"""Demo investor seed data."""

from datetime import date
from decimal import Decimal

from investhome_api.models.investor import (
    AccreditationStatus,
    InvestmentModel,
    InvestorStatus,
    InvestorType,
    RiskProfile,
)

DEMO_INVESTORS: list[dict[str, object]] = [
    {
        "full_name": "Ayşe Yılmaz",
        "email": "ayse.yilmaz@example.com",
        "phone": "+90 532 100 2001",
        "country": "Türkiye",
        "city": "İstanbul",
        "investor_type": InvestorType.INDIVIDUAL,
        "accreditation_status": AccreditationStatus.SELF_CERTIFIED,
        "preferred_investment_model": InvestmentModel.RENTAL_INCOME,
        "investment_capacity": Decimal("1500000.00"),
        "minimum_ticket": Decimal("250000.00"),
        "maximum_ticket": Decimal("750000.00"),
        "preferred_markets": "İstanbul, Ankara, İzmir",
        "preferred_projects": "Konut geliştirme, karma kullanım",
        "risk_profile": RiskProfile.BALANCED,
        "status": InvestorStatus.ACTIVE,
        "assigned_to": "Emre Kaya",
        "source": "Referral",
        "notes": "Demo yatırımcı — kira getirisi odaklı bireysel profil.",
        "last_contact_date": date(2026, 6, 20),
        "next_follow_up_date": date(2026, 7, 28),
    },
    {
        "full_name": "Marmara Capital Partners",
        "email": "invest@marmara-capital.example.com",
        "phone": "+90 212 555 0100",
        "country": "Türkiye",
        "city": "İstanbul",
        "investor_type": InvestorType.COMPANY,
        "accreditation_status": AccreditationStatus.VERIFIED,
        "preferred_investment_model": InvestmentModel.DEVELOPMENT_EQUITY,
        "investment_capacity": Decimal("12000000.00"),
        "minimum_ticket": Decimal("2000000.00"),
        "maximum_ticket": Decimal("5000000.00"),
        "preferred_markets": "Türkiye, Balkanlar",
        "preferred_projects": "Lüks konut, otel",
        "risk_profile": RiskProfile.GROWTH,
        "status": InvestorStatus.INVESTED,
        "assigned_to": "Sarah Chen",
        "source": "Exhibition",
        "notes": "Demo yatırımcı — aktif proje geliştirme ortağı.",
        "last_contact_date": date(2026, 7, 1),
        "next_follow_up_date": date(2026, 8, 5),
    },
    {
        "full_name": "James Whitfield",
        "email": "j.whitfield@example.com",
        "phone": "+1 415 555 0199",
        "country": "United States",
        "city": "San Francisco",
        "investor_type": InvestorType.INDIVIDUAL,
        "accreditation_status": AccreditationStatus.VERIFIED,
        "preferred_investment_model": InvestmentModel.JOINT_VENTURE,
        "investment_capacity": Decimal("8000000.00"),
        "minimum_ticket": Decimal("1000000.00"),
        "maximum_ticket": Decimal("3000000.00"),
        "preferred_markets": "United States, Türkiye, UAE",
        "preferred_projects": "Mixed-use, hospitality",
        "risk_profile": RiskProfile.AGGRESSIVE,
        "status": InvestorStatus.QUALIFIED,
        "assigned_to": "James Okonkwo",
        "source": "LinkedIn",
        "notes": "Demo investor — US HNW seeking international JV opportunities.",
        "last_contact_date": date(2026, 6, 15),
        "next_follow_up_date": date(2026, 7, 20),
    },
    {
        "full_name": "Al-Rashid Family Office",
        "email": "familyoffice@alrashid.example.com",
        "phone": "+971 4 555 8800",
        "country": "United Arab Emirates",
        "city": "Dubai",
        "investor_type": InvestorType.FAMILY_OFFICE,
        "accreditation_status": AccreditationStatus.VERIFIED,
        "preferred_investment_model": InvestmentModel.BULK_PURCHASE,
        "investment_capacity": Decimal("25000000.00"),
        "minimum_ticket": Decimal("5000000.00"),
        "maximum_ticket": Decimal("10000000.00"),
        "preferred_markets": "Middle East, Türkiye, Europe",
        "preferred_projects": "Premium residential portfolios",
        "risk_profile": RiskProfile.BALANCED,
        "status": InvestorStatus.INVESTED,
        "assigned_to": "Sarah Chen",
        "source": "Partner",
        "notes": "Demo investor — family office with bulk acquisition mandate.",
        "last_contact_date": date(2026, 7, 5),
        "next_follow_up_date": date(2026, 8, 10),
    },
    {
        "full_name": "Nordic Growth Fund II",
        "email": "ir@nordicgrowth.example.com",
        "phone": "+46 8 555 4400",
        "country": "Sweden",
        "city": "Stockholm",
        "investor_type": InvestorType.FUND,
        "accreditation_status": AccreditationStatus.VERIFIED,
        "preferred_investment_model": InvestmentModel.DEVELOPMENT_EQUITY,
        "investment_capacity": Decimal("45000000.00"),
        "minimum_ticket": Decimal("3000000.00"),
        "maximum_ticket": Decimal("8000000.00"),
        "preferred_markets": "Europe, Türkiye",
        "preferred_projects": "Sustainable residential, ESG-led",
        "risk_profile": RiskProfile.GROWTH,
        "status": InvestorStatus.ACTIVE,
        "assigned_to": "Emily Ross",
        "source": "Referral",
        "notes": "Demo investor — European fund targeting emerging market development.",
        "last_contact_date": date(2026, 6, 28),
        "next_follow_up_date": date(2026, 7, 30),
    },
    {
        "full_name": "Helena Bauer",
        "email": "helena.bauer@example.com",
        "phone": "+49 30 555 7700",
        "country": "Germany",
        "city": "Berlin",
        "investor_type": InvestorType.INDIVIDUAL,
        "accreditation_status": AccreditationStatus.SELF_CERTIFIED,
        "preferred_investment_model": InvestmentModel.RENTAL_INCOME,
        "investment_capacity": Decimal("2200000.00"),
        "minimum_ticket": Decimal("300000.00"),
        "maximum_ticket": Decimal("900000.00"),
        "preferred_markets": "Germany, Türkiye, Spain",
        "preferred_projects": "Buy-to-let apartments",
        "risk_profile": RiskProfile.CONSERVATIVE,
        "status": InvestorStatus.CONTACTED,
        "assigned_to": "Emre Kaya",
        "source": "Website",
        "notes": "Demo investor — income-focused European individual.",
        "last_contact_date": date(2026, 6, 10),
        "next_follow_up_date": date(2026, 7, 18),
    },
    {
        "full_name": "Continental Institutional RE",
        "email": "allocations@continental-re.example.com",
        "phone": "+33 1 555 6600",
        "country": "France",
        "city": "Paris",
        "investor_type": InvestorType.INSTITUTIONAL,
        "accreditation_status": AccreditationStatus.VERIFIED,
        "preferred_investment_model": InvestmentModel.DEBT_INVESTMENT,
        "investment_capacity": Decimal("60000000.00"),
        "minimum_ticket": Decimal("5000000.00"),
        "maximum_ticket": Decimal("15000000.00"),
        "preferred_markets": "Europe, Middle East",
        "preferred_projects": "Senior debt, mezzanine",
        "risk_profile": RiskProfile.CONSERVATIVE,
        "status": InvestorStatus.QUALIFIED,
        "assigned_to": "James Okonkwo",
        "source": "Partner",
        "notes": "Demo investor — institutional lender evaluating regional pipeline.",
        "last_contact_date": date(2026, 7, 8),
        "next_follow_up_date": date(2026, 8, 1),
    },
    {
        "full_name": "Gulf Bridge Brokers",
        "email": "deals@gulfbridge.example.com",
        "phone": "+966 11 555 3300",
        "country": "Saudi Arabia",
        "city": "Riyadh",
        "investor_type": InvestorType.BROKER,
        "accreditation_status": AccreditationStatus.UNKNOWN,
        "preferred_investment_model": InvestmentModel.OTHER,
        "investment_capacity": Decimal("10000000.00"),
        "minimum_ticket": Decimal("500000.00"),
        "maximum_ticket": Decimal("2500000.00"),
        "preferred_markets": "GCC, Türkiye",
        "preferred_projects": "Introductory mandates",
        "risk_profile": RiskProfile.BALANCED,
        "status": InvestorStatus.FOLLOW_UP,
        "assigned_to": "Sarah Chen",
        "source": "Cold Outreach",
        "notes": "Demo investor — broker channel for GCC capital introductions.",
        "last_contact_date": date(2026, 5, 30),
        "next_follow_up_date": date(2026, 7, 15),
    },
    {
        "full_name": "Mehmet & Partners Advisory",
        "email": "mehmet@partners-advisory.example.com",
        "phone": "+90 312 555 2200",
        "country": "Türkiye",
        "city": "Ankara",
        "investor_type": InvestorType.REFERRAL_PARTNER,
        "accreditation_status": AccreditationStatus.UNKNOWN,
        "preferred_investment_model": InvestmentModel.JOINT_VENTURE,
        "investment_capacity": Decimal("5000000.00"),
        "minimum_ticket": Decimal("250000.00"),
        "maximum_ticket": Decimal("1500000.00"),
        "preferred_markets": "Türkiye",
        "preferred_projects": "Referral pipeline",
        "risk_profile": RiskProfile.GROWTH,
        "status": InvestorStatus.PROSPECT,
        "assigned_to": "Emre Kaya",
        "source": "Referral",
        "notes": "Demo yatırımcı — yerel referans ortağı ağı.",
        "last_contact_date": date(2026, 6, 5),
        "next_follow_up_date": date(2026, 7, 22),
    },
    {
        "full_name": "Atlantic Fix & Flip Group",
        "email": "capital@atlanticff.example.com",
        "phone": "+1 305 555 1188",
        "country": "United States",
        "city": "Miami",
        "investor_type": InvestorType.COMPANY,
        "accreditation_status": AccreditationStatus.VERIFIED,
        "preferred_investment_model": InvestmentModel.FIX_AND_FLIP,
        "investment_capacity": Decimal("9000000.00"),
        "minimum_ticket": Decimal("400000.00"),
        "maximum_ticket": Decimal("2000000.00"),
        "preferred_markets": "United States, Türkiye coastal",
        "preferred_projects": "Renovation, value-add",
        "risk_profile": RiskProfile.AGGRESSIVE,
        "status": InvestorStatus.ACTIVE,
        "assigned_to": "Emily Ross",
        "source": "Exhibition",
        "notes": "Demo investor — value-add operator expanding to Mediterranean.",
        "last_contact_date": date(2026, 7, 2),
        "next_follow_up_date": date(2026, 7, 25),
    },
    {
        "full_name": "Vienna Heritage Fund",
        "email": "info@viennaheritage.example.com",
        "phone": "+43 1 555 9900",
        "country": "Austria",
        "city": "Vienna",
        "investor_type": InvestorType.FUND,
        "accreditation_status": AccreditationStatus.VERIFIED,
        "preferred_investment_model": InvestmentModel.RENTAL_INCOME,
        "investment_capacity": Decimal("18000000.00"),
        "minimum_ticket": Decimal("1000000.00"),
        "maximum_ticket": Decimal("4000000.00"),
        "preferred_markets": "Central Europe, Türkiye",
        "preferred_projects": "Heritage restoration, rental yield",
        "risk_profile": RiskProfile.BALANCED,
        "status": InvestorStatus.DORMANT,
        "assigned_to": "James Okonkwo",
        "source": "Partner",
        "notes": "Demo investor — dormant fund relationship pending reactivation.",
        "last_contact_date": date(2026, 3, 12),
        "next_follow_up_date": date(2026, 9, 1),
    },
    {
        "full_name": "Karim El-Sayed",
        "email": "karim.elsayed@example.com",
        "phone": "+20 2 555 4400",
        "country": "Egypt",
        "city": "Cairo",
        "investor_type": InvestorType.INDIVIDUAL,
        "accreditation_status": AccreditationStatus.NOT_ACCREDITED,
        "preferred_investment_model": InvestmentModel.DEVELOPMENT_EQUITY,
        "investment_capacity": Decimal("750000.00"),
        "minimum_ticket": Decimal("100000.00"),
        "maximum_ticket": Decimal("350000.00"),
        "preferred_markets": "North Africa, Türkiye",
        "preferred_projects": "Affordable housing",
        "risk_profile": RiskProfile.GROWTH,
        "status": InvestorStatus.REJECTED,
        "assigned_to": "Emre Kaya",
        "source": "Website",
        "notes": "Demo investor — profile reviewed and declined for current mandate.",
        "last_contact_date": date(2026, 4, 18),
        "next_follow_up_date": None,
    },
]
