"""Demo project seed data."""

from datetime import date
from decimal import Decimal

from investhome_api.models.project import DevelopmentType, ProjectStatus, ProjectType

DEMO_PROJECTS: list[dict[str, object]] = [
    {
        "project_code": "PRJ-TEMP-001",
        "project_name": "The Temple",
        "address": "1610 Columbia Rd NW",
        "city": "Washington",
        "state": "DC",
        "postal_code": "20009",
        "country": "United States",
        "project_type": ProjectType.MIXED_USE,
        "development_type": DevelopmentType.GROUND_UP,
        "project_status": ProjectStatus.CONSTRUCTION,
        "ownership_entity": "Investhome Temple LLC",
        "total_units": 72,
        "residential_units": 64,
        "commercial_units": 8,
        "gross_square_feet": 98500,
        "acquisition_price": Decimal("8200000.00"),
        "total_development_cost": Decimal("48500000.00"),
        "current_project_value": Decimal("52000000.00"),
        "projected_sale_value": Decimal("62000000.00"),
        "equity_required": Decimal("14500000.00"),
        "equity_raised": Decimal("11200000.00"),
        "debt_amount": Decimal("34000000.00"),
        "loan_to_cost": Decimal("70.1000"),
        "projected_revenue": Decimal("62000000.00"),
        "projected_profit": Decimal("13500000.00"),
        "projected_roi": Decimal("27.8000"),
        "projected_irr": Decimal("19.5000"),
        "start_date": date(2024, 3, 1),
        "target_completion_date": date(2027, 6, 30),
        "assigned_project_manager": "Sarah Chen",
        "description": "Demo project — mixed-use redevelopment in Adams Morgan with retail podium and residential above.",
        "notes": "Demo data — approximate values for development tracking only.",
    },
    {
        "project_code": "PRJ-UNIL-002",
        "project_name": "UniLoft",
        "address": "300 I St NE",
        "city": "Washington",
        "state": "DC",
        "postal_code": "20002",
        "country": "United States",
        "project_type": ProjectType.RESIDENTIAL,
        "development_type": DevelopmentType.RENOVATION,
        "project_status": ProjectStatus.LEASING,
        "ownership_entity": "UniLoft DC Holdings LLC",
        "total_units": 48,
        "residential_units": 48,
        "commercial_units": 0,
        "gross_square_feet": 54200,
        "acquisition_price": Decimal("6100000.00"),
        "total_development_cost": Decimal("18200000.00"),
        "current_project_value": Decimal("21500000.00"),
        "projected_sale_value": Decimal("24000000.00"),
        "equity_required": Decimal("6200000.00"),
        "equity_raised": Decimal("6200000.00"),
        "debt_amount": Decimal("12000000.00"),
        "loan_to_cost": Decimal("65.9000"),
        "projected_revenue": Decimal("24000000.00"),
        "projected_profit": Decimal("5800000.00"),
        "projected_roi": Decimal("31.9000"),
        "projected_irr": Decimal("22.1000"),
        "start_date": date(2023, 8, 15),
        "target_completion_date": date(2026, 3, 31),
        "actual_completion_date": date(2026, 2, 28),
        "assigned_project_manager": "Marcus Webb",
        "description": "Demo project — adaptive reuse of warehouse into loft-style rental apartments near NoMa.",
        "notes": "Demo data — leasing at 78% as of Q2 2026.",
    },
    {
        "project_code": "PRJ-309H-003",
        "project_name": "309 H St NE",
        "address": "309 H St NE",
        "city": "Washington",
        "state": "DC",
        "postal_code": "20002",
        "country": "United States",
        "project_type": ProjectType.MULTIFAMILY,
        "development_type": DevelopmentType.VALUE_ADD,
        "project_status": ProjectStatus.PRE_DEVELOPMENT,
        "ownership_entity": "H Street Development Partners LLC",
        "total_units": 24,
        "residential_units": 24,
        "commercial_units": 0,
        "gross_square_feet": 28600,
        "acquisition_price": Decimal("4200000.00"),
        "total_development_cost": Decimal("9800000.00"),
        "current_project_value": Decimal("10500000.00"),
        "projected_sale_value": Decimal("13200000.00"),
        "equity_required": Decimal("3200000.00"),
        "equity_raised": Decimal("1800000.00"),
        "debt_amount": Decimal("6600000.00"),
        "loan_to_cost": Decimal("67.3000"),
        "projected_revenue": Decimal("13200000.00"),
        "projected_profit": Decimal("3400000.00"),
        "projected_roi": Decimal("34.7000"),
        "projected_irr": Decimal("24.8000"),
        "start_date": date(2026, 1, 10),
        "target_completion_date": date(2028, 12, 31),
        "assigned_project_manager": "Emre Kaya",
        "description": "Demo project — value-add multifamily repositioning on H Street corridor.",
        "notes": "Demo data — entitlements in progress.",
    },
    {
        "project_code": "PRJ-CAMP-004",
        "project_name": "The Campus",
        "address": "3220 & 3224 Minnesota Ave NE",
        "city": "Washington",
        "state": "DC",
        "postal_code": "20019",
        "country": "United States",
        "project_type": ProjectType.MIXED_USE,
        "development_type": DevelopmentType.GROUND_UP,
        "project_status": ProjectStatus.PERMITTING,
        "ownership_entity": "Campus Ward LLC",
        "total_units": 156,
        "residential_units": 140,
        "commercial_units": 16,
        "gross_square_feet": 168000,
        "acquisition_price": Decimal("11500000.00"),
        "total_development_cost": Decimal("72000000.00"),
        "current_project_value": Decimal("68000000.00"),
        "projected_sale_value": Decimal("89000000.00"),
        "equity_required": Decimal("22000000.00"),
        "equity_raised": Decimal("8500000.00"),
        "debt_amount": Decimal("50000000.00"),
        "loan_to_cost": Decimal("69.4000"),
        "projected_revenue": Decimal("89000000.00"),
        "projected_profit": Decimal("17000000.00"),
        "projected_roi": Decimal("23.6000"),
        "projected_irr": Decimal("18.2000"),
        "start_date": date(2025, 11, 1),
        "target_completion_date": date(2029, 9, 30),
        "assigned_project_manager": "Sarah Chen",
        "description": "Demo project — two-parcel campus-style mixed-use development in Ward 7.",
        "notes": "Demo data — joint venture discussions ongoing.",
    },
    {
        "project_code": "PRJ-1812H-005",
        "project_name": "1812 H Place NE",
        "address": "1812 H Place NE",
        "city": "Washington",
        "state": "DC",
        "postal_code": "20002",
        "country": "United States",
        "project_type": ProjectType.TOWNHOME,
        "development_type": DevelopmentType.GROUND_UP,
        "project_status": ProjectStatus.PERMITTING,
        "ownership_entity": "H Place Townhomes LLC",
        "total_units": 12,
        "residential_units": 12,
        "commercial_units": 0,
        "gross_square_feet": 22400,
        "acquisition_price": Decimal("2100000.00"),
        "total_development_cost": Decimal("7800000.00"),
        "current_project_value": Decimal("8100000.00"),
        "projected_sale_value": Decimal("10200000.00"),
        "equity_required": Decimal("2600000.00"),
        "equity_raised": Decimal("2100000.00"),
        "debt_amount": Decimal("5200000.00"),
        "loan_to_cost": Decimal("66.7000"),
        "projected_revenue": Decimal("10200000.00"),
        "projected_profit": Decimal("2400000.00"),
        "projected_roi": Decimal("30.8000"),
        "projected_irr": Decimal("21.4000"),
        "start_date": date(2026, 4, 1),
        "target_completion_date": date(2027, 11, 30),
        "assigned_project_manager": "Marcus Webb",
        "description": "Demo project — boutique townhome development near Trinidad.",
        "notes": "Demo data — pre-sales not yet launched.",
    },
    {
        "project_code": "PRJ-NOMA-006",
        "project_name": "NoMa Gateway",
        "address": "1200 3rd St NE",
        "city": "Washington",
        "state": "DC",
        "postal_code": "20002",
        "country": "United States",
        "project_type": ProjectType.CONDOMINIUM,
        "development_type": DevelopmentType.GROUND_UP,
        "project_status": ProjectStatus.SALES,
        "ownership_entity": "Investhome NoMa LLC",
        "total_units": 86,
        "residential_units": 86,
        "commercial_units": 0,
        "gross_square_feet": 112000,
        "acquisition_price": Decimal("9800000.00"),
        "total_development_cost": Decimal("55200000.00"),
        "current_project_value": Decimal("58500000.00"),
        "projected_sale_value": Decimal("71000000.00"),
        "equity_required": Decimal("16500000.00"),
        "equity_raised": Decimal("16500000.00"),
        "debt_amount": Decimal("38700000.00"),
        "loan_to_cost": Decimal("70.1000"),
        "projected_revenue": Decimal("71000000.00"),
        "projected_profit": Decimal("15800000.00"),
        "projected_roi": Decimal("28.6000"),
        "projected_irr": Decimal("20.3000"),
        "start_date": date(2023, 5, 1),
        "target_completion_date": date(2026, 8, 31),
        "assigned_project_manager": "Emre Kaya",
        "description": "Demo project — for-sale condominium tower near NoMa-Gallaudet Metro.",
        "notes": "Demo data — 42% of units under contract.",
    },
    {
        "project_code": "PRJ-PIPE-007",
        "project_name": "Anacostia Riverfront Parcel",
        "address": "1500 South Capitol St SE",
        "city": "Washington",
        "state": "DC",
        "postal_code": "20003",
        "country": "United States",
        "project_type": ProjectType.LAND,
        "development_type": DevelopmentType.LAND_DEVELOPMENT,
        "project_status": ProjectStatus.PIPELINE,
        "ownership_entity": "Investhome Land Co.",
        "total_units": 0,
        "residential_units": 0,
        "commercial_units": 0,
        "gross_square_feet": 0,
        "acquisition_price": Decimal("3500000.00"),
        "total_development_cost": Decimal("3500000.00"),
        "current_project_value": Decimal("3800000.00"),
        "projected_sale_value": Decimal("12000000.00"),
        "equity_required": Decimal("3500000.00"),
        "equity_raised": Decimal("500000.00"),
        "debt_amount": Decimal("0.00"),
        "loan_to_cost": Decimal("0.0000"),
        "projected_revenue": Decimal("12000000.00"),
        "projected_profit": Decimal("8500000.00"),
        "projected_roi": Decimal("242.9000"),
        "projected_irr": Decimal("35.0000"),
        "start_date": None,
        "target_completion_date": date(2030, 12, 31),
        "assigned_project_manager": "Sarah Chen",
        "description": "Demo project — early-stage land assemblage along the Anacostia riverfront.",
        "notes": "Demo data — feasibility study in progress.",
    },
]
