import type { ReportsWorkspacePreview } from './reports-model';

/** Typed local fixtures for Reports UX review — no live API / reporting engine. */
export function makeReportsPreview(): ReportsWorkspacePreview {
  return {
    filters: {
      dateRange: 'rangeWeek',
      comparison: 'previousPeriod',
      teams: ['all', 'sales', 'enterprise', 'partners'],
      users: ['all', 'ayse', 'mehmet', 'zeynep', 'can', 'elif'],
      sources: ['all', 'referral', 'event', 'website', 'email', 'social', 'other'],
    },
    kpis: [
      {
        key: 'totalRevenue',
        value: '$2.48M',
        delta: '+18.4%',
        deltaTone: 'up',
        sparkValues: [42, 48, 45, 52, 58, 61, 68, 72, 70, 78, 84, 90],
        sparkColor: '#2f8a5b',
      },
      {
        key: 'newOpportunities',
        value: '156',
        delta: '+24.6%',
        deltaTone: 'up',
        sparkValues: [18, 22, 20, 28, 30, 26, 34, 38, 36, 42, 46, 52],
        sparkColor: '#7b5ea7',
      },
      {
        key: 'wonDeals',
        value: '42',
        delta: '+16.2%',
        deltaTone: 'up',
        sparkValues: [8, 10, 9, 12, 11, 14, 13, 16, 15, 18, 17, 20],
        sparkColor: '#2f6fed',
      },
      {
        key: 'activeCustomers',
        value: '248',
        delta: '+11.7%',
        deltaTone: 'up',
        sparkValues: [120, 128, 132, 140, 148, 152, 160, 168, 176, 184, 192, 200],
        sparkColor: '#c77938',
      },
      {
        key: 'meetings',
        value: '186',
        delta: '+9.8%',
        deltaTone: 'up',
        sparkValues: [22, 24, 21, 28, 26, 30, 29, 34, 32, 36, 38, 40],
        sparkColor: '#c45c5c',
      },
    ],
    revenueTrend: [
      { label: '21', current: 180, previous: 140 },
      { label: '22', current: 260, previous: 190 },
      { label: '23', current: 320, previous: 250 },
      { label: '24', current: 410, previous: 300 },
      { label: '25', current: 520, previous: 360 },
      { label: '26', current: 610, previous: 420 },
      { label: '27', current: 720, previous: 480 },
    ],
    funnel: [
      { key: 'new', valueLabel: '$4.52M', count: 156, widthPct: 100 },
      { key: 'review', valueLabel: '$3.18M', count: 98, widthPct: 82 },
      { key: 'proposal', valueLabel: '$2.64M', count: 72, widthPct: 66 },
      { key: 'negotiation', valueLabel: '$1.92M', count: 54, widthPct: 50 },
      { key: 'won', valueLabel: '$1.24M', count: 42, widthPct: 36 },
    ],
    performanceSummary: [
      { key: 'totalRevenue', value: '$2.48M', delta: '+18.4%', deltaTone: 'up' },
      { key: 'newOpportunities', value: '156', delta: '+24.6%', deltaTone: 'up' },
      { key: 'wonDeals', value: '42', delta: '+16.2%', deltaTone: 'up' },
      { key: 'avgDealSize', value: '$58.9K', delta: '+7.3%', deltaTone: 'up' },
      { key: 'winRate', value: '26.9%', delta: '+3.1%', deltaTone: 'up' },
    ],
    team: [
      {
        id: 't-ayse',
        name: 'Ayşe Yılmaz',
        initials: 'AY',
        tone: 'navy',
        revenue: '$642K',
        opportunities: 38,
        won: 12,
        sparkValues: [12, 16, 14, 20, 22, 26, 28],
        trendTone: 'up',
      },
      {
        id: 't-mehmet',
        name: 'Mehmet Kaya',
        initials: 'MK',
        tone: 'cyan',
        revenue: '$518K',
        opportunities: 31,
        won: 9,
        sparkValues: [10, 12, 15, 14, 18, 20, 22],
        trendTone: 'up',
      },
      {
        id: 't-zeynep',
        name: 'Zeynep Demir',
        initials: 'ZD',
        tone: 'green',
        revenue: '$456K',
        opportunities: 28,
        won: 8,
        sparkValues: [8, 11, 10, 14, 13, 17, 19],
        trendTone: 'up',
      },
      {
        id: 't-can',
        name: 'Can Öztürk',
        initials: 'CÖ',
        tone: 'violet',
        revenue: '$392K',
        opportunities: 24,
        won: 7,
        sparkValues: [14, 13, 12, 15, 14, 16, 15],
        trendTone: 'neutral',
      },
      {
        id: 't-elif',
        name: 'Elif Arslan',
        initials: 'EA',
        tone: 'amber',
        revenue: '$348K',
        opportunities: 22,
        won: 6,
        sparkValues: [9, 10, 12, 11, 13, 12, 14],
        trendTone: 'up',
      },
    ],
    monthlyComparison: [
      { label: 'jan', current: 420, previous: 360 },
      { label: 'feb', current: 480, previous: 390 },
      { label: 'mar', current: 520, previous: 450 },
      { label: 'apr', current: 610, previous: 500 },
      { label: 'may', current: 680, previous: 540 },
      { label: 'jun', current: 720, previous: 580 },
    ],
    goals: [
      { key: 'revenue', target: '$2.80M', actual: '$2.48M', pct: 89, tone: 'warning' },
      { key: 'newOpportunities', target: '140', actual: '156', pct: 111, tone: 'success' },
      { key: 'wonDeals', target: '50', actual: '42', pct: 84, tone: 'warning' },
      { key: 'meetings', target: '200', actual: '186', pct: 93, tone: 'success' },
      { key: 'activeCustomers', target: '260', actual: '248', pct: 95, tone: 'success' },
    ],
    sources: [
      { key: 'referral', pct: 38 },
      { key: 'event', pct: 24 },
      { key: 'website', pct: 16 },
      { key: 'email', pct: 12 },
      { key: 'social', pct: 7 },
      { key: 'other', pct: 3 },
    ],
    quickReports: [
      { key: 'salesPerformance', icon: 'trendingUp' },
      { key: 'pipeline', icon: 'barChart' },
      { key: 'customerAnalysis', icon: 'users' },
      { key: 'activityAnalysis', icon: 'activity' },
      { key: 'wonOpportunities', icon: 'check' },
    ],
    aiInsights: [
      { id: 'ai-1', textKey: 'referralMomentum' },
      { id: 'ai-2', textKey: 'negotiationGap' },
      { id: 'ai-3', textKey: 'teamLead' },
    ],
  };
}