import type { MatchWorkspacePreview } from '@/app/workspaces/crm/matches/matches-model';

/** Typed local fixtures for Matches UX review — no live API calls. */
export function makeMatchesPreview(): MatchWorkspacePreview {
  return {
    customer: {
      id: 'ui-preview-ahmet-yilmaz',
      displayName: 'Ahmet Yılmaz',
      email: 'ahmet.yilmaz@email.com',
      phone: '+90 532 456 78 90',
      verified: true,
      profileHref: '/ui-preview/customer-profile',
      initials: 'AY',
      photoTone: 'warm',
      budget: '$250k – $400k',
      investmentGoalKey: 'rentalIncome',
      preferredAreas: 'Washington DC, Miami',
      roiTarget: '%8 – %12',
      riskProfileKey: 'medium',
      languageKey: 'turkish',
      nationalityKey: 'turkey',
      investmentHorizonKey: '3-5y',
      financingKey: 'mortgageEligible',
      investorTypeKey: 'individual',
      preferredUnit: '1+1, 2+1',
    },
    recommendationId: 'match-marina-heights',
    recommendationSummaryKey: 'marinaHeights',
    totalMatches: 24,
    matches: [
      {
        id: 'match-marina-heights',
        projectName: 'Marina Heights',
        location: 'Miami, FL',
        developer: 'Coastal Developers',
        price: '$325.000',
        unitType: '1+1',
        area: '52 m²',
        roi: '%11.2',
        monthlyRent: '$2.850',
        monthlyCashFlow: '$1.240',
        deliveryDate: 'Q2 2027',
        status: 'construction',
        matchScore: 96,
        scene: 'marina',
        whyKeys: ['withinBudget', 'highRentalYield', 'preferredArea', 'strongCashFlow'],
        favorite: true,
      },
      {
        id: 'match-ocean-view',
        projectName: 'Ocean View Residences',
        location: 'Miami Beach, FL',
        developer: 'Atlantic Group',
        price: '$380.000',
        unitType: '2+1',
        area: '68 m²',
        roi: '%10.4',
        monthlyRent: '$3.200',
        monthlyCashFlow: '$1.080',
        deliveryDate: 'Q4 2026',
        status: 'preSales',
        matchScore: 92,
        scene: 'ocean',
        whyKeys: ['withinBudget', 'preferredArea', 'nearTargetRoi', 'developerTrackRecord'],
      },
      {
        id: 'match-park-avenue',
        projectName: 'Park Avenue Tower',
        location: 'Washington DC',
        developer: 'Capitol Homes',
        price: '$295.000',
        unitType: '1+1',
        area: '48 m²',
        roi: '%9.8',
        monthlyRent: '$2.450',
        monthlyCashFlow: '$980',
        deliveryDate: 'Q1 2027',
        status: 'construction',
        matchScore: 87,
        scene: 'park',
        whyKeys: ['withinBudget', 'preferredArea', 'stableMarket', 'mortgageFriendly'],
      },
      {
        id: 'match-sunset-boulevard',
        projectName: 'Sunset Boulevard',
        location: 'Miami, FL',
        developer: 'Horizon Living',
        price: '$350.000',
        unitType: '2+1',
        area: '74 m²',
        roi: '%9.1',
        monthlyRent: '$2.980',
        monthlyCashFlow: '$890',
        deliveryDate: 'Q3 2027',
        status: 'construction',
        matchScore: 84,
        scene: 'sunset',
        whyKeys: ['withinBudget', 'highRentalYield', 'unitTypeMatch', 'growthCorridor'],
      },
      {
        id: 'match-skyline-lofts',
        projectName: 'Skyline Lofts',
        location: 'Washington DC',
        developer: 'Metro Build',
        price: '$275.000',
        unitType: '1+1',
        area: '45 m²',
        roi: '%10.1',
        monthlyRent: '$2.320',
        monthlyCashFlow: '$1.050',
        deliveryDate: 'Q2 2026',
        status: 'ready',
        matchScore: 81,
        scene: 'sky',
        whyKeys: ['withinBudget', 'nearTargetRoi', 'readyDelivery', 'preferredArea'],
      },
      {
        id: 'match-garden-court',
        projectName: 'Garden Court Residences',
        location: 'Miami, FL',
        developer: 'Palm Partners',
        price: '$310.000',
        unitType: '1+1',
        area: '55 m²',
        roi: '%8.9',
        monthlyRent: '$2.600',
        monthlyCashFlow: '$860',
        deliveryDate: 'Q4 2027',
        status: 'preSales',
        matchScore: 78,
        scene: 'garden',
        whyKeys: ['withinBudget', 'unitTypeMatch', 'preferredArea', 'developerTrackRecord'],
      },
      {
        id: 'match-harbor-point',
        projectName: 'Harbor Point',
        location: 'Miami Beach, FL',
        developer: 'Coastal Developers',
        price: '$395.000',
        unitType: '2+1',
        area: '72 m²',
        roi: '%9.6',
        monthlyRent: '$3.350',
        monthlyCashFlow: '$1.020',
        deliveryDate: 'Q1 2028',
        status: 'construction',
        matchScore: 76,
        scene: 'marina',
        whyKeys: ['nearBudgetCeiling', 'highRentalYield', 'preferredArea', 'strongCashFlow'],
      },
      {
        id: 'match-capitol-square',
        projectName: 'Capitol Square',
        location: 'Washington DC',
        developer: 'Capitol Homes',
        price: '$265.000',
        unitType: '1+1',
        area: '46 m²',
        roi: '%8.7',
        monthlyRent: '$2.180',
        monthlyCashFlow: '$820',
        deliveryDate: 'Ready',
        status: 'ready',
        matchScore: 74,
        scene: 'park',
        whyKeys: ['withinBudget', 'readyDelivery', 'stableMarket', 'mortgageFriendly'],
      },
      {
        id: 'match-bayfront',
        projectName: 'Bayfront Suites',
        location: 'Miami, FL',
        developer: 'Atlantic Group',
        price: '$340.000',
        unitType: '2+1',
        area: '70 m²',
        roi: '%9.3',
        monthlyRent: '$2.900',
        monthlyCashFlow: '$910',
        deliveryDate: 'Q3 2026',
        status: 'preSales',
        matchScore: 72,
        scene: 'ocean',
        whyKeys: ['withinBudget', 'unitTypeMatch', 'preferredArea', 'nearTargetRoi'],
      },
      {
        id: 'match-riverwalk',
        projectName: 'Riverwalk Residences',
        location: 'Washington DC',
        developer: 'Metro Build',
        price: '$288.000',
        unitType: '1+1',
        area: '50 m²',
        roi: '%8.5',
        monthlyRent: '$2.280',
        monthlyCashFlow: '$790',
        deliveryDate: 'Q2 2027',
        status: 'construction',
        matchScore: 70,
        scene: 'garden',
        whyKeys: ['withinBudget', 'preferredArea', 'mortgageFriendly', 'stableMarket'],
      },
      {
        id: 'match-coral-keys',
        projectName: 'Coral Keys',
        location: 'Miami, FL',
        developer: 'Horizon Living',
        price: '$360.000',
        unitType: '2+1',
        area: '76 m²',
        roi: '%8.8',
        monthlyRent: '$3.050',
        monthlyCashFlow: '$870',
        deliveryDate: 'Q4 2027',
        status: 'construction',
        matchScore: 68,
        scene: 'sunset',
        whyKeys: ['withinBudget', 'unitTypeMatch', 'growthCorridor', 'developerTrackRecord'],
      },
      {
        id: 'match-district-one',
        projectName: 'District One',
        location: 'Washington DC',
        developer: 'Palm Partners',
        price: '$255.000',
        unitType: '1+1',
        area: '44 m²',
        roi: '%9.0',
        monthlyRent: '$2.150',
        monthlyCashFlow: '$940',
        deliveryDate: 'Q1 2027',
        status: 'preSales',
        matchScore: 66,
        scene: 'sky',
        whyKeys: ['withinBudget', 'nearTargetRoi', 'preferredArea', 'strongCashFlow'],
      },
    ],
    riskAlerts: [
      {
        id: 'risk-delivery',
        tone: 'warning',
        titleKey: 'deliveryHorizon',
        bodyKey: 'deliveryHorizonBody',
      },
      {
        id: 'risk-currency',
        tone: 'info',
        titleKey: 'currencyExposure',
        bodyKey: 'currencyExposureBody',
      },
    ],
    documents: [
      { id: 'doc-pitch', nameKey: 'investmentPitch', metaKey: 'pdfMeta' },
      { id: 'doc-finance', nameKey: 'financialAnalysis', metaKey: 'xlsxMeta' },
      { id: 'doc-compare', nameKey: 'comparisonSheet', metaKey: 'pdfMeta' },
    ],
    activities: [
      { id: 'act-ai', titleKey: 'aiAnalysisCompleted', timeKey: 'hoursAgo2' },
      { id: 'act-projects', titleKey: 'projectsAdded', timeKey: 'yesterday' },
      { id: 'act-prefs', titleKey: 'preferenceUpdated', timeKey: 'daysAgo3' },
    ],
  };
}
