import type { ActivityWorkspacePreview } from './activities-model';

/** Typed local fixtures for Activities UX review — no live API calls. */
export function makeActivitiesPreview(): ActivityWorkspacePreview {
  return {
    totalActivities: 247,
    kpis: [
      {
        key: 'today',
        value: 24,
        hintKey: 'todayHint',
        delta: '+18%',
        deltaTone: 'up',
      },
      {
        key: 'completed',
        value: 18,
        hintKey: 'completedHint',
        delta: '+12%',
        deltaTone: 'up',
      },
      {
        key: 'pending',
        value: 32,
        hintKey: 'pendingHint',
        delta: '+8%',
        deltaTone: 'up',
      },
      {
        key: 'overdue',
        value: 7,
        hintKey: 'overdueHint',
        delta: '-5%',
        deltaTone: 'down',
      },
    ],
    daySummary: {
      completed: 18,
      pending: 32,
      overdue: 7,
      assessmentKey: 'dayAssessment',
    },
    customers: [
      'Ahmet Yılmaz',
      'Ayşe Demir',
      'Mehmet Kaya',
      'Zeynep Arslan',
      'Elif Yıldız',
      'Can Özkan',
      'Burak Şahin',
      'Deniz Acar',
    ],
    salesReps: ['Emin Bilgin', 'Selin Kara', 'Onur Kılıç', 'Merve Aksoy'],
    projects: ['Deniz', 'Marina', 'Ocean View', 'Park Avenue', 'Skyline', 'Garden'],
    activities: [
      {
        id: 'act-1',
        type: 'phone',
        titleKey: 'phone',
        descriptionKey: 'phoneDesc1',
        customer: 'Ahmet Yılmaz',
        customerDetail: 'Ocean View Residences',
        project: 'Deniz',
        projectTone: 'navy',
        salesRep: 'Emin Bilgin',
        salesRepInitials: 'EB',
        dateTime: '24.06.2025 14:30',
        status: 'completed',
        priority: 'high',
        aiSummaryKey: 'summary1',
      },
      {
        id: 'act-2',
        type: 'whatsapp',
        titleKey: 'whatsapp',
        descriptionKey: 'whatsappDesc1',
        customer: 'Ayşe Demir',
        customerDetail: 'Marina Heights',
        project: 'Marina',
        projectTone: 'cyan',
        salesRep: 'Selin Kara',
        salesRepInitials: 'SK',
        dateTime: '24.06.2025 13:15',
        status: 'pending',
        priority: 'medium',
        aiSummaryKey: 'summary2',
      },
      {
        id: 'act-3',
        type: 'email',
        titleKey: 'email',
        descriptionKey: 'emailDesc1',
        customer: 'Mehmet Kaya',
        customerDetail: 'Park Avenue',
        project: 'Park Avenue',
        projectTone: 'green',
        salesRep: 'Onur Kılıç',
        salesRepInitials: 'OK',
        dateTime: '24.06.2025 11:45',
        status: 'completed',
        priority: 'low',
        aiSummaryKey: 'summary3',
      },
      {
        id: 'act-4',
        type: 'meeting',
        titleKey: 'meeting',
        descriptionKey: 'meetingDesc1',
        customer: 'Zeynep Arslan',
        customerDetail: 'Skyline Lofts',
        project: 'Skyline',
        projectTone: 'amber',
        salesRep: 'Emin Bilgin',
        salesRepInitials: 'EB',
        dateTime: '24.06.2025 10:00',
        status: 'inProgress',
        priority: 'critical',
        aiSummaryKey: 'summary4',
      },
      {
        id: 'act-5',
        type: 'note',
        titleKey: 'note',
        descriptionKey: 'noteDesc1',
        customer: 'Elif Yıldız',
        customerDetail: 'Garden Court',
        project: 'Garden',
        projectTone: 'green',
        salesRep: 'Merve Aksoy',
        salesRepInitials: 'MA',
        dateTime: '23.06.2025 17:20',
        status: 'completed',
        priority: 'medium',
        aiSummaryKey: 'summary5',
      },
      {
        id: 'act-6',
        type: 'documentShared',
        titleKey: 'documentShared',
        descriptionKey: 'documentDesc1',
        customer: 'Can Özkan',
        customerDetail: 'Ocean View Residences',
        project: 'Ocean View',
        projectTone: 'cyan',
        salesRep: 'Selin Kara',
        salesRepInitials: 'SK',
        dateTime: '23.06.2025 16:05',
        status: 'completed',
        priority: 'high',
        aiSummaryKey: 'summary6',
      },
      {
        id: 'act-7',
        type: 'missedCall',
        titleKey: 'missedCall',
        descriptionKey: 'missedCallDesc1',
        customer: 'Burak Şahin',
        customerDetail: 'Marina Heights',
        project: 'Marina',
        projectTone: 'navy',
        salesRep: 'Onur Kılıç',
        salesRepInitials: 'OK',
        dateTime: '23.06.2025 15:40',
        status: 'pending',
        priority: 'critical',
        aiSummaryKey: 'summary7',
      },
      {
        id: 'act-8',
        type: 'sms',
        titleKey: 'sms',
        descriptionKey: 'smsDesc1',
        customer: 'Deniz Acar',
        customerDetail: 'Park Avenue',
        project: 'Park Avenue',
        projectTone: 'slate',
        salesRep: 'Merve Aksoy',
        salesRepInitials: 'MA',
        dateTime: '23.06.2025 14:10',
        status: 'cancelled',
        priority: 'low',
        aiSummaryKey: 'summary8',
      },
      {
        id: 'act-9',
        type: 'videoCall',
        titleKey: 'videoCall',
        descriptionKey: 'videoDesc1',
        customer: 'Ahmet Yılmaz',
        customerDetail: 'Skyline Lofts',
        project: 'Skyline',
        projectTone: 'amber',
        salesRep: 'Emin Bilgin',
        salesRepInitials: 'EB',
        dateTime: '23.06.2025 12:30',
        status: 'completed',
        priority: 'high',
        aiSummaryKey: 'summary9',
      },
      {
        id: 'act-10',
        type: 'phone',
        titleKey: 'phone',
        descriptionKey: 'phoneDesc2',
        customer: 'Elif Yıldız',
        customerDetail: 'Garden Court',
        project: 'Garden',
        projectTone: 'green',
        salesRep: 'Selin Kara',
        salesRepInitials: 'SK',
        dateTime: '22.06.2025 18:00',
        status: 'pending',
        priority: 'medium',
        aiSummaryKey: 'summary10',
      },
      {
        id: 'act-11',
        type: 'meeting',
        titleKey: 'meeting',
        descriptionKey: 'meetingDesc2',
        customer: 'Ayşe Demir',
        customerDetail: 'Marina Heights',
        project: 'Marina',
        projectTone: 'cyan',
        salesRep: 'Emin Bilgin',
        salesRepInitials: 'EB',
        dateTime: '22.06.2025 11:00',
        status: 'completed',
        priority: 'high',
        aiSummaryKey: 'summary11',
      },
      {
        id: 'act-12',
        type: 'email',
        titleKey: 'email',
        descriptionKey: 'emailDesc2',
        customer: 'Zeynep Arslan',
        customerDetail: 'Ocean View Residences',
        project: 'Ocean View',
        projectTone: 'navy',
        salesRep: 'Onur Kılıç',
        salesRepInitials: 'OK',
        dateTime: '21.06.2025 09:25',
        status: 'inProgress',
        priority: 'medium',
        aiSummaryKey: 'summary12',
      },
    ],
    overdueFollowUps: [
      { id: 'of-1', customer: 'Elif Yıldız', daysOverdue: 5 },
      { id: 'of-2', customer: 'Burak Şahin', daysOverdue: 3 },
      { id: 'of-3', customer: 'Can Özkan', daysOverdue: 2 },
    ],
    upcomingMeetings: [
      {
        id: 'um-1',
        title: 'Proje sunumu',
        customer: 'Zeynep Arslan',
        time: 'Bugün 15:30',
      },
      {
        id: 'um-2',
        title: 'Ödeme planı görüşmesi',
        customer: 'Ahmet Yılmaz',
        time: 'Yarın 10:00',
      },
      {
        id: 'um-3',
        title: 'Saha gezisi',
        customer: 'Ayşe Demir',
        time: '26.06 14:00',
      },
    ],
    aiRecommendations: [
      { id: 'ai-1', bodyKey: 'recFollowElif' },
      { id: 'ai-2', bodyKey: 'recCallBurak' },
      { id: 'ai-3', bodyKey: 'recSendDocs' },
    ],
    recentNotes: [
      {
        id: 'note-1',
        author: 'Emin Bilgin',
        bodyKey: 'noteAhmet',
        timeKey: 'hoursAgo2',
      },
      {
        id: 'note-2',
        author: 'Selin Kara',
        bodyKey: 'noteAyse',
        timeKey: 'hoursAgo5',
      },
      {
        id: 'note-3',
        author: 'Onur Kılıç',
        bodyKey: 'noteMehmet',
        timeKey: 'yesterday',
      },
    ],
  };
}
