import type { FilesWorkspacePreview } from './files-model';

/** Typed local fixtures for Files module — no live files API. */
export function makeFilesPreview(): FilesWorkspacePreview {
  const files = [
    {
      id: 'file-sales-contract',
      name: 'Satış Sözleşmesi.pdf',
      fileType: 'pdf' as const,
      category: 'contracts' as const,
      size: '2.4 MB',
      version: 'v2.1',
      updatedAt: '24.07.2026',
      relatedKind: 'customer' as const,
      relatedName: 'Ahmet Yılmaz',
      owner: 'Ayşe Demir',
      recent: true,
    },
    {
      id: 'file-id-scan',
      name: 'Kimlik Tarama.pdf',
      fileType: 'pdf' as const,
      category: 'identity' as const,
      size: '1.1 MB',
      version: 'v1.0',
      updatedAt: '23.07.2026',
      relatedKind: 'customer' as const,
      relatedName: 'Elif Kaya',
      owner: 'Mehmet Kaya',
      recent: true,
    },
    {
      id: 'file-payment-plan',
      name: 'Ödeme Planı.xlsx',
      fileType: 'xlsx' as const,
      category: 'financial' as const,
      size: '856 KB',
      version: 'v3.0',
      updatedAt: '22.07.2026',
      relatedKind: 'project' as const,
      relatedName: 'Marina Heights',
      owner: 'Can Özkan',
      recent: true,
    },
    {
      id: 'file-investor-deck',
      name: 'Yatırımcı Sunumu.docx',
      fileType: 'docx' as const,
      category: 'marketing' as const,
      size: '4.2 MB',
      version: 'v1.4',
      updatedAt: '21.07.2026',
      relatedKind: 'investor' as const,
      relatedName: 'Nova Capital',
      owner: 'Zeynep Arslan',
      recent: false,
    },
    {
      id: 'file-title-deed',
      name: 'Tapu Belgesi.pdf',
      fileType: 'pdf' as const,
      category: 'legal' as const,
      size: '3.2 MB',
      version: 'v1.0',
      updatedAt: '18.07.2026',
      relatedKind: 'project' as const,
      relatedName: 'Ocean View',
      owner: 'Elif Yıldız',
      recent: false,
    },
    {
      id: 'file-unit-photo',
      name: 'Birim Fotoğrafı.jpg',
      fileType: 'jpg' as const,
      category: 'marketing' as const,
      size: '2.8 MB',
      version: 'v1.0',
      updatedAt: '16.07.2026',
      relatedKind: 'project' as const,
      relatedName: 'Park Avenue',
      owner: 'Ahmet Yılmaz',
      recent: false,
    },
    {
      id: 'file-nda-pack',
      name: 'NDA Paketi.zip',
      fileType: 'zip' as const,
      category: 'legal' as const,
      size: '12.4 MB',
      version: 'v2.0',
      updatedAt: '12.07.2026',
      relatedKind: 'investor' as const,
      relatedName: 'Horizon Partners',
      owner: 'Ayşe Demir',
      recent: false,
    },
    {
      id: 'file-site-plan',
      name: 'Vaziyet Planı.png',
      fileType: 'png' as const,
      category: 'other' as const,
      size: '6.1 MB',
      version: 'v1.2',
      updatedAt: '10.07.2026',
      relatedKind: 'project' as const,
      relatedName: 'Skyline Lofts',
      owner: 'Can Özkan',
      recent: false,
    },
  ];

  return {
    files,
    categories: [
      { id: 'all', count: files.length },
      { id: 'contracts', count: files.filter((f) => f.category === 'contracts').length },
      { id: 'identity', count: files.filter((f) => f.category === 'identity').length },
      { id: 'financial', count: files.filter((f) => f.category === 'financial').length },
      { id: 'marketing', count: files.filter((f) => f.category === 'marketing').length },
      { id: 'legal', count: files.filter((f) => f.category === 'legal').length },
      { id: 'other', count: files.filter((f) => f.category === 'other').length },
    ],
    recentIds: files.filter((f) => f.recent).map((f) => f.id),
  };
}
