"""ProjectPhotoCreativeProfileV1 — art direction starts from what the photograph can do."""

from __future__ import annotations

from typing import Any

SCHEMA = "ProjectPhotoCreativeProfileV1"

TEMPLE_PHOTO_PROFILES: tuple[dict[str, Any], ...] = (
    {
        "filename": "IH_DC_TMP_001_Render_Exterior_Day_001.jpg",
        "asset_id": "5d26caf3-c237-4a78-9f3a-91f05dd24fa2",
        "subject_geometry": "full street monument, centered historic mass with adjacent modern fabric",
        "architectural_anchor": "complete Temple volume including base and spire",
        "negative_space": "sky around the crown; street foreground",
        "perspective": "eye-level street",
        "horizon": "low-mid, street holds the base",
        "dominant_lines": "vertical spire, horizontal cornice, street plane",
        "depth_opportunities": "street → lawn → façade → sky",
        "text_safe_regions": ["upper sky left or right of spire", "lower street if darkened"],
        "mask_opportunities": ["sky field as type veil", "building silhouette as object"],
        "boundary_interaction_opportunities": ["spire can interrupt a top edge or color field"],
        "foreground_opportunities": "street and pedestrians as scale",
        "crop_flexibility": "medium — losing the base weakens monumentality",
        "visual_energy": "civic daylight, readable identity",
        "campaign_suitability": "identity hero, object-on-page, street-life prestige",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Exterior_Day_002.jpg",
        "asset_id": "543aeb03-c4c9-46f9-9d9f-81bf53f45438",
        "subject_geometry": "mid-distance spire against large sky, three arched mid-windows",
        "architectural_anchor": "spire shaft and lantern",
        "negative_space": "generous bright sky with clouds",
        "perspective": "slightly low, looking up the tower",
        "horizon": "low, architecture dominates vertical",
        "dominant_lines": "strong vertical spire",
        "depth_opportunities": "trees and lamp at base as scale",
        "text_safe_regions": ["left or right sky", "not across the spire"],
        "mask_opportunities": ["sky as field", "spire as cutting silhouette"],
        "boundary_interaction_opportunities": ["spire can pierce a chamber opening or top bleed"],
        "foreground_opportunities": "limited — mostly sky and shaft",
        "crop_flexibility": "high on sky; protect the lantern",
        "visual_energy": "iconic, airy, emblematic",
        "campaign_suitability": "spire-as-idea, chamber reveal, graphic crop",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Exterior_Day_003.jpg",
        "asset_id": "7346e259-f999-4fbb-a8d5-63708d4e0c81",
        "subject_geometry": "architecture with a large quiet upper sky — historically used for type field",
        "architectural_anchor": "Temple mass under open sky",
        "negative_space": "wide pale sky, strongest type-safe photographic quiet in the set",
        "perspective": "slightly distant elevational",
        "horizon": "lower third",
        "dominant_lines": "horizontal sky/building split, vertical tower",
        "depth_opportunities": "sky as emptiness, building as base mass",
        "text_safe_regions": ["upper-left sky is the primary type territory"],
        "mask_opportunities": ["soft sky bleach for type", "building as lower foundation"],
        "boundary_interaction_opportunities": ["sky/building collision as page split without a rectangle"],
        "foreground_opportunities": "low",
        "crop_flexibility": "high in sky; keep the crown",
        "visual_energy": "calm daylight authority",
        "campaign_suitability": "type-in-real-sky, prestige still, NOT a quality ceiling",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Exterior_Day_004.jpg",
        "asset_id": "299bd265-a0ea-486d-866d-1947f103fd57",
        "subject_geometry": "elevated / aerial mass of the block",
        "architectural_anchor": "rooftop plan and urban context",
        "negative_space": "surrounding streets and sky",
        "perspective": "oblique aerial",
        "horizon": "high or absent",
        "dominant_lines": "block geometry, street grid",
        "depth_opportunities": "city fabric around the project",
        "text_safe_regions": ["sky corners if present", "soft edges of context"],
        "mask_opportunities": ["isolate the block as an object"],
        "boundary_interaction_opportunities": ["map-like object on a graphic field"],
        "foreground_opportunities": "none at human scale",
        "crop_flexibility": "low for intimacy; high for diagram",
        "visual_energy": "strategic, cartographic, less emotional",
        "campaign_suitability": "context/adjacency, not a looking-chamber or terrace narrative",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Exterior_Day_005.jpg",
        "asset_id": "07863b0f-22e8-43c6-a629-7ceca7651b16",
        "subject_geometry": "aerial neighborhood mass",
        "architectural_anchor": "roofscape",
        "negative_space": "open urban surround",
        "perspective": "aerial",
        "horizon": "high",
        "dominant_lines": "block and streets",
        "depth_opportunities": "city as texture",
        "text_safe_regions": ["peripheral sky/ground"],
        "mask_opportunities": ["object isolation"],
        "boundary_interaction_opportunities": ["graphic map field"],
        "foreground_opportunities": "none",
        "crop_flexibility": "low for campaign intimacy",
        "visual_energy": "overview",
        "campaign_suitability": "location proof only",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Exterior_Day_007.jpg",
        "asset_id": "c0afa1bf-b487-410c-be3d-91c31852550d",
        "subject_geometry": "aerial architectural mass with readable historic roof and spire from above",
        "architectural_anchor": "historic roof + spire from altitude",
        "negative_space": "surrounding fabric and sky",
        "perspective": "high oblique",
        "horizon": "high",
        "dominant_lines": "roof ridges, spire needle",
        "depth_opportunities": "city as context ring",
        "text_safe_regions": ["sky beyond the roof"],
        "mask_opportunities": ["protect spire needle as silhouette"],
        "boundary_interaction_opportunities": ["needle piercing a field"],
        "foreground_opportunities": "none",
        "crop_flexibility": "protect the needle; crop context freely",
        "visual_energy": "commanding, less intimate",
        "campaign_suitability": "authority/overview; weak for residential intimacy",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Exterior_Day_008.jpg",
        "asset_id": "2d44757b-079c-4a78-a4a9-5fe6370466c8",
        "subject_geometry": "low-angle plaza looking up at the historic mass",
        "architectural_anchor": "base, arches, upward thrust",
        "negative_space": "sky above the crown",
        "perspective": "worm's-eye plaza",
        "horizon": "very low",
        "dominant_lines": "converging verticals",
        "depth_opportunities": "plaza pavement as foreground stage",
        "text_safe_regions": ["sky beside the rise", "darkened pavement"],
        "mask_opportunities": ["upward crop as monument"],
        "boundary_interaction_opportunities": ["building bursting the top edge"],
        "foreground_opportunities": "plaza, people, pavement texture",
        "crop_flexibility": "protect the upward gesture; do not flatten to elevation",
        "visual_energy": "monumental, physical, civic",
        "campaign_suitability": "authority launch, arrival, plaza life",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Exterior_Day_009.jpg",
        "asset_id": "7696df34-0544-44b9-89f5-0d1b2523c412",
        "subject_geometry": "street-level monumental spire with full historic base and side modern neighbor",
        "architectural_anchor": "street-level arches + soaring spire",
        "negative_space": "blue sky; street as stage",
        "perspective": "eye-level, slight upward",
        "horizon": "low street",
        "dominant_lines": "vertical spire, three tall arches, street horizontal",
        "depth_opportunities": "street, lawn, façade, sky — strongest street monument in the set",
        "text_safe_regions": ["sky left of spire if modern neighbor is cropped", "street band"],
        "mask_opportunities": ["spire as reveal", "building as object on a field"],
        "boundary_interaction_opportunities": ["spire interrupting chamber, field, or top bleed"],
        "foreground_opportunities": "street, pedestrians, lawn, fence",
        "crop_flexibility": "high horizontally; keep arches + lantern together",
        "visual_energy": "monumental identity, human scale at the base",
        "campaign_suitability": "flagship identity, chamber reveal, street prestige",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Exterior_Day_010.jpg",
        "asset_id": "f491ee6e-de7d-4258-a153-4104e326b736",
        "subject_geometry": "aerial / high mass",
        "architectural_anchor": "roof and urban block",
        "negative_space": "city surround",
        "perspective": "aerial",
        "horizon": "high",
        "dominant_lines": "block plan",
        "depth_opportunities": "context only",
        "text_safe_regions": ["peripheral sky"],
        "mask_opportunities": ["object isolation"],
        "boundary_interaction_opportunities": ["diagram field"],
        "foreground_opportunities": "none",
        "crop_flexibility": "low for intimacy",
        "visual_energy": "map-like",
        "campaign_suitability": "context only",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Exterior_Sunset_001.jpg",
        "asset_id": "65f68756-a006-43d4-9c86-2c0ec25ad229",
        "subject_geometry": "dusk façade and sky melt — warm sky is both atmosphere and potential graphic field",
        "architectural_anchor": "silhouetted Temple against sunset",
        "negative_space": "large warm sky",
        "perspective": "street-to-sky dusk",
        "horizon": "low-mid",
        "dominant_lines": "horizon glow, vertical dark mass",
        "depth_opportunities": "dark building against luminous sky",
        "text_safe_regions": ["sky if contrast is designed; never thin type on mixed cloud"],
        "mask_opportunities": ["sky as color field merging with architecture"],
        "boundary_interaction_opportunities": ["photo and graphic field can share the same dusk"],
        "foreground_opportunities": "ground gloom, possible human scale",
        "crop_flexibility": "sky is flexible; protect the dark silhouette",
        "visual_energy": "warm, cinematic, atmospheric",
        "campaign_suitability": "dusk merge, emotional launch, NOT a quality ceiling",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Living_Room_001.jpg",
        "asset_id": "c3d11c35-d8b7-485c-b216-0a4da68b751a",
        "subject_geometry": "furnished living chamber with large windows looking to the city",
        "architectural_anchor": "window wall as aperture; sofa as inhabited foreground",
        "negative_space": "upper wall/curtain; some ceiling",
        "perspective": "interior looking out",
        "horizon": "exterior city through glass",
        "dominant_lines": "window mullions, sofa curve, floor plane",
        "depth_opportunities": "room → glass → city — strongest looking-out interior",
        "text_safe_regions": ["upper wall/curtain if contrast allows — historically type lived here"],
        "mask_opportunities": ["windows as reveal to a second photograph", "room as chamber"],
        "boundary_interaction_opportunities": ["interior opening into exterior architecture"],
        "foreground_opportunities": "sofa, ottoman, plant, coffee table — lived scale",
        "crop_flexibility": "protect sofa + windows together; do not crop out the looking-out",
        "visual_energy": "warm residential intimacy with urban proof beyond the glass",
        "campaign_suitability": "chamber concept, interior-led prestige, looking-out narrative",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Living_Room_002.jpeg",
        "asset_id": "bcf7b360-7078-44b6-a5f3-0e52372cdca9",
        "subject_geometry": "alternate living interior",
        "architectural_anchor": "room volume",
        "negative_space": "walls and ceiling depending on crop",
        "perspective": "interior",
        "horizon": "interior",
        "dominant_lines": "furniture and openings",
        "depth_opportunities": "room depth; confirm window if present",
        "text_safe_regions": ["quiet walls"],
        "mask_opportunities": ["interior as environment"],
        "boundary_interaction_opportunities": ["weaker than Living_Room_001 unless a window dominates"],
        "foreground_opportunities": "furniture",
        "crop_flexibility": "medium",
        "visual_energy": "residential",
        "campaign_suitability": "supporting interior, not default hero",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Living_Room_005.jpg",
        "asset_id": "8837fa06-d71b-4d26-a5cb-9cb682748311",
        "subject_geometry": "living interior variant",
        "architectural_anchor": "interior architecture",
        "negative_space": "walls",
        "perspective": "interior",
        "horizon": "interior",
        "dominant_lines": "openings and furniture",
        "depth_opportunities": "room",
        "text_safe_regions": ["quiet walls"],
        "mask_opportunities": ["environment"],
        "boundary_interaction_opportunities": "limited",
        "foreground_opportunities": "furniture",
        "crop_flexibility": "medium",
        "visual_energy": "residential",
        "campaign_suitability": "supporting",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Living_Room_006.jpg",
        "asset_id": "a27e3c70-995f-48fc-965c-49fde9917b3f",
        "subject_geometry": "living interior variant",
        "architectural_anchor": "interior architecture",
        "negative_space": "walls",
        "perspective": "interior",
        "horizon": "interior",
        "dominant_lines": "furniture",
        "depth_opportunities": "room",
        "text_safe_regions": ["quiet walls"],
        "mask_opportunities": ["environment"],
        "boundary_interaction_opportunities": "limited",
        "foreground_opportunities": "furniture",
        "crop_flexibility": "medium",
        "visual_energy": "residential",
        "campaign_suitability": "supporting",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Bedroom_007.jpg",
        "asset_id": "2635b01e-6580-4511-82fe-a16fba510b41",
        "subject_geometry": "bedroom interior",
        "architectural_anchor": "sleeping volume",
        "negative_space": "walls, bedding quiet",
        "perspective": "interior",
        "horizon": "interior",
        "dominant_lines": "bed plane, windows if present",
        "depth_opportunities": "intimate room",
        "text_safe_regions": ["quiet walls only"],
        "mask_opportunities": ["privacy interior as texture/environment"],
        "boundary_interaction_opportunities": "weak for civic campaign",
        "foreground_opportunities": "bed, textiles",
        "crop_flexibility": "medium",
        "visual_energy": "private, quiet",
        "campaign_suitability": "unit-type story, not flagship identity",
    },
    {
        "filename": "IH_DC_TMP_001_Render_Bathroom_008.jpeg",
        "asset_id": "518a295f-f76f-40d8-b4b3-9a11cfbc7791",
        "subject_geometry": "bathroom interior",
        "architectural_anchor": "material/finish",
        "negative_space": "tiles, mirrors",
        "perspective": "tight interior",
        "horizon": "interior",
        "dominant_lines": "fixtures",
        "depth_opportunities": "low",
        "text_safe_regions": ["almost none — materials dominate"],
        "mask_opportunities": ["material texture only"],
        "boundary_interaction_opportunities": "none for civic idea",
        "foreground_opportunities": "fixtures",
        "crop_flexibility": "low",
        "visual_energy": "detail, not campaign",
        "campaign_suitability": "spec sheet / amenity only",
    },
)


def project_photo_profile(asset_id: str | None = None, filename: str | None = None) -> dict[str, Any] | None:
    for item in TEMPLE_PHOTO_PROFILES:
        if asset_id and item["asset_id"] == asset_id:
            return {"schema": SCHEMA, **item}
        if filename and item["filename"] == filename:
            return {"schema": SCHEMA, **item}
    return None


def project_photo_profile_library() -> dict[str, Any]:
    records = [{"schema": SCHEMA, **item} for item in TEMPLE_PHOTO_PROFILES]
    return {
        "schema": "ProjectPhotoCreativeProfileLibraryV1",
        "project": "The Temple",
        "count": len(records),
        "records": records,
        "status": "READY" if records else "FAIL",
        "note": "Art direction must start from these opportunities. Do not force a reference crop onto an unfit photo.",
    }
