import type { TaskWorkspacePreview } from './tasks-model';

/** Typed local fixtures for Tasks UX review — no live API calls. */
export function makeTasksPreview(): TaskWorkspacePreview {
  return {
    totalTasks: 247,
    kpis: [
      {
        key: 'open',
        value: 42,
        hintKey: 'openHint',
        delta: '+12%',
        deltaTone: 'up',
      },
      {
        key: 'dueToday',
        value: 8,
        hintKey: 'dueTodayHint',
        delta: '',
        deltaTone: 'neutral',
      },
      {
        key: 'overdue',
        value: 5,
        hintKey: 'overdueHint',
        delta: '-2',
        deltaTone: 'down',
      },
      {
        key: 'completed',
        value: 126,
        hintKey: 'completedHint',
        delta: '+18%',
        deltaTone: 'up',
      },
    ],
    daySummary: {
      open: 42,
      dueToday: 8,
      overdue: 5,
      assessmentKey: 'dayAssessment',
    },
    customers: [
      'Ahmet Yılmaz',
      'Ayşe Demir',
      'Mehmet Kaya',
      'Zeynep Arslan',
      'Elif Yıldız',
      'Can Özkan',
    ],
    assignees: ['Emin Bilgin', 'Selin Kara', 'Onur Kılıç', 'Merve Aksoy'],
    projects: [
      'The Temple',
      'Marina Heights',
      'Ocean View',
      'Park Avenue',
      'Skyline Lofts',
      'Garden Court',
    ],
    tags: ['contract', 'analysis', 'payment', 'closing', 'followUp'],
    todayPriorities: [
      { id: 'pri-1', titleKey: 'sendLandContract', dueLabelKey: 'today1600' },
      { id: 'pri-2', titleKey: 'checkRoiAnalysis', dueLabelKey: 'today1730' },
    ],
    upcomingDeadlines: [
      { id: 'dl-1', titleKey: 'sharePaymentPlan', dueLabelKey: 'tomorrow1100' },
      { id: 'dl-2', titleKey: 'prepareClosingDocs', dueLabelKey: 'mon1400' },
      { id: 'dl-3', titleKey: 'customerFollowUpCall', dueLabelKey: 'tue1030' },
    ],
    aiRecommendations: [
      { id: 'rec-1', bodyKey: 'recAhmetFirst' },
      { id: 'rec-2', bodyKey: 'recRoiBeforeCall' },
      { id: 'rec-3', bodyKey: 'recOverdueBatch' },
    ],
    teamPerformance: [
      { id: 'tp-1', name: 'Emin Bilgin', completed: 12, total: 15 },
      { id: 'tp-2', name: 'Selin Kara', completed: 9, total: 11 },
      { id: 'tp-3', name: 'Onur Kılıç', completed: 7, total: 10 },
      { id: 'tp-4', name: 'Merve Aksoy', completed: 11, total: 12 },
    ],
    tasks: [
      {
        id: 'task-1',
        titleKey: 'sendLandContract',
        descriptionKey: 'sendLandContractDesc',
        customer: 'Ahmet Yılmaz',
        project: 'The Temple',
        dueLabelKey: 'today1600',
        dueTone: 'today',
        priority: 'high',
        status: 'open',
        kanbanColumn: 'todo',
        assignee: 'Emin Bilgin',
        assigneeInitials: 'EB',
        tag: 'contract',
        aiNoteKey: 'note1',
      },
      {
        id: 'task-2',
        titleKey: 'checkRoiAnalysis',
        descriptionKey: 'checkRoiAnalysisDesc',
        customer: 'Ayşe Demir',
        project: 'Marina Heights',
        dueLabelKey: 'today1730',
        dueTone: 'today',
        priority: 'critical',
        status: 'inProgress',
        kanbanColumn: 'inProgress',
        assignee: 'Selin Kara',
        assigneeInitials: 'SK',
        tag: 'analysis',
        aiNoteKey: 'note2',
      },
      {
        id: 'task-3',
        titleKey: 'sharePaymentPlan',
        descriptionKey: 'sharePaymentPlanDesc',
        customer: 'Mehmet Kaya',
        project: 'Ocean View',
        dueLabelKey: 'tomorrow1100',
        dueTone: 'soon',
        priority: 'medium',
        status: 'open',
        kanbanColumn: 'todo',
        assignee: 'Onur Kılıç',
        assigneeInitials: 'OK',
        tag: 'payment',
        aiNoteKey: 'note3',
      },
      {
        id: 'task-4',
        titleKey: 'prepareClosingDocs',
        descriptionKey: 'prepareClosingDocsDesc',
        customer: 'Zeynep Arslan',
        project: 'Park Avenue',
        dueLabelKey: 'mon1400',
        dueTone: 'soon',
        priority: 'high',
        status: 'waiting',
        kanbanColumn: 'review',
        assignee: 'Emin Bilgin',
        assigneeInitials: 'EB',
        tag: 'closing',
        aiNoteKey: 'note4',
      },
      {
        id: 'task-5',
        titleKey: 'customerFollowUpCall',
        descriptionKey: 'customerFollowUpCallDesc',
        customer: 'Elif Yıldız',
        project: 'Skyline Lofts',
        dueLabelKey: 'overdue2d',
        dueTone: 'overdue',
        priority: 'critical',
        status: 'open',
        kanbanColumn: 'todo',
        assignee: 'Merve Aksoy',
        assigneeInitials: 'MA',
        tag: 'followUp',
        aiNoteKey: 'note5',
      },
      {
        id: 'task-6',
        titleKey: 'sendBrochurePack',
        descriptionKey: 'sendBrochurePackDesc',
        customer: 'Can Özkan',
        project: 'Garden Court',
        dueLabelKey: 'wed0900',
        dueTone: 'neutral',
        priority: 'low',
        status: 'open',
        kanbanColumn: 'todo',
        assignee: 'Selin Kara',
        assigneeInitials: 'SK',
        tag: 'followUp',
        aiNoteKey: 'note6',
      },
      {
        id: 'task-7',
        titleKey: 'scheduleSiteVisit',
        descriptionKey: 'scheduleSiteVisitDesc',
        customer: 'Ahmet Yılmaz',
        project: 'The Temple',
        dueLabelKey: 'today1500',
        dueTone: 'today',
        priority: 'medium',
        status: 'inProgress',
        kanbanColumn: 'inProgress',
        assignee: 'Onur Kılıç',
        assigneeInitials: 'OK',
        tag: 'followUp',
        aiNoteKey: 'note7',
      },
      {
        id: 'task-8',
        titleKey: 'reviewReservationForm',
        descriptionKey: 'reviewReservationFormDesc',
        customer: 'Ayşe Demir',
        project: 'Marina Heights',
        dueLabelKey: 'done',
        dueTone: 'done',
        priority: 'medium',
        status: 'completed',
        kanbanColumn: 'completed',
        assignee: 'Emin Bilgin',
        assigneeInitials: 'EB',
        tag: 'contract',
        aiNoteKey: 'note8',
        checked: true,
      },
      {
        id: 'task-9',
        titleKey: 'collectBankDocs',
        descriptionKey: 'collectBankDocsDesc',
        customer: 'Mehmet Kaya',
        project: 'Ocean View',
        dueLabelKey: 'overdue1d',
        dueTone: 'overdue',
        priority: 'high',
        status: 'waiting',
        kanbanColumn: 'review',
        assignee: 'Merve Aksoy',
        assigneeInitials: 'MA',
        tag: 'closing',
        aiNoteKey: 'note9',
      },
      {
        id: 'task-10',
        titleKey: 'confirmUnitHold',
        descriptionKey: 'confirmUnitHoldDesc',
        customer: 'Zeynep Arslan',
        project: 'Park Avenue',
        dueLabelKey: 'thu1600',
        dueTone: 'neutral',
        priority: 'low',
        status: 'cancelled',
        kanbanColumn: 'todo',
        assignee: 'Selin Kara',
        assigneeInitials: 'SK',
        tag: 'followUp',
        aiNoteKey: 'note10',
      },
    ],
  };
}
