/**
 * INVESTHOME OS — Design Asset Registry (D1B.5)
 * Machine-readable Figma↔code inventory for admin showcase + tooling.
 * Do not expose internal paths in non-admin production UI.
 */

export type DesignAssetCategory =
  | 'foundation'
  | 'primitive'
  | 'navigation'
  | 'overlay'
  | 'data-display'
  | 'chart'
  | 'domain';

export type DesignAssetStatus =
  | 'canonical'
  | 'experimental'
  | 'legacy'
  | 'duplicate'
  | 'deprecated-candidate'
  | 'domain-specific';

export type DesignAssetOwner = 'packages/ui' | 'apps/web/design-system' | 'apps/web/shell' | 'domain';

export interface DesignAssetEntry {
  id: string;
  category: DesignAssetCategory;
  codeName: string;
  importPath: string;
  figmaName: string;
  variants: string[];
  states: string[];
  sizes: string[];
  status: DesignAssetStatus;
  owner: DesignAssetOwner;
  documentationPath: string;
}

export const DESIGN_ASSET_REGISTRY: readonly DesignAssetEntry[] = [
  {
    id: 'foundation-color-surface',
    category: 'foundation',
    codeName: 'designTokens.color / theme-tokens',
    importPath: '@investhome/ui',
    figmaName: 'Foundation / Color / Surface / Default',
    variants: ['canvas', 'subtle', 'elevated', 'default'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/figma-variables-spec.md',
  },
  {
    id: 'foundation-icon-ih',
    category: 'foundation',
    codeName: 'IhIcon',
    importPath: '@/components/icons/ih-icons',
    figmaName: 'Foundation / Icon / Stroke / Default',
    variants: [],
    states: [],
    sizes: ['12', '14', '16', '18', '20', '24', '32', 'sm', 'md', 'lg', 'nav'],
    status: 'canonical',
    owner: 'apps/web/shell',
    documentationPath: 'docs/design-system/icon-system.md',
  },
  {
    id: 'primitive-button',
    category: 'primitive',
    codeName: 'Button',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Button / Primary / Medium',
    variants: ['primary', 'secondary', 'tertiary', 'ghost', 'danger', 'link'],
    states: ['default', 'disabled', 'loading', 'success'],
    sizes: ['sm', 'md', 'lg'],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-variant-contract.md',
  },
  {
    id: 'primitive-icon-button',
    category: 'primitive',
    codeName: 'IconButton',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Icon Button / Ghost / Medium',
    variants: ['default', 'ghost'],
    states: ['default', 'disabled'],
    sizes: ['md'],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'primitive-badge',
    category: 'primitive',
    codeName: 'Badge',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Badge / Success / Default',
    variants: ['default', 'success', 'warning', 'danger', 'info'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'primitive-status-badge',
    category: 'primitive',
    codeName: 'StatusBadge',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Status Badge / Info / Default',
    variants: ['success', 'warning', 'danger', 'info', 'ai', 'neutral'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-variant-contract.md',
  },
  {
    id: 'primitive-status-chip',
    category: 'primitive',
    codeName: 'StatusChip',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Status Chip / Default / Default',
    variants: ['default', 'success', 'warning', 'danger', 'info'],
    states: [],
    sizes: [],
    status: 'deprecated-candidate',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/duplicate-component-matrix.md',
  },
  {
    id: 'primitive-alert',
    category: 'primitive',
    codeName: 'Alert',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Alert / Warning / Default',
    variants: ['info', 'success', 'warning', 'error'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'primitive-surface',
    category: 'primitive',
    codeName: 'Surface',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Surface / Elevated / Default',
    variants: ['default', 'subtle', 'elevated', 'flush'],
    states: [],
    sizes: [],
    status: 'experimental',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'primitive-card',
    category: 'primitive',
    codeName: 'Card',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Card / Default / Default',
    variants: ['legacy-title', 'compound'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-variant-contract.md',
  },
  {
    id: 'primitive-unit-card',
    category: 'primitive',
    codeName: 'UnitCard',
    importPath: '@investhome/ui',
    figmaName: 'UXR1 V2 / Unit Card / Portrait',
    variants: ['portrait'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/investhome-os-design-system-v2.md',
  },
  {
    id: 'primitive-pipeline-column',
    category: 'primitive',
    codeName: 'PipelineColumn',
    importPath: '@investhome/ui',
    figmaName: 'UXR1 V2 / Pipeline Column',
    variants: ['lead', 'qualify', 'proposal', 'negotiation', 'won', 'lost', 'neutral'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/investhome-os-design-system-v2.md',
  },
  {
    id: 'primitive-progress-pair',
    category: 'primitive',
    codeName: 'ProgressPair',
    importPath: '@investhome/ui',
    figmaName: 'UXR1 V2 / Progress Pair',
    variants: ['construction-sales'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/investhome-os-design-system-v2.md',
  },
  {
    id: 'primitive-input',
    category: 'primitive',
    codeName: 'Input',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Input / Default / Default',
    variants: [],
    states: ['default', 'disabled', 'error', 'success', 'hint'],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-variant-contract.md',
  },
  {
    id: 'primitive-textarea',
    category: 'primitive',
    codeName: 'TextArea',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Text Area / Default / Default',
    variants: [],
    states: ['default', 'disabled', 'error', 'success', 'hint'],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-variant-contract.md',
  },
  {
    id: 'primitive-select',
    category: 'primitive',
    codeName: 'Select',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Select / Default / Default',
    variants: [],
    states: ['default', 'disabled'],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-variant-contract.md',
  },
  {
    id: 'primitive-search-input',
    category: 'primitive',
    codeName: 'SearchInput',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Search Input / Default / Default',
    variants: [],
    states: ['default', 'loading', 'clearable'],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'primitive-tabs',
    category: 'primitive',
    codeName: 'Tabs',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Tabs / Default / Default',
    variants: [],
    states: ['active', 'disabled'],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'primitive-segmented-control',
    category: 'primitive',
    codeName: 'SegmentedControl',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Segmented Control / Default / Default',
    variants: [],
    states: ['selected'],
    sizes: [],
    status: 'experimental',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'primitive-filter-button',
    category: 'primitive',
    codeName: 'FilterButton',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Filter Button / Active / Default',
    variants: [],
    states: ['default', 'active'],
    sizes: [],
    status: 'experimental',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'primitive-date-range',
    category: 'primitive',
    codeName: 'DateRangeControl',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Date Range / Default / Default',
    variants: [],
    states: [],
    sizes: [],
    status: 'experimental',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'primitive-progress-bar',
    category: 'primitive',
    codeName: 'ProgressBar',
    importPath: '@investhome/ui',
    figmaName: 'Primitive / Progress Bar / Success / Default',
    variants: ['default', 'success', 'warning', 'danger', 'gold'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'navigation-page-header-ds',
    category: 'navigation',
    codeName: 'PageHeader',
    importPath: '@/components/design-system/layout',
    figmaName: 'Navigation / Page Header / Default / Default',
    variants: [],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'navigation-page-header-ui',
    category: 'navigation',
    codeName: 'PageHeader',
    importPath: '@investhome/ui',
    figmaName: 'Navigation / Page Header Legacy / Default / Default',
    variants: [],
    states: [],
    sizes: [],
    status: 'legacy',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/duplicate-component-matrix.md',
  },
  {
    id: 'navigation-section-header',
    category: 'navigation',
    codeName: 'SectionHeader',
    importPath: '@investhome/ui',
    figmaName: 'Navigation / Section Header / Default / Default',
    variants: [],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'navigation-app-page',
    category: 'navigation',
    codeName: 'AppPage',
    importPath: '@/components/design-system/layout',
    figmaName: 'Navigation / App Page / Default / Default',
    variants: [],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'overlay-dialog',
    category: 'overlay',
    codeName: 'Dialog',
    importPath: '@investhome/ui',
    figmaName: 'Overlay / Dialog / Default / Default',
    variants: [],
    states: ['open', 'closed'],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'overlay-drawer',
    category: 'overlay',
    codeName: 'Drawer',
    importPath: '@investhome/ui',
    figmaName: 'Overlay / Drawer / Wide / Default',
    variants: ['default', 'wide', 'sm', 'md', 'lg', 'full'],
    states: ['open', 'closed'],
    sizes: ['sm', 'md', 'lg', 'full'],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'overlay-widget-menu',
    category: 'overlay',
    codeName: 'WidgetMenu',
    importPath: '@investhome/ui',
    figmaName: 'Overlay / Widget Menu / Default / Default',
    variants: [],
    states: ['open', 'closed'],
    sizes: [],
    status: 'experimental',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'data-metric-card',
    category: 'data-display',
    codeName: 'MetricCard',
    importPath: '@investhome/ui',
    figmaName: 'Data Display / Metric Card / Large / Default',
    variants: [],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: ['large', 'medium'],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-variant-contract.md',
  },
  {
    id: 'data-kpi-card',
    category: 'data-display',
    codeName: 'KpiCard',
    importPath: '@investhome/ui',
    figmaName: 'Data Display / KPI Card Legacy / Default / Default',
    variants: ['default', 'gold', 'success', 'warning', 'danger', 'info'],
    states: ['ready', 'loading'],
    sizes: [],
    status: 'legacy',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/duplicate-component-matrix.md',
  },
  {
    id: 'data-widget-shell',
    category: 'data-display',
    codeName: 'WidgetShell',
    importPath: '@investhome/ui',
    figmaName: 'Data Display / Widget Shell / Span 6 / Ready',
    variants: ['span-3', 'span-4', 'span-6', 'span-8', 'span-12'],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-variant-contract.md',
  },
  {
    id: 'data-right-rail-card',
    category: 'data-display',
    codeName: 'RightRailCard',
    importPath: '@investhome/ui',
    figmaName: 'Data Display / Right Rail Card / Default / Default',
    variants: [],
    states: [],
    sizes: [],
    status: 'experimental',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'data-empty-state',
    category: 'data-display',
    codeName: 'EmptyState',
    importPath: '@investhome/ui',
    figmaName: 'Data Display / Empty State / Compact / Default',
    variants: ['default', 'compact'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'data-error-state',
    category: 'data-display',
    codeName: 'ErrorState',
    importPath: '@investhome/ui',
    figmaName: 'Data Display / Error State / Compact / Default',
    variants: ['default', 'compact'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'data-loading-state',
    category: 'data-display',
    codeName: 'LoadingState',
    importPath: '@investhome/ui',
    figmaName: 'Data Display / Loading State / Skeleton / Default',
    variants: ['text', 'skeleton'],
    states: ['loading'],
    sizes: [],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'data-table',
    category: 'data-display',
    codeName: 'Table',
    importPath: '@investhome/ui',
    figmaName: 'Data Display / Table / Standard / Default',
    variants: [],
    states: [],
    sizes: ['compact', 'standard', 'comfortable'],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/table-density-contract.md',
  },
  {
    id: 'data-trend-indicator',
    category: 'data-display',
    codeName: 'TrendIndicator',
    importPath: '@investhome/ui',
    figmaName: 'Data Display / Trend Indicator / Up / Default',
    variants: ['up', 'down', 'neutral'],
    states: [],
    sizes: [],
    status: 'experimental',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/component-source-of-truth.md',
  },
  {
    id: 'chart-container',
    category: 'chart',
    codeName: 'ChartContainer',
    importPath: '@investhome/ui',
    figmaName: 'Chart / Container / Standard / Ready',
    variants: [],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: ['compact', 'standard', 'large', 'hero'],
    status: 'canonical',
    owner: 'packages/ui',
    documentationPath: 'docs/design-system/chart-design-contract.md',
  },
  {
    id: 'chart-line',
    category: 'chart',
    codeName: 'LineChart',
    importPath: '@/components/design-system/charts',
    figmaName: 'Chart / Line / Standard / Default',
    variants: [],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: ['compact', 'standard', 'large', 'hero'],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/chart-design-contract.md',
  },
  {
    id: 'chart-area',
    category: 'chart',
    codeName: 'AreaChart',
    importPath: '@/components/design-system/charts',
    figmaName: 'Chart / Area / Standard / Default',
    variants: [],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: ['compact', 'standard', 'large', 'hero'],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/chart-design-contract.md',
  },
  {
    id: 'chart-bar',
    category: 'chart',
    codeName: 'BarChart',
    importPath: '@/components/design-system/charts',
    figmaName: 'Chart / Bar / Standard / Default',
    variants: [],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: ['compact', 'standard', 'large', 'hero'],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/chart-design-contract.md',
  },
  {
    id: 'chart-donut',
    category: 'chart',
    codeName: 'DonutChart',
    importPath: '@/components/design-system/charts',
    figmaName: 'Chart / Donut / Standard / Default',
    variants: [],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: ['compact', 'standard', 'large', 'hero'],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/chart-design-contract.md',
  },
  {
    id: 'chart-funnel',
    category: 'chart',
    codeName: 'FunnelChart',
    importPath: '@/components/design-system/charts',
    figmaName: 'Chart / Funnel / Standard / Default',
    variants: [],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: ['compact', 'standard', 'large', 'hero'],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/chart-design-contract.md',
  },
  {
    id: 'chart-progress',
    category: 'chart',
    codeName: 'ProgressChart',
    importPath: '@/components/design-system/charts',
    figmaName: 'Chart / Progress / Standard / Default',
    variants: [],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: ['compact', 'standard', 'large', 'hero'],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/chart-design-contract.md',
  },
  {
    id: 'chart-sparkline',
    category: 'chart',
    codeName: 'Sparkline',
    importPath: '@/components/design-system/charts',
    figmaName: 'Chart / Sparkline / Compact / Default',
    variants: [],
    states: ['ready'],
    sizes: ['compact'],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/chart-design-contract.md',
  },
  {
    id: 'chart-timeline',
    category: 'chart',
    codeName: 'TimelineChart',
    importPath: '@/components/design-system/charts',
    figmaName: 'Chart / Timeline / Standard / Default',
    variants: [],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: ['compact', 'standard', 'large', 'hero'],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/chart-design-contract.md',
  },
  {
    id: 'chart-heatmap',
    category: 'chart',
    codeName: 'HeatmapChart',
    importPath: '@/components/design-system/charts',
    figmaName: 'Chart / Heatmap / Standard / Default',
    variants: [],
    states: ['ready', 'loading', 'empty', 'error'],
    sizes: ['compact', 'standard', 'large', 'hero'],
    status: 'experimental',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/chart-design-contract.md',
  },
  {
    id: 'layout-dashboard-grid',
    category: 'navigation',
    codeName: 'DashboardGrid',
    importPath: '@/components/design-system/layout',
    figmaName: 'Foundation / Grid / Desktop / 12',
    variants: ['desktop-12', 'tablet-8', 'mobile-1'],
    states: [],
    sizes: [],
    status: 'canonical',
    owner: 'apps/web/design-system',
    documentationPath: 'docs/design-system/responsive-component-contract.md',
  },
] as const;

export function getDesignAssetsByStatus(status: DesignAssetStatus): DesignAssetEntry[] {
  return DESIGN_ASSET_REGISTRY.filter((entry) => entry.status === status);
}

export function getCanonicalDesignAssets(): DesignAssetEntry[] {
  return getDesignAssetsByStatus('canonical');
}

export function getDeprecatedCandidateAssets(): DesignAssetEntry[] {
  return DESIGN_ASSET_REGISTRY.filter(
    (entry) => entry.status === 'deprecated-candidate' || entry.status === 'legacy',
  );
}
