import type { CompanyWorkspacePreview } from './companies-model';

/** Typed local fixtures for Companies UX review — no live API calls. */
export function makeCompaniesPreview(): CompanyWorkspacePreview {
  return {
    totalCompanies: 248,
    totalPages: 13,
    kpis: [
      {
        key: 'total',
        value: 248,
        hintKey: 'totalHint',
        delta: '+18',
        deltaTone: 'up',
      },
      {
        key: 'activePartners',
        value: 86,
        hintKey: 'activePartnersHint',
        delta: '+9',
        deltaTone: 'up',
      },
      {
        key: 'investors',
        value: 42,
        hintKey: 'investorsHint',
        delta: '+6',
        deltaTone: 'up',
      },
      {
        key: 'newThisMonth',
        value: 24,
        hintKey: 'newThisMonthHint',
        delta: '+24',
        deltaTone: 'up',
      },
      {
        key: 'openCollaborations',
        value: 31,
        hintKey: 'openCollaborationsHint',
        delta: '+7',
        deltaTone: 'up',
      },
    ],
    companies: [
      {
        id: 'co-temple',
        name: 'The Temple Group',
        subtitleKey: 'templeSubtitle',
        initials: 'TG',
        logoTone: 'navy',
        category: 'investor',
        country: 'us',
        contactName: 'James Temple',
        contactRoleKey: 'managingPartner',
        contactInitials: 'JT',
        openProjects: 5,
        lastActivityKey: 'meeting',
        lastActivityDate: '22.07.2026',
        healthScore: 94,
        health: 'excellent',
        aiSummaryKey: 'temple',
        status: 'active',
        relation: 'strategicPartner',
        owner: 'Emin Bilgin',
        tags: ['strategic', 'capital'],
      },
      {
        id: 'co-marina',
        name: 'Marina Heights LLC',
        subtitleKey: 'marinaSubtitle',
        initials: 'MH',
        logoTone: 'cyan',
        category: 'developer',
        country: 'ae',
        contactName: 'Sara Al-Hassan',
        contactRoleKey: 'ceo',
        contactInitials: 'SA',
        openProjects: 3,
        lastActivityKey: 'call',
        lastActivityDate: '21.07.2026',
        healthScore: 82,
        health: 'good',
        aiSummaryKey: 'marina',
        status: 'active',
        relation: 'client',
        owner: 'Ayşe Demir',
        tags: ['pipeline', 'coastal'],
      },
      {
        id: 'co-bay',
        name: 'Bay Area Architects',
        subtitleKey: 'baySubtitle',
        initials: 'BA',
        logoTone: 'violet',
        category: 'architecture',
        country: 'us',
        contactName: 'Elena Brooks',
        contactRoleKey: 'designDirector',
        contactInitials: 'EB',
        openProjects: 2,
        lastActivityKey: 'email',
        lastActivityDate: '19.07.2026',
        healthScore: 68,
        health: 'medium',
        aiSummaryKey: 'bay',
        status: 'active',
        relation: 'vendor',
        owner: 'Mehmet Kaya',
        tags: ['design'],
      },
      {
        id: 'co-liberty',
        name: 'Liberty Law Partners',
        subtitleKey: 'libertySubtitle',
        initials: 'LL',
        logoTone: 'amber',
        category: 'legal',
        country: 'uk',
        contactName: 'Oliver Grant',
        contactRoleKey: 'partner',
        contactInitials: 'OG',
        openProjects: 1,
        lastActivityKey: 'note',
        lastActivityDate: '15.07.2026',
        healthScore: 45,
        health: 'attention',
        aiSummaryKey: 'liberty',
        status: 'prospect',
        relation: 'advisor',
        owner: 'Can Özkan',
        tags: ['legal', 'closing'],
      },
      {
        id: 'co-sunset',
        name: 'Sunset Title Company',
        subtitleKey: 'sunsetSubtitle',
        initials: 'ST',
        logoTone: 'rose',
        category: 'title',
        country: 'us',
        contactName: 'Mia Chen',
        contactRoleKey: 'opsLead',
        contactInitials: 'MC',
        openProjects: 0,
        lastActivityKey: 'task',
        lastActivityDate: '08.07.2026',
        healthScore: 32,
        health: 'risk',
        aiSummaryKey: 'sunset',
        status: 'inactive',
        relation: 'vendor',
        owner: 'Zeynep Arslan',
        tags: ['title'],
      },
      {
        id: 'co-bosphorus',
        name: 'Bosphorus Capital',
        subtitleKey: 'bosphorusSubtitle',
        initials: 'BC',
        logoTone: 'green',
        category: 'investor',
        country: 'tr',
        contactName: 'Emre Yılmaz',
        contactRoleKey: 'investmentLead',
        contactInitials: 'EY',
        openProjects: 4,
        lastActivityKey: 'meeting',
        lastActivityDate: '23.07.2026',
        healthScore: 88,
        health: 'good',
        aiSummaryKey: 'bosphorus',
        status: 'active',
        relation: 'investor',
        owner: 'Emin Bilgin',
        tags: ['capital', 'local'],
      },
      {
        id: 'co-harbor',
        name: 'Harbor Brokerage',
        subtitleKey: 'harborSubtitle',
        initials: 'HB',
        logoTone: 'cyan',
        category: 'broker',
        country: 'sg',
        contactName: 'Wei Lin',
        contactRoleKey: 'broker',
        contactInitials: 'WL',
        openProjects: 2,
        lastActivityKey: 'call',
        lastActivityDate: '20.07.2026',
        healthScore: 74,
        health: 'medium',
        aiSummaryKey: 'harbor',
        status: 'active',
        relation: 'strategicPartner',
        owner: 'Ayşe Demir',
        tags: ['broker'],
      },
      {
        id: 'co-nordic',
        name: 'Nordic Trust Bank',
        subtitleKey: 'nordicSubtitle',
        initials: 'NT',
        logoTone: 'navy',
        category: 'bank',
        country: 'de',
        contactName: 'Lukas Weber',
        contactRoleKey: 'relationshipMgr',
        contactInitials: 'LW',
        openProjects: 1,
        lastActivityKey: 'email',
        lastActivityDate: '18.07.2026',
        healthScore: 79,
        health: 'good',
        aiSummaryKey: 'nordic',
        status: 'active',
        relation: 'advisor',
        owner: 'Mehmet Kaya',
        tags: ['finance'],
      },
    ],
    recentCompanies: [
      {
        id: 'recent-1',
        name: 'Bosphorus Capital',
        initials: 'BC',
        logoTone: 'green',
        addedAtKey: 'hoursAgo2',
      },
      {
        id: 'recent-2',
        name: 'Harbor Brokerage',
        initials: 'HB',
        logoTone: 'cyan',
        addedAtKey: 'yesterday',
      },
      {
        id: 'recent-3',
        name: 'Nordic Trust Bank',
        initials: 'NT',
        logoTone: 'navy',
        addedAtKey: 'daysAgo3',
      },
      {
        id: 'recent-4',
        name: 'The Temple Group',
        initials: 'TG',
        logoTone: 'navy',
        addedAtKey: 'daysAgo5',
      },
    ],
    upcomingMeetings: [
      {
        id: 'meet-1',
        company: 'Marina Heights LLC',
        typeKey: 'projectKickoff',
        whenKey: 'tomorrow1000',
      },
      {
        id: 'meet-2',
        company: 'The Temple Group',
        typeKey: 'capitalReview',
        whenKey: 'wed1430',
      },
      {
        id: 'meet-3',
        company: 'Bosphorus Capital',
        typeKey: 'pipelineSync',
        whenKey: 'thu1100',
      },
    ],
    recommendations: [
      { id: 'rec-1', bodyKey: 'marinaOpportunity' },
      { id: 'rec-2', bodyKey: 'sunsetRisk' },
      { id: 'rec-3', bodyKey: 'libertyFollowUp' },
      { id: 'rec-4', bodyKey: 'templeExpansion' },
    ],
    categoryDistribution: [
      { key: 'investor', pct: 24 },
      { key: 'developer', pct: 22 },
      { key: 'architecture', pct: 16 },
      { key: 'legal', pct: 14 },
      { key: 'title', pct: 12 },
      { key: 'other', pct: 12 },
    ],
    activePartners: [
      {
        id: 'ap-1',
        name: 'The Temple Group',
        initials: 'TG',
        logoTone: 'navy',
        activityCount: 18,
        lastContactKey: 'daysAgo1',
      },
      {
        id: 'ap-2',
        name: 'Marina Heights LLC',
        initials: 'MH',
        logoTone: 'cyan',
        activityCount: 14,
        lastContactKey: 'daysAgo2',
      },
      {
        id: 'ap-3',
        name: 'Bosphorus Capital',
        initials: 'BC',
        logoTone: 'green',
        activityCount: 11,
        lastContactKey: 'hoursAgo6',
      },
    ],
    owners: ['Emin Bilgin', 'Ayşe Demir', 'Mehmet Kaya', 'Can Özkan', 'Zeynep Arslan'],
    tags: ['strategic', 'capital', 'pipeline', 'coastal', 'design', 'legal', 'closing', 'title', 'local', 'broker', 'finance'],
    countries: ['us', 'ae', 'uk', 'tr', 'de', 'sg'],
  };
}
