import type { CalendarWorkspacePreview } from './calendar-model';

/** Typed local fixtures for Calendar UX review — no live API / scheduling engine. */
export function makeCalendarPreview(): CalendarWorkspacePreview {
  return {
    weekStartIso: '2025-07-21',
    currentDayIndex: 2,
    nowMinute: 195,
    rangeLabelKey: 'jul21to27',
    kpis: [
      {
        key: 'todayEvents',
        value: '18',
        hintKey: 'todayEventsHint',
        delta: '+3',
        deltaTone: 'up',
      },
      {
        key: 'thisWeek',
        value: '54',
        hintKey: 'thisWeekHint',
        delta: '+8',
        deltaTone: 'up',
      },
      {
        key: 'upcomingMeetings',
        value: '7',
        hintKey: 'upcomingMeetingsHint',
        delta: '+2',
        deltaTone: 'up',
      },
      {
        key: 'completed',
        value: '26',
        hintKey: 'completedHint',
        delta: '+5',
        deltaTone: 'up',
        tone: 'success',
      },
      {
        key: 'attendanceRate',
        value: '92%',
        hintKey: 'attendanceRateHint',
        delta: '+4%',
        deltaTone: 'up',
      },
    ],
    events: [
      {
        id: 'ev-all-sat',
        titleKey: 'siteVisitSaturday',
        customer: 'Marina Heights',
        project: 'Marina Heights',
        type: 'siteVisit',
        dayIndex: 5,
        startMinute: null,
        durationMinutes: 0,
        participantCount: 3,
        allDay: true,
      },
      {
        id: 'ev-all-sun',
        titleKey: 'reportingSunday',
        customer: 'Internal',
        project: 'Operations',
        type: 'task',
        dayIndex: 6,
        startMinute: null,
        durationMinutes: 0,
        participantCount: 2,
        allDay: true,
      },
      {
        id: 'ev-mon-1',
        titleKey: 'ahmetProjectPresentation',
        customer: 'Ahmet Yılmaz',
        project: 'The Temple',
        type: 'presentation',
        dayIndex: 0,
        startMinute: 60,
        durationMinutes: 90,
        participantCount: 4,
      },
      {
        id: 'ev-tue-1',
        titleKey: 'aysePhoneCall',
        customer: 'Ayşe Demir',
        project: 'Ocean View',
        type: 'phone',
        dayIndex: 1,
        startMinute: 120,
        durationMinutes: 45,
        participantCount: 2,
      },
      {
        id: 'ev-wed-1',
        titleKey: 'marinaProgressMeeting',
        customer: 'Selin Kara',
        project: 'Marina Heights',
        type: 'meeting',
        dayIndex: 2,
        startMinute: 60,
        durationMinutes: 75,
        participantCount: 5,
      },
      {
        id: 'ev-wed-2',
        titleKey: 'roiAnalysisReview',
        customer: 'Ahmet Yılmaz',
        project: 'The Temple',
        type: 'demo',
        dayIndex: 2,
        startMinute: 240,
        durationMinutes: 60,
        participantCount: 3,
      },
      {
        id: 'ev-thu-1',
        titleKey: 'yusufPhoneCall',
        customer: 'Yusuf Bildirici',
        project: 'Park Avenue',
        type: 'phone',
        dayIndex: 3,
        startMinute: 90,
        durationMinutes: 40,
        participantCount: 2,
      },
      {
        id: 'ev-thu-2',
        titleKey: 'eminInternalReview',
        customer: 'Emin Bilgin',
        project: 'Internal',
        type: 'internalMeeting',
        dayIndex: 3,
        startMinute: 270,
        durationMinutes: 60,
        participantCount: 4,
      },
      {
        id: 'ev-fri-1',
        titleKey: 'weeklyTeamMeeting',
        customer: 'Sales Team',
        project: 'Internal',
        type: 'internalMeeting',
        dayIndex: 4,
        startMinute: 120,
        durationMinutes: 60,
        participantCount: 8,
      },
      {
        id: 'ev-fri-2',
        titleKey: 'investorBriefing',
        customer: 'Zeynep Arslan',
        project: 'Skyline Lofts',
        type: 'investorMeeting',
        dayIndex: 4,
        startMinute: 300,
        durationMinutes: 75,
        participantCount: 3,
      },
      {
        id: 'ev-mon-2',
        titleKey: 'documentHandoff',
        customer: 'Mehmet Kaya',
        project: 'Garden Court',
        type: 'documentHandoff',
        dayIndex: 0,
        startMinute: 300,
        durationMinutes: 45,
        participantCount: 2,
      },
      {
        id: 'ev-tue-2',
        titleKey: 'followUpTask',
        customer: 'Elif Yıldız',
        project: 'Ocean View',
        type: 'task',
        dayIndex: 1,
        startMinute: 300,
        durationMinutes: 30,
        participantCount: 1,
      },
      {
        id: 'ev-wed-3',
        titleKey: 'documentHandoff',
        customer: 'Mehmet Kaya',
        project: 'Garden Court',
        type: 'documentHandoff',
        dayIndex: 2,
        startMinute: 360,
        durationMinutes: 45,
        participantCount: 2,
      },
      {
        id: 'ev-mon-3',
        titleKey: 'aysePhoneCall',
        customer: 'Ayşe Demir',
        project: 'Ocean View',
        type: 'phone',
        dayIndex: 0,
        startMinute: 210,
        durationMinutes: 30,
        participantCount: 2,
      },
      {
        id: 'ev-thu-3',
        titleKey: 'siteVisitSaturday',
        customer: 'Marina Heights',
        project: 'Marina Heights',
        type: 'siteVisit',
        dayIndex: 3,
        startMinute: 180,
        durationMinutes: 90,
        participantCount: 3,
      },
    ],
    upcoming: [
      {
        id: 'up-1',
        titleKey: 'marinaProgressMeeting',
        timeLabel: '12:00',
        when: 'today',
        type: 'meeting',
      },
      {
        id: 'up-2',
        titleKey: 'roiAnalysisReview',
        timeLabel: '15:00',
        when: 'today',
        type: 'demo',
      },
      {
        id: 'up-3',
        titleKey: 'yusufPhoneCall',
        timeLabel: '10:30',
        when: 'tomorrow',
        type: 'phone',
      },
      {
        id: 'up-4',
        titleKey: 'weeklyTeamMeeting',
        timeLabel: '10:00',
        when: 'later',
        type: 'internalMeeting',
      },
    ],
    aiSuggestions: [
      { id: 'ai-1', bodyKey: 'conflictToday' },
      { id: 'ai-2', bodyKey: 'followUpSlot' },
      { id: 'ai-3', bodyKey: 'freeSlotWed' },
      { id: 'ai-4', bodyKey: 'rescheduleDemo' },
    ],
    sync: [
      { id: 'sync-google', providerKey: 'google', status: 'connected' },
      { id: 'sync-outlook', providerKey: 'outlook', status: 'connected' },
    ],
  };
}
