import type { DocumentWorkspacePreview } from './documents-model';

/** Typed local fixtures for Documents UX review — no live API calls. */
export function makeDocumentsPreview(): DocumentWorkspacePreview {
  return {
    totalDocuments: 432,
    kpis: [
      {
        key: 'total',
        value: 432,
        hintKey: 'allTime',
        delta: '+12%',
        deltaTone: 'up',
      },
      {
        key: 'awaitingSignature',
        value: 18,
        hintKey: 'totalAwaiting',
        delta: '+5%',
        deltaTone: 'up',
      },
      {
        key: 'addedLast7Days',
        value: 27,
        hintKey: 'last7Days',
        delta: '+8%',
        deltaTone: 'up',
      },
      {
        key: 'shared',
        value: 64,
        hintKey: 'activelyShared',
        delta: '+15%',
        deltaTone: 'up',
      },
    ],
    documents: [
      {
        id: 'doc-sales-contract',
        name: 'Satış Sözleşmesi.pdf',
        fileType: 'pdf',
        owner: 'Ahmet Yılmaz',
        project: 'Marina Heights',
        status: 'signed',
        size: '2.4 MB',
        version: 'v2.1',
        date: '12.06.2025',
      },
      {
        id: 'doc-id-copy',
        name: 'Kimlik Fotokopisi.pdf',
        fileType: 'pdf',
        owner: 'Ayşe Demir',
        project: 'Ocean View',
        status: 'awaitingSignature',
        size: '1.1 MB',
        version: 'v1.0',
        date: '11.06.2025',
      },
      {
        id: 'doc-payment-plan',
        name: 'Ödeme Planı.xlsx',
        fileType: 'xlsx',
        owner: 'Mehmet Kaya',
        project: 'Park Avenue',
        status: 'shared',
        size: '856 KB',
        version: 'v3.0',
        date: '10.06.2025',
      },
      {
        id: 'doc-reservation',
        name: 'Rezervasyon Formu.docx',
        fileType: 'docx',
        owner: 'Zeynep Arslan',
        project: 'Sunset Blvd',
        status: 'signed',
        size: '420 KB',
        version: 'v1.2',
        date: '09.06.2025',
      },
      {
        id: 'doc-title-deed',
        name: 'Tapu Belgesi.pdf',
        fileType: 'pdf',
        owner: 'Can Özkan',
        project: 'Skyline Lofts',
        status: 'awaitingSignature',
        size: '3.2 MB',
        version: 'v1.0',
        date: '08.06.2025',
      },
      {
        id: 'doc-financial-analysis',
        name: 'Finansal Analiz.xlsx',
        fileType: 'xlsx',
        owner: 'Elif Yıldız',
        project: 'Garden Court',
        status: 'shared',
        size: '1.8 MB',
        version: 'v2.0',
        date: '07.06.2025',
      },
      {
        id: 'doc-power-of-attorney',
        name: 'Vekaletname.pdf',
        fileType: 'pdf',
        owner: 'Burak Şahin',
        project: 'Marina Heights',
        status: 'signed',
        size: '980 KB',
        version: 'v1.1',
        date: '06.06.2025',
      },
      {
        id: 'doc-presentation',
        name: 'Proje Sunumu.docx',
        fileType: 'docx',
        owner: 'Deniz Acar',
        project: 'Ocean View',
        status: 'draft',
        size: '5.6 MB',
        version: 'v4.2',
        date: '05.06.2025',
      },
    ],
    aiSummary: {
      title: 'Marina Heights - Satış Sözleşmesi',
      bodyKey: 'marinaSalesContract',
      lastUpdated: '12.06.2025',
    },
    recentlyOpened: [
      {
        id: 'recent-1',
        name: 'Satış Sözleşmesi.pdf',
        fileType: 'pdf',
        openedAtKey: 'minutesAgo10',
      },
      {
        id: 'recent-2',
        name: 'Ödeme Planı.xlsx',
        fileType: 'xlsx',
        openedAtKey: 'hoursAgo1',
      },
      {
        id: 'recent-3',
        name: 'Rezervasyon Formu.docx',
        fileType: 'docx',
        openedAtKey: 'yesterday',
      },
    ],
    signatureDistribution: {
      signed: 289,
      awaiting: 18,
      rejected: 3,
    },
    missingCount: 5,
    missingItems: [
      { id: 'miss-1', labelKey: 'idCopy' },
      { id: 'miss-2', labelKey: 'proofOfAddress' },
      { id: 'miss-3', labelKey: 'bankStatement' },
    ],
    activities: [
      { id: 'act-1', titleKey: 'ahmetSigned', timeKey: 'hoursAgo2' },
      { id: 'act-2', titleKey: 'ayseShared', timeKey: 'hoursAgo5' },
      { id: 'act-3', titleKey: 'mehmetUploaded', timeKey: 'yesterday' },
      { id: 'act-4', titleKey: 'zeynepViewed', timeKey: 'daysAgo2' },
    ],
    customers: ['Ahmet Yılmaz', 'Ayşe Demir', 'Mehmet Kaya', 'Zeynep Arslan', 'Can Özkan'],
    projects: [
      'Marina Heights',
      'Ocean View',
      'Park Avenue',
      'Sunset Blvd',
      'Skyline Lofts',
      'Garden Court',
    ],
    documentTypes: ['pdf', 'docx', 'xlsx'],
  };
}
