"""Authorization resource and action constants."""

RESOURCES = frozenset(
    {
        "executive",
        "leads",
        "investors",
        "projects",
        "finance",
        "users",
        "roles",
        "settings",
        "activity",
        "notifications",
        "search",
        "documents",
        "construction",
        "marketing",
        "reports",
    }
)

ACTIONS = frozenset(
    {
        "view",
        "create",
        "update",
        "archive",
        "delete",
        "export",
        "approve",
        "manage",
        "download",
        "view_confidential",
        "view_highly_confidential",
        "analyze",
        "reprocess",
        "view_analysis",
        "ask",
        "export_analysis",
        "manage_ai",
        "view_sensitive_analysis",
    }
)

SYSTEM_ROLE_CODES = frozenset(
    {
        "super_admin",
        "executive",
        "partner",
        "sales",
        "investor_relations",
        "finance",
        "construction",
        "marketing",
        "operations",
        "assistant",
        "read_only",
    }
)

# Default permission grants per system role: {role_code: [(resource, action), ...]}
DEFAULT_ROLE_PERMISSIONS: dict[str, list[tuple[str, str]]] = {
    "super_admin": [(resource, action) for resource in RESOURCES for action in ACTIONS],
    "executive": [
        ("executive", "view"),
        ("executive", "export"),
        ("leads", "view"),
        ("investors", "view"),
        ("projects", "view"),
        ("finance", "view"),
        ("finance", "export"),
        ("activity", "view"),
        ("notifications", "view"),
        ("search", "view"),
        ("documents", "view"),
        ("documents", "download"),
        ("documents", "view_confidential"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("reports", "view"),
        ("reports", "export"),
        ("users", "view"),
    ],
    "partner": [
        ("executive", "view"),
        ("leads", "view"),
        ("investors", "view"),
        ("projects", "view"),
        ("finance", "view"),
        ("search", "view"),
        ("documents", "view"),
        ("documents", "download"),
        ("documents", "view_confidential"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("reports", "view"),
    ],
    "sales": [
        ("leads", "view"),
        ("leads", "create"),
        ("leads", "update"),
        ("leads", "archive"),
        ("investors", "view"),
        ("investors", "create"),
        ("investors", "update"),
        ("projects", "view"),
        ("documents", "view"),
        ("documents", "create"),
        ("documents", "download"),
        ("notifications", "view"),
        ("search", "view"),
    ],
    "investor_relations": [
        ("investors", "view"),
        ("investors", "create"),
        ("investors", "update"),
        ("investors", "archive"),
        ("leads", "view"),
        ("leads", "update"),
        ("projects", "view"),
        ("finance", "view"),
        ("executive", "view"),
        ("documents", "view"),
        ("documents", "create"),
        ("documents", "update"),
        ("documents", "download"),
        ("documents", "view_confidential"),
        ("documents", "analyze"),
        ("documents", "reprocess"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("documents", "export_analysis"),
        ("documents", "view_sensitive_analysis"),
        ("notifications", "view"),
        ("search", "view"),
    ],
    "finance": [
        ("finance", "view"),
        ("finance", "create"),
        ("finance", "update"),
        ("finance", "archive"),
        ("finance", "export"),
        ("finance", "approve"),
        ("projects", "view"),
        ("investors", "view"),
        ("executive", "view"),
        ("documents", "view"),
        ("documents", "create"),
        ("documents", "update"),
        ("documents", "download"),
        ("documents", "view_confidential"),
        ("documents", "analyze"),
        ("documents", "reprocess"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("documents", "export_analysis"),
        ("documents", "view_sensitive_analysis"),
        ("documents", "archive"),
        ("reports", "view"),
        ("reports", "export"),
        ("notifications", "view"),
        ("search", "view"),
    ],
    "construction": [
        ("projects", "view"),
        ("projects", "update"),
        ("construction", "view"),
        ("construction", "create"),
        ("construction", "update"),
        ("finance", "view"),
        ("documents", "view"),
        ("documents", "create"),
        ("documents", "update"),
        ("documents", "download"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("documents", "reprocess"),
        ("documents", "approve"),
        ("search", "view"),
    ],
    "marketing": [
        ("leads", "view"),
        ("projects", "view"),
        ("marketing", "view"),
        ("marketing", "create"),
        ("marketing", "update"),
        ("search", "view"),
    ],
    "operations": [
        ("projects", "view"),
        ("projects", "update"),
        ("finance", "view"),
        ("documents", "view"),
        ("documents", "create"),
        ("documents", "update"),
        ("documents", "download"),
        ("documents", "archive"),
        ("activity", "view"),
        ("notifications", "view"),
        ("search", "view"),
    ],
    "assistant": [
        ("leads", "view"),
        ("leads", "create"),
        ("leads", "update"),
        ("investors", "view"),
        ("investors", "create"),
        ("investors", "update"),
        ("projects", "view"),
        ("search", "view"),
    ],
    "read_only": [
        ("executive", "view"),
        ("leads", "view"),
        ("investors", "view"),
        ("projects", "view"),
        ("finance", "view"),
        ("activity", "view"),
        ("notifications", "view"),
        ("search", "view"),
        ("documents", "view"),
        ("documents", "download"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("reports", "view"),
    ],
}
