"""Authorization resource and action constants."""

RESOURCES = frozenset(
    {
        "executive",
        "leads",
        "investors",
        "projects",
        "finance",
        "users",
        "roles",
        "settings",
        "company",
        "offices",
        "brand",
        "brand_assets",
        "organization",
        "integrations",
        "ai_providers",
        "storage",
        "activity",
        "notifications",
        "search",
        "documents",
        "construction",
        "design",
        "inventory",
        "marketing",
        "reports",
    }
)

ACTIONS = frozenset(
    {
        "view",
        "create",
        "update",
        "archive",
        "delete",
        "export",
        "approve",
        "manage",
        "download",
        "view_confidential",
        "view_highly_confidential",
        "analyze",
        "reprocess",
        "view_analysis",
        "ask",
        "export_analysis",
        "manage_ai",
        "view_sensitive_analysis",
        "manage_assets",
        "save_version",
        "manage_styles",
        "manage_materials",
        "manage_furniture",
        "submit_review",
        "restore",
        "manage_status",
        "reserve",
        "release_hold",
        "request_reservation",
        "approve_reservation",
        "cancel_reservation",
        "mark_deposit_received",
        "convert_reservation",
        "view_price",
        "create_initial_price",
        "request_price_change",
        "review_price_change",
        "approve_price",
        "reject_price",
        "view_price_history",
        "view_sensitive_price",
        "self_approve_price",
    }
)

SYSTEM_ROLE_CODES = frozenset(
    {
        "super_admin",
        "executive",
        "partner",
        "sales",
        "investor_relations",
        "finance",
        "construction",
        "marketing",
        "operations",
        "assistant",
        "read_only",
    }
)

# Default permission grants per system role: {role_code: [(resource, action), ...]}
DEFAULT_ROLE_PERMISSIONS: dict[str, list[tuple[str, str]]] = {
    "super_admin": [(resource, action) for resource in RESOURCES for action in ACTIONS],
    "executive": [
        ("executive", "view"),
        ("executive", "export"),
        ("leads", "view"),
        ("investors", "view"),
        ("projects", "view"),
        ("finance", "view"),
        ("finance", "export"),
        ("activity", "view"),
        ("notifications", "view"),
        ("search", "view"),
        ("documents", "view"),
        ("documents", "download"),
        ("documents", "view_confidential"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("reports", "view"),
        ("reports", "export"),
        ("users", "view"),
        ("settings", "view"),
        ("company", "view"),
        ("brand", "view"),
        ("offices", "view"),
        ("design", "view"),
        ("design", "approve"),
        ("inventory", "view"),
        ("inventory", "view_price"),
        ("inventory", "review_price_change"),
        ("inventory", "approve_price"),
        ("inventory", "reject_price"),
        ("inventory", "view_price_history"),
        ("inventory", "view_sensitive_price"),
    ],
    "partner": [
        ("executive", "view"),
        ("leads", "view"),
        ("investors", "view"),
        ("projects", "view"),
        ("finance", "view"),
        ("search", "view"),
        ("documents", "view"),
        ("documents", "download"),
        ("documents", "view_confidential"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("reports", "view"),
        ("design", "view"),
        ("inventory", "view"),
        ("inventory", "view_price"),
        ("inventory", "view_price_history"),
    ],
    "sales": [
        ("leads", "view"),
        ("leads", "create"),
        ("leads", "update"),
        ("leads", "archive"),
        ("investors", "view"),
        ("investors", "create"),
        ("investors", "update"),
        ("projects", "view"),
        ("documents", "view"),
        ("documents", "create"),
        ("documents", "download"),
        ("notifications", "view"),
        ("search", "view"),
        ("inventory", "view"),
        ("inventory", "create"),
        ("inventory", "update"),
        ("inventory", "reserve"),
        ("inventory", "release_hold"),
        ("inventory", "request_reservation"),
        ("inventory", "cancel_reservation"),
        ("inventory", "view_price"),
        ("inventory", "request_price_change"),
        ("inventory", "view_price_history"),
    ],
    "investor_relations": [
        ("investors", "view"),
        ("investors", "create"),
        ("investors", "update"),
        ("investors", "archive"),
        ("leads", "view"),
        ("leads", "update"),
        ("projects", "view"),
        ("finance", "view"),
        ("executive", "view"),
        ("documents", "view"),
        ("documents", "create"),
        ("documents", "update"),
        ("documents", "download"),
        ("documents", "view_confidential"),
        ("documents", "analyze"),
        ("documents", "reprocess"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("documents", "export_analysis"),
        ("documents", "view_sensitive_analysis"),
        ("notifications", "view"),
        ("search", "view"),
        ("inventory", "view"),
        ("inventory", "update"),
        ("inventory", "reserve"),
        ("inventory", "release_hold"),
        ("inventory", "request_reservation"),
        ("inventory", "approve_reservation"),
        ("inventory", "cancel_reservation"),
        ("inventory", "mark_deposit_received"),
        ("inventory", "convert_reservation"),
        ("inventory", "view_price"),
        ("inventory", "view_price_history"),
    ],
    "finance": [
        ("finance", "view"),
        ("finance", "create"),
        ("finance", "update"),
        ("finance", "archive"),
        ("finance", "export"),
        ("finance", "approve"),
        ("projects", "view"),
        ("investors", "view"),
        ("executive", "view"),
        ("documents", "view"),
        ("documents", "create"),
        ("documents", "update"),
        ("documents", "download"),
        ("documents", "view_confidential"),
        ("documents", "analyze"),
        ("documents", "reprocess"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("documents", "export_analysis"),
        ("documents", "view_sensitive_analysis"),
        ("documents", "archive"),
        ("reports", "view"),
        ("reports", "export"),
        ("notifications", "view"),
        ("search", "view"),
        ("inventory", "view"),
        ("inventory", "approve_reservation"),
        ("inventory", "mark_deposit_received"),
        ("inventory", "view_price"),
        ("inventory", "create_initial_price"),
        ("inventory", "request_price_change"),
        ("inventory", "review_price_change"),
        ("inventory", "approve_price"),
        ("inventory", "reject_price"),
        ("inventory", "view_price_history"),
        ("inventory", "view_sensitive_price"),
    ],
    "construction": [
        ("projects", "view"),
        ("projects", "update"),
        ("construction", "view"),
        ("construction", "create"),
        ("construction", "update"),
        ("design", "view"),
        ("design", "create"),
        ("design", "update"),
        ("design", "save_version"),
        ("design", "manage_styles"),
        ("design", "manage_materials"),
        ("design", "manage_furniture"),
        ("design", "submit_review"),
        ("design", "approve"),
        ("design", "archive"),
        ("finance", "view"),
        ("documents", "view"),
        ("documents", "create"),
        ("documents", "update"),
        ("documents", "download"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("documents", "reprocess"),
        ("documents", "approve"),
        ("search", "view"),
        ("inventory", "view"),
        ("inventory", "create"),
        ("inventory", "update"),
        ("inventory", "manage_status"),
    ],
    "marketing": [
        ("leads", "view"),
        ("projects", "view"),
        ("marketing", "view"),
        ("marketing", "create"),
        ("marketing", "update"),
        ("design", "view"),
        ("design", "create"),
        ("design", "update"),
        ("design", "save_version"),
        ("design", "manage_styles"),
        ("design", "manage_materials"),
        ("design", "submit_review"),
        ("search", "view"),
        ("brand", "view"),
        ("brand_assets", "view"),
        ("inventory", "view"),
        ("inventory", "view_price"),
    ],
    "operations": [
        ("projects", "view"),
        ("projects", "update"),
        ("finance", "view"),
        ("documents", "view"),
        ("documents", "create"),
        ("documents", "update"),
        ("documents", "download"),
        ("documents", "archive"),
        ("activity", "view"),
        ("notifications", "view"),
        ("search", "view"),
        ("settings", "view"),
        ("settings", "update"),
        ("company", "view"),
        ("company", "update"),
        ("offices", "view"),
        ("offices", "manage"),
        ("brand", "view"),
        ("brand", "manage"),
        ("brand_assets", "manage_assets"),
        ("organization", "view"),
        ("organization", "manage"),
        ("integrations", "view"),
        ("ai_providers", "view"),
        ("storage", "view"),
        ("inventory", "view"),
        ("inventory", "update"),
        ("inventory", "archive"),
        ("inventory", "restore"),
        ("inventory", "manage_status"),
        ("inventory", "reserve"),
        ("inventory", "release_hold"),
        ("inventory", "request_reservation"),
        ("inventory", "approve_reservation"),
        ("inventory", "cancel_reservation"),
        ("inventory", "mark_deposit_received"),
        ("inventory", "convert_reservation"),
        ("inventory", "view_price"),
        ("inventory", "create_initial_price"),
        ("inventory", "request_price_change"),
        ("inventory", "review_price_change"),
        ("inventory", "view_price_history"),
    ],
    "assistant": [
        ("leads", "view"),
        ("leads", "create"),
        ("leads", "update"),
        ("investors", "view"),
        ("investors", "create"),
        ("investors", "update"),
        ("projects", "view"),
        ("search", "view"),
        ("inventory", "view"),
        ("inventory", "view_price"),
        ("inventory", "request_price_change"),
    ],
    "read_only": [
        ("executive", "view"),
        ("leads", "view"),
        ("investors", "view"),
        ("projects", "view"),
        ("finance", "view"),
        ("activity", "view"),
        ("notifications", "view"),
        ("search", "view"),
        ("documents", "view"),
        ("documents", "download"),
        ("documents", "view_analysis"),
        ("documents", "ask"),
        ("reports", "view"),
        ("company", "view"),
        ("brand", "view"),
        ("offices", "view"),
        ("design", "view"),
        ("inventory", "view"),
        ("inventory", "view_price"),
    ],
}
