import { L } from '../locale';
import type {
  AdoptionRoleId,
  CapabilityAuditItem,
  Certification,
  ContextualGuidance,
  HelpArticle,
  KnowledgeCheck,
  Playbook,
  SimulationScenario,
  SlaDefinition,
} from '../types';

export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: 'help-navigation',
    title: L('How navigation works', 'Gezinme nasıl çalışır'),
    summary: L('Sidebar, workspaces, and search.', 'Kenar çubuğu, çalışma alanları ve arama.'),
    body: L(
      'Use the left navigation for workspaces you are permitted to access. Restricted modules stay hidden.',
      'İzinli olduğunuz çalışma alanları için sol menüyü kullanın. Kısıtlı modüller gizlidir.',
    ),
    category: 'Getting Started',
    contentType: 'article',
    roles: ['*'],
    workspaces: ['dashboard'],
    relatedRoutes: ['/dashboard', '/dashboard/onboarding'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Platform',
    durationMinutes: 3,
    difficulty: 'beginner',
  },
  {
    id: 'help-duplicate-leads',
    title: L('How do I fix duplicate leads?', 'Yinelenen leadleri nasıl düzeltirim?'),
    summary: L('Merge and qualification guidance.', 'Birleştirme ve niteleme rehberi.'),
    body: L(
      'On Lead Detail, review match candidates before creating a new record. Escalate conflicts to your manager.',
      'Lead Detayında yeni kayıt oluşturmadan önce eşleşme adaylarını inceleyin. Çatışmaları yöneticinize yükseltin.',
    ),
    category: 'CRM',
    contentType: 'troubleshooting',
    roles: ['sales_rep', 'sales_manager', 'admin'],
    workspaces: ['crm'],
    relatedRoutes: ['/workspaces/crm/leads'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'CRM',
  },
  {
    id: 'help-reservation',
    title: L('How do I create a reservation?', 'Rezervasyon nasıl oluştururum?'),
    summary: L('Investor reservation steps.', 'Yatırımcı rezervasyon adımları.'),
    body: L(
      'From the investor profile, select a unit, set expiry, and capture required documents. Do not notify real investors in training mode.',
      'Yatırımcı profilinden birim seçin, süre belirleyin ve belgeleri kaydedin. Eğitim modunda gerçek yatırımcıları bilgilendirmeyin.',
    ),
    category: 'Investors',
    contentType: 'article',
    roles: ['investor_relations', 'admin'],
    workspaces: ['investors'],
    relatedRoutes: ['/dashboard/investors'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'IR',
  },
  {
    id: 'help-investor-invite',
    title: L('How do I invite an investor?', 'Yatırımcıyı nasıl davet ederim?'),
    summary: L('Portal invitation without CRM jargon for clients.', 'Müşteriye CRM jargonu olmadan portal daveti.'),
    body: L(
      'Enable portal access on the investor record. Real emails are blocked while TRAINING MODE is on.',
      'Yatırımcı kaydında portal erişimini etkinleştirin. EĞİTİM MODU açıkken gerçek e-postalar engellenir.',
    ),
    category: 'Portal',
    contentType: 'article',
    roles: ['investor_relations', 'admin'],
    workspaces: ['investors', 'portal'],
    relatedRoutes: ['/dashboard/investors', '/portal/help'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'IR',
  },
  {
    id: 'help-payment-approval',
    title: L('Why can’t I approve this payment?', 'Bu ödemeyi neden onaylayamıyorum?'),
    summary: L('Permission and approval matrix.', 'İzin ve onay matrisi.'),
    body: L(
      'Payment approval requires finance permissions and an eligible queue state. Training mode never posts live payments.',
      'Ödeme onayı finans izni ve uygun kuyruk durumu gerektirir. Eğitim modu canlı ödeme kaydetmez.',
    ),
    category: 'Finance',
    contentType: 'faq',
    roles: ['finance', 'cfo', 'admin'],
    workspaces: ['finance'],
    relatedRoutes: ['/dashboard/finance'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Finance',
  },
  {
    id: 'help-reconciliation',
    title: L('Explain reconciliation', 'Mutabakatı açıkla'),
    summary: L('Matching wires to obligations.', 'Havaleleri yükümlülüklere eşleştirme.'),
    body: L(
      'Match incoming wires to expected obligations, then confirm balances. Restricted cash is labeled separately.',
      'Gelen havaleleri beklenen yükümlülüklere eşleştirin, bakiyeleri doğrulayın. Kısıtlı nakit ayrı etiketlenir.',
    ),
    category: 'Finance',
    contentType: 'article',
    roles: ['finance', 'cfo', 'admin'],
    workspaces: ['finance'],
    relatedRoutes: ['/dashboard/finance'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Finance',
  },
  {
    id: 'help-project-budget',
    title: L('Planned vs actual budget', 'Planlanan ve gerçekleşen bütçe'),
    summary: L('Variance and forecast at completion.', 'Sapma ve tamamlanma tahmini.'),
    body: L(
      'Budget views compare planned vs actual and forecast at completion. Changes require approval when thresholds are exceeded.',
      'Bütçe görünümleri planlanan/gerçekleşen ve tamamlanma tahminini karşılaştırır. Eşik aşımında onay gerekir.',
    ),
    category: 'Projects',
    contentType: 'article',
    roles: ['project_manager', 'construction_ops', 'finance', 'admin'],
    workspaces: ['projects'],
    relatedRoutes: ['/dashboard/projects'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Projects',
  },
  {
    id: 'help-permit',
    title: L('Where do I update a permit?', 'İzni nerede güncellerim?'),
    summary: L('Permit records on project workspace.', 'Proje alanında izin kayıtları.'),
    body: L(
      'Open the project, navigate to permits, upload or update status, then schedule inspection if required.',
      'Projeyi açın, izinlere gidin, yükleyin veya durumu güncelleyin, gerekirse denetim planlayın.',
    ),
    category: 'Projects',
    contentType: 'faq',
    roles: ['construction_ops', 'project_manager', 'admin'],
    workspaces: ['projects'],
    relatedRoutes: ['/dashboard/projects'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Construction',
  },
  {
    id: 'help-attribution',
    title: L('Explain attribution', 'Atıfı açıkla'),
    summary: L('Campaign to qualified lead.', 'Kampanyadan nitelikli leade.'),
    body: L(
      'Attribution connects campaigns and channels to lead quality and ROI. Untracked traffic is labeled separately.',
      'Atıf, kampanya ve kanalları lead kalitesi ve ROI ile bağlar. İzlenmeyen trafik ayrı etiketlenir.',
    ),
    category: 'Marketing',
    contentType: 'article',
    roles: ['marketing', 'admin'],
    workspaces: ['marketing'],
    relatedRoutes: ['/workspaces/marketing'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Marketing',
  },
  {
    id: 'help-ai',
    title: L('Reviewing AI recommendations', 'YZ önerilerini inceleme'),
    summary: L('Accept, dismiss, and log decisions.', 'Kabul, red ve karar kaydı.'),
    body: L(
      'Treat AI suggestions as decision support. Always verify before acting on financial or investor records.',
      'YZ önerilerini karar desteği olarak ele alın. Finans veya yatırımcı kayıtlarında işlemden önce doğrulayın.',
    ),
    category: 'AI',
    contentType: 'article',
    roles: ['ceo', 'admin', 'operations'],
    workspaces: ['ai'],
    relatedRoutes: ['/dashboard/ai'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'AI',
  },
  {
    id: 'help-admin-users',
    title: L('Create users and assign roles', 'Kullanıcı oluşturma ve rol atama'),
    summary: L('Admin onboarding without permission self-service.', 'İzin self-servisi olmadan yönetici oryantasyonu.'),
    body: L(
      'Admins create users and assign roles. Users never configure their own permissions.',
      'Yöneticiler kullanıcı oluşturur ve rol atar. Kullanıcılar kendi izinlerini yapılandırmaz.',
    ),
    category: 'Admin',
    contentType: 'role_guide',
    roles: ['admin'],
    workspaces: ['admin'],
    relatedRoutes: ['/dashboard/admin/users'],
    adminOnly: true,
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Admin',
  },
  {
    id: 'help-support',
    title: L('How support escalation works', 'Destek yükseltmesi nasıl çalışır'),
    summary: L('Categories, severity, SLA.', 'Kategoriler, ciddiyet, SLA.'),
    body: L(
      'Open an in-product support request with route, severity, and evidence. Security issues escalate immediately.',
      'Rota, ciddiyet ve kanıtla ürün içi destek talebi açın. Güvenlik sorunları hemen yükseltilir.',
    ),
    category: 'Operations',
    contentType: 'article',
    roles: ['*'],
    workspaces: ['support'],
    relatedRoutes: ['/dashboard/help'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Operations',
  },
  {
    id: 'help-contract',
    title: L('Contract processing overview', 'Sözleşme süreci özeti'),
    summary: L('From reservation to signature readiness.', 'Rezervasyondan imza hazırlığına.'),
    body: L('Collect documents, draft, legal review, then prepare signature. Training never executes real contracts.', 'Belgeleri toplayın, taslak, hukuk incelemesi, sonra imza. Eğitim gerçek sözleşme yürütmez.'),
    category: 'Investors',
    contentType: 'quick_reference',
    roles: ['investor_relations', 'admin'],
    workspaces: ['investors'],
    relatedRoutes: ['/dashboard/investors'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'IR',
  },
  {
    id: 'help-closing',
    title: L('Closing preparation', 'Kapanış hazırlığı'),
    summary: L('Funds, contingencies, status.', 'Fonlar, koşullar, durum.'),
    body: L('Verify funds and clear contingencies before closing status updates.', 'Kapanış durumu güncellemeden önce fonları ve koşulları doğrulayın.'),
    category: 'Investors',
    contentType: 'article',
    roles: ['investor_relations', 'finance', 'admin'],
    workspaces: ['investors', 'finance'],
    relatedRoutes: ['/dashboard/investors'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'IR',
  },
  {
    id: 'help-portal-portfolio',
    title: L('Understanding your portfolio', 'Portföyünüzü anlama'),
    summary: L('Client-facing portfolio help.', 'Müşteriye dönük portföy yardımı.'),
    body: L('Your portfolio shows projects, payments, and documents shared with you.', 'Portföyünüz sizinle paylaşılan projeleri, ödemeleri ve belgeleri gösterir.'),
    category: 'Portal',
    contentType: 'article',
    roles: ['portal_investor'],
    workspaces: ['portal'],
    relatedRoutes: ['/portal/portfolio', '/portal/help'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Portal',
  },
  {
    id: 'help-documents',
    title: L('Document upload and review', 'Belge yükleme ve inceleme'),
    summary: L('Classification and permissions.', 'Sınıflandırma ve izinler.'),
    body: L('Upload, classify, and request review. Blocked documents show a clear reason.', 'Yükleyin, sınıflandırın ve inceleme isteyin. Engellenen belgeler net neden gösterir.'),
    category: 'Operations',
    contentType: 'article',
    roles: ['*'],
    workspaces: ['documents'],
    relatedRoutes: ['/dashboard/knowledge'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Knowledge',
  },
  {
    id: 'help-meetings',
    title: L('Meeting prep and follow-up', 'Toplantı hazırlığı ve takip'),
    summary: L('Briefs, notes, tasks.', 'Özetler, notlar, görevler.'),
    body: L('Attach a brief, capture notes, and create follow-up tasks after meetings.', 'Özet ekleyin, not alın ve toplantı sonrası takip görevleri oluşturun.'),
    category: 'Executive',
    contentType: 'quick_reference',
    roles: ['executive_assistant', 'ceo', 'investor_relations', 'admin'],
    workspaces: ['executive'],
    relatedRoutes: ['/dashboard'],
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'EA',
  },
  {
    id: 'help-admin-security',
    title: L('Security incident routing', 'Güvenlik olayı yönlendirme'),
    summary: L('Admin-only escalation path.', 'Yalnızca yönetici yükseltme yolu.'),
    body: L('Security support routes to the security escalation process immediately.', 'Güvenlik destekleri derhal güvenlik yükseltme sürecine gider.'),
    category: 'Security',
    contentType: 'policy',
    roles: ['admin'],
    workspaces: ['admin'],
    relatedRoutes: ['/dashboard/admin/incidents'],
    adminOnly: true,
    version: '1.0.0',
    status: 'published',
    lastUpdated: '2026-07-20',
    owner: 'Security',
  },
];

export const PLAYBOOKS: Playbook[] = [
  'New Lead Response',
  'Investor Onboarding',
  'Reservation Processing',
  'Contract Processing',
  'Payment Reconciliation',
  'Closing Preparation',
  'Project Kickoff',
  'Permit Delay',
  'Inspection Failure',
  'Budget Overrun',
  'Contractor Delay',
  'Campaign Launch',
  'Campaign Underperformance',
  'Missing Document',
  'User Access Request',
  'Security Incident',
  'Data Correction',
  'System Outage',
  'AI Provider Failure',
].map((title, i) => {
  const id = `pb-${i + 1}`;
  const trTitles = [
    'Yeni Lead Yanıtı',
    'Yatırımcı Oryantasyonu',
    'Rezervasyon İşleme',
    'Sözleşme İşleme',
    'Ödeme Mutabakatı',
    'Kapanış Hazırlığı',
    'Proje Başlatma',
    'İzin Gecikmesi',
    'Denetim Başarısızlığı',
    'Bütçe Aşımı',
    'Yüklenici Gecikmesi',
    'Kampanya Lansmanı',
    'Kampanya Düşük Performans',
    'Eksik Belge',
    'Kullanıcı Erişim Talebi',
    'Güvenlik Olayı',
    'Veri Düzeltme',
    'Sistem Kesintisi',
    'YZ Sağlayıcı Arızası',
  ];
  const roles: AdoptionRoleId[] = [
    'sales_rep',
    'investor_relations',
    'investor_relations',
    'investor_relations',
    'finance',
    'investor_relations',
    'project_manager',
    'construction_ops',
    'construction_ops',
    'project_manager',
    'construction_ops',
    'marketing',
    'marketing',
    'operations',
    'admin',
    'admin',
    'operations',
    'admin',
    'admin',
  ];
  const slaIds = [
    'sla-lead',
    'sla-investor-followup',
    'sla-contract',
    'sla-contract',
    'sla-wire',
    'sla-contract',
    'sla-issue',
    'sla-permit',
    'sla-inspection',
    'sla-issue',
    'sla-issue',
    'sla-lead',
    'sla-lead',
    'sla-document',
    'sla-support',
    'sla-security',
    'sla-support',
    'sla-support',
    'sla-support',
  ];
  const trTitle = trTitles[i] ?? title;
  const role = roles[i] ?? 'operations';
  const slaId = slaIds[i] ?? 'sla-support';
  return {
    id,
    title: L(title, trTitle),
    trigger: L(`Triggered when ${title.toLowerCase()} conditions occur.`, `${trTitle} koşulları oluştuğunda tetiklenir.`),
    responsibleRole: role,
    steps: [
      L('Confirm trigger and severity', 'Tetikleyici ve ciddiyeti doğrula'),
      L('Execute required operational steps', 'Gerekli operasyon adımlarını uygula'),
      L('Capture evidence', 'Kanıt topla'),
      L('Close or escalate per SLA', 'SLA’ya göre kapat veya yükselt'),
    ],
    slaId,
    escalationPath: L('Owner → Manager → Operations / Security', 'Sahip → Yönetici → Operasyon / Güvenlik'),
    requiredEvidence: [L('Timestamped notes', 'Zaman damgalı notlar'), L('Related record link', 'İlgili kayıt bağlantısı')],
    completionCriteria: L('All steps done and SLA status resolved', 'Tüm adımlar tamam ve SLA çözüldü'),
    auditRequirements: L('Retain activity in audit log', 'Aktiviteyi denetim kaydında tut'),
    version: '1.0.0',
    status: 'published',
  };
});

export const SLAS: SlaDefinition[] = [
  { id: 'sla-lead', title: L('New lead first response', 'Yeni lead ilk yanıt'), event: L('Lead created', 'Lead oluşturuldu'), ownerRole: 'sales_rep', responseTargetMinutes: 30, resolutionTargetHours: 8, severity: 'high', escalationThresholdMinutes: 60, escalationRecipient: L('Sales Manager', 'Satış Müdürü'), notificationBehavior: L('In-app + email preference', 'Uygulama içi + e-posta tercihi'), businessHours: true, timezone: 'Europe/Istanbul', linkedAutomation: 'automation-center' },
  { id: 'sla-investor-followup', title: L('Investor follow-up', 'Yatırımcı takibi'), event: L('Follow-up due', 'Takip vadesi'), ownerRole: 'investor_relations', responseTargetMinutes: 240, resolutionTargetHours: 48, severity: 'medium', escalationThresholdMinutes: 480, escalationRecipient: L('IR Manager', 'Yİ Müdürü'), notificationBehavior: L('In-app', 'Uygulama içi'), businessHours: true, timezone: 'Europe/Istanbul', linkedAutomation: 'automation-center' },
  { id: 'sla-payment', title: L('Payment approval', 'Ödeme onayı'), event: L('Payment pending approval', 'Ödeme onay bekliyor'), ownerRole: 'finance', responseTargetMinutes: 120, resolutionTargetHours: 24, severity: 'high', escalationThresholdMinutes: 240, escalationRecipient: L('CFO', 'CFO'), notificationBehavior: L('In-app + urgent', 'Uygulama içi + acil'), businessHours: true, timezone: 'Europe/Istanbul', linkedAutomation: 'automation-center' },
  { id: 'sla-wire', title: L('Wire reconciliation', 'Havale mutabakatı'), event: L('Unmatched wire', 'Eşleşmeyen havale'), ownerRole: 'finance', responseTargetMinutes: 180, resolutionTargetHours: 24, severity: 'high', escalationThresholdMinutes: 360, escalationRecipient: L('CFO', 'CFO'), notificationBehavior: L('In-app', 'Uygulama içi'), businessHours: true, timezone: 'Europe/Istanbul', linkedAutomation: 'automation-center' },
  { id: 'sla-document', title: L('Document review', 'Belge incelemesi'), event: L('Document submitted', 'Belge gönderildi'), ownerRole: 'operations', responseTargetMinutes: 480, resolutionTargetHours: 72, severity: 'medium', escalationThresholdMinutes: 1440, escalationRecipient: L('Operations', 'Operasyon'), notificationBehavior: L('In-app', 'Uygulama içi'), businessHours: true, timezone: 'Europe/Istanbul' },
  { id: 'sla-contract', title: L('Contract review', 'Sözleşme incelemesi'), event: L('Contract draft ready', 'Sözleşme taslağı hazır'), ownerRole: 'investor_relations', responseTargetMinutes: 480, resolutionTargetHours: 96, severity: 'medium', escalationThresholdMinutes: 1440, escalationRecipient: L('Legal / IR Manager', 'Hukuk / Yİ Müdürü'), notificationBehavior: L('In-app', 'Uygulama içi'), businessHours: true, timezone: 'Europe/Istanbul' },
  { id: 'sla-issue', title: L('Critical issue response', 'Kritik sorun yanıtı'), event: L('Critical issue opened', 'Kritik sorun açıldı'), ownerRole: 'project_manager', responseTargetMinutes: 60, resolutionTargetHours: 24, severity: 'critical', escalationThresholdMinutes: 120, escalationRecipient: L('Construction Ops Lead', 'Şantiye Operasyon Lideri'), notificationBehavior: L('In-app + urgent', 'Uygulama içi + acil'), businessHours: false, timezone: 'Europe/Istanbul', linkedAutomation: 'automation-center' },
  { id: 'sla-permit', title: L('Permit escalation', 'İzin yükseltmesi'), event: L('Permit delayed', 'İzin gecikti'), ownerRole: 'construction_ops', responseTargetMinutes: 240, resolutionTargetHours: 72, severity: 'high', escalationThresholdMinutes: 480, escalationRecipient: L('Project Manager', 'Proje Yöneticisi'), notificationBehavior: L('In-app', 'Uygulama içi'), businessHours: true, timezone: 'Europe/Istanbul' },
  { id: 'sla-inspection', title: L('Inspection failure response', 'Denetim başarısızlığı yanıtı'), event: L('Inspection failed', 'Denetim başarısız'), ownerRole: 'construction_ops', responseTargetMinutes: 120, resolutionTargetHours: 48, severity: 'high', escalationThresholdMinutes: 240, escalationRecipient: L('Project Manager', 'Proje Yöneticisi'), notificationBehavior: L('In-app + urgent', 'Uygulama içi + acil'), businessHours: true, timezone: 'Europe/Istanbul' },
  { id: 'sla-support', title: L('Support request', 'Destek talebi'), event: L('Support created', 'Destek oluşturuldu'), ownerRole: 'operations', responseTargetMinutes: 240, resolutionTargetHours: 72, severity: 'medium', escalationThresholdMinutes: 480, escalationRecipient: L('Operations Lead', 'Operasyon Lideri'), notificationBehavior: L('In-app', 'Uygulama içi'), businessHours: true, timezone: 'Europe/Istanbul', linkedAutomation: 'automation-center' },
  { id: 'sla-security', title: L('Security incident', 'Güvenlik olayı'), event: L('Security support opened', 'Güvenlik desteği açıldı'), ownerRole: 'admin', responseTargetMinutes: 15, resolutionTargetHours: 8, severity: 'critical', escalationThresholdMinutes: 30, escalationRecipient: L('Security On-call', 'Güvenlik Nöbeti'), notificationBehavior: L('Immediate escalation', 'Anında yükseltme'), businessHours: false, timezone: 'Europe/Istanbul', linkedAutomation: 'automation-center' },
];

export const KNOWLEDGE_CHECKS: KnowledgeCheck[] = [
  {
    id: 'kc-ceo',
    title: L('CEO knowledge check', 'CEO bilgi kontrolü'),
    roleId: 'ceo',
    passScore: 70,
    version: '1.0.0',
    status: 'published',
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        prompt: L('Where do you start the day as CEO?', 'CEO olarak güne nereden başlarsınız?'),
        options: [
          L('Executive priorities', 'Yönetici öncelikleri'),
          L('Training builder', 'Eğitim oluşturucu'),
          L('Design system', 'Tasarım sistemi'),
        ],
        correctIndex: 0,
        explanation: L('Start with critical priorities on the executive dashboard.', 'Yönetici panelindeki kritik önceliklerle başlayın.'),
      },
      {
        id: 'q2',
        type: 'true_false',
        prompt: L('AI recommendations should be verified before action.', 'YZ önerileri işlemden önce doğrulanmalıdır.'),
        options: [L('True', 'Doğru'), L('False', 'Yanlış')],
        correctIndex: 0,
        explanation: L('AI is decision support, not automatic authority.', 'YZ karar desteğidir, otomatik yetki değildir.'),
      },
    ],
  },
  {
    id: 'kc-sales',
    title: L('Sales knowledge check', 'Satış bilgi kontrolü'),
    roleId: 'sales_rep',
    passScore: 70,
    version: '1.0.0',
    status: 'published',
    questions: [
      {
        id: 'q1',
        type: 'scenario',
        prompt: L('A lead looks duplicated. What first?', 'Lead yinelenmiş görünüyor. İlk ne yaparsınız?'),
        options: [
          L('Review match candidates', 'Eşleşme adaylarını incele'),
          L('Create another lead immediately', 'Hemen yeni lead oluştur'),
          L('Delete production data', 'Üretim verisini sil'),
        ],
        correctIndex: 0,
        explanation: L('Check duplicates before creating records.', 'Kayıt oluşturmadan önce yinelenenleri kontrol edin.'),
      },
    ],
  },
  {
    id: 'kc-finance',
    title: L('Finance knowledge check', 'Finans bilgi kontrolü'),
    roleId: 'finance',
    passScore: 80,
    version: '1.0.0',
    status: 'published',
    questions: [
      {
        id: 'q1',
        type: 'identify_action',
        prompt: L('In training mode, posting a live payment is:', 'Eğitim modunda canlı ödeme kaydı:'),
        options: [
          L('Blocked', 'Engellenir'),
          L('Allowed if demo user', 'Demo kullanıcıysa izinli'),
          L('Silent', 'Sessizce yapılır'),
        ],
        correctIndex: 0,
        explanation: L('Simulation isolates real financial posting.', 'Simülasyon gerçek finansal kaydı izole eder.'),
      },
    ],
  },
  {
    id: 'kc-ir',
    title: L('IR knowledge check', 'Yİ bilgi kontrolü'),
    roleId: 'investor_relations',
    passScore: 70,
    version: '1.0.0',
    status: 'published',
    questions: [
      {
        id: 'q1',
        type: 'true_false',
        prompt: L('Portal invites send real investor emails in training mode.', 'Eğitim modunda portal davetleri gerçek yatırımcı e-postası gönderir.'),
        options: [L('True', 'Doğru'), L('False', 'Yanlış')],
        correctIndex: 1,
        explanation: L('Training mode blocks real investor notifications.', 'Eğitim modu gerçek yatırımcı bildirimlerini engeller.'),
      },
    ],
  },
  {
    id: 'kc-marketing',
    title: L('Marketing knowledge check', 'Pazarlama bilgi kontrolü'),
    roleId: 'marketing',
    passScore: 70,
    version: '1.0.0',
    status: 'published',
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        prompt: L('Campaign publish in training mode is:', 'Eğitim modunda kampanya yayını:'),
        options: [L('Blocked', 'Engellenir'), L('Live', 'Canlı'), L('Queued to production', 'Üretime kuyruklanır')],
        correctIndex: 0,
        explanation: L('Never publish real campaigns from simulations.', 'Simülasyondan gerçek kampanya yayınlamayın.'),
      },
    ],
  },
  {
    id: 'kc-admin',
    title: L('Admin knowledge check', 'Yönetici bilgi kontrolü'),
    roleId: 'admin',
    passScore: 80,
    version: '1.0.0',
    status: 'published',
    questions: [
      {
        id: 'q1',
        type: 'true_false',
        prompt: L('Broken tour selectors can still be published.', 'Bozuk tur seçicileri yine de yayınlanabilir.'),
        options: [L('True', 'Doğru'), L('False', 'Yanlış')],
        correctIndex: 1,
        explanation: L('Training builder blocks publish when selectors are missing.', 'Eğitim oluşturucu eksik seçicilerde yayını engeller.'),
      },
    ],
  },
];

export const CERTIFICATIONS: Certification[] = [
  { id: 'cert-crm', title: L('CRM Certified', 'CRM Sertifikalı'), roleIds: ['sales_rep', 'sales_manager'], requiredModuleIds: ['sr-m1', 'sr-m3'], requiredSimulationId: 'sim-create-lead', requiredKnowledgeCheckId: 'kc-sales', managerApprovalRequired: true, renewalMonths: 12, version: '1.0.0', status: 'published' },
  { id: 'cert-ir', title: L('Investor Operations Certified', 'Yatırımcı Operasyonları Sertifikalı'), roleIds: ['investor_relations'], requiredModuleIds: ['ir-m1', 'ir-m3'], requiredSimulationId: 'sim-reservation', requiredKnowledgeCheckId: 'kc-ir', managerApprovalRequired: true, renewalMonths: 12, version: '1.0.0', status: 'published' },
  { id: 'cert-finance', title: L('Finance Operations Certified', 'Finans Operasyonları Sertifikalı'), roleIds: ['finance', 'cfo'], requiredModuleIds: ['fin-m1', 'fin-m2'], requiredSimulationId: 'sim-payment', requiredKnowledgeCheckId: 'kc-finance', managerApprovalRequired: true, renewalMonths: 12, version: '1.0.0', status: 'published' },
  { id: 'cert-projects', title: L('Project Operations Certified', 'Proje Operasyonları Sertifikalı'), roleIds: ['project_manager', 'construction_ops'], requiredModuleIds: ['pm-m1', 'pm-m3'], managerApprovalRequired: false, renewalMonths: 12, version: '1.0.0', status: 'published' },
  { id: 'cert-marketing', title: L('Marketing Operations Certified', 'Pazarlama Operasyonları Sertifikalı'), roleIds: ['marketing'], requiredModuleIds: ['mkt-m1', 'mkt-m3'], requiredKnowledgeCheckId: 'kc-marketing', managerApprovalRequired: false, renewalMonths: 12, version: '1.0.0', status: 'published' },
  { id: 'cert-admin', title: L('Admin Certified', 'Yönetici Sertifikalı'), roleIds: ['admin'], requiredModuleIds: ['adm-m1', 'adm-m2', 'adm-m3'], requiredKnowledgeCheckId: 'kc-admin', managerApprovalRequired: true, renewalMonths: 12, version: '1.0.0', status: 'published' },
];

export const SIMULATIONS: SimulationScenario[] = [
  {
    id: 'sim-create-lead',
    title: L('Create lead (training)', 'Lead oluştur (eğitim)'),
    description: L('Practice lead creation with TRAINING DATA labels.', 'TRAINING DATA etiketleriyle lead oluşturmayı deneyin.'),
    roleId: 'sales_rep',
    steps: [
      L('Enter training mode', 'Eğitim moduna gir'),
      L('Create TEST lead', 'TEST lead oluştur'),
      L('Confirm no real emails sent', 'Gerçek e-posta gitmediğini doğrula'),
    ],
    labels: ['TRAINING DATA', 'DEMO USER'],
    blocksRealActions: true,
  },
  {
    id: 'sim-reservation',
    title: L('Create reservation (training)', 'Rezervasyon oluştur (eğitim)'),
    description: L('TEST INVESTOR reservation without live notify.', 'Canlı bildirim olmadan TEST YATIRIMCI rezervasyonu.'),
    roleId: 'investor_relations',
    steps: [
      L('Enter training mode', 'Eğitim moduna gir'),
      L('Select TEST PROJECT unit', 'TEST PROJE birimini seç'),
      L('Confirm investor notify blocked', 'Yatırımcı bildiriminin engellendiğini doğrula'),
    ],
    labels: ['TRAINING DATA', 'TEST INVESTOR', 'TEST PROJECT'],
    blocksRealActions: true,
  },
  {
    id: 'sim-payment',
    title: L('Record payment (training)', 'Ödeme kaydet (eğitim)'),
    description: L('TEST PAYMENT with posting blocked.', 'Kayıt engelli TEST ÖDEME.'),
    roleId: 'finance',
    steps: [
      L('Enter training mode', 'Eğitim moduna gir'),
      L('Attempt payment post', 'Ödeme kaydı dene'),
      L('Observe block reason', 'Engel nedenini gör'),
    ],
    labels: ['TRAINING DATA', 'TEST PAYMENT'],
    blocksRealActions: true,
  },
  {
    id: 'sim-campaign',
    title: L('Create campaign (training)', 'Kampanya oluştur (eğitim)'),
    description: L('Draft campaign; publish blocked.', 'Kampanya taslağı; yayın engelli.'),
    roleId: 'marketing',
    steps: [
      L('Enter training mode', 'Eğitim moduna gir'),
      L('Draft campaign', 'Kampanya taslağı'),
      L('Confirm publish blocked', 'Yayının engellendiğini doğrula'),
    ],
    labels: ['TRAINING DATA'],
    blocksRealActions: true,
  },
];

export const CONTEXTUAL_GUIDANCE: ContextualGuidance[] = [
  {
    id: 'guide-lead',
    routePattern: '/workspaces/crm/leads',
    title: L('Lead detail guidance', 'Lead detay rehberi'),
    tips: [
      L('Explain qualification criteria before stage change.', 'Aşama değişiminden önce niteleme kriterlerini açıklayın.'),
      L('Check duplicates before creating contacts.', 'Kişi oluşturmadan önce yinelenenleri kontrol edin.'),
      L('Next action should be scheduled when leaving the record.', 'Kayıttan çıkarken sonraki aksiyon planlanmalı.'),
    ],
    pattern: 'side_panel',
  },
  {
    id: 'guide-investor',
    routePattern: '/dashboard/investors',
    title: L('Investor profile guidance', 'Yatırımcı profil rehberi'),
    tips: [
      L('Capture investment preferences early.', 'Yatırım tercihlerini erken kaydedin.'),
      L('KYC status gates portal invitation.', 'KYC durumu portal davetini belirler.'),
      L('Payment state should match finance records.', 'Ödeme durumu finans kayıtlarıyla uyumlu olmalı.'),
    ],
    pattern: 'info_panel',
  },
  {
    id: 'guide-budget',
    routePattern: '/dashboard/projects',
    title: L('Project budget guidance', 'Proje bütçe rehberi'),
    tips: [
      L('Compare planned vs actual before change orders.', 'Değişiklik emrinden önce planlanan/gerçekleşeni karşılaştırın.'),
      L('Forecast at completion informs approvals.', 'Tamamlanma tahmini onayları bilgilendirir.'),
    ],
    pattern: 'inline_warning',
  },
  {
    id: 'guide-finance',
    routePattern: '/dashboard/finance',
    title: L('Finance guidance', 'Finans rehberi'),
    tips: [
      L('Reconcile before approving outbound payments.', 'Giden ödemeleri onaylamadan önce mutabakat yapın.'),
      L('Restricted cash is not available for discretionary spend.', 'Kısıtlı nakit serbest harcama için kullanılamaz.'),
    ],
    pattern: 'info_panel',
  },
  {
    id: 'guide-marketing',
    routePattern: '/workspaces/marketing',
    title: L('Marketing guidance', 'Pazarlama rehberi'),
    tips: [
      L('Attribution explains which campaigns produce qualified leads.', 'Atıf hangi kampanyaların nitelikli lead ürettiğini gösterir.'),
      L('Investigate untracked traffic before scaling spend.', 'Harcama artırmadan önce izlenmeyen trafiği araştırın.'),
    ],
    pattern: 'tooltip',
  },
];

export const CAPABILITY_AUDIT: CapabilityAuditItem[] = [
  { id: 'roles', name: 'User roles', status: 'LIVE', notes: 'RBAC seed + API SoT' },
  { id: 'permissions', name: 'Permissions', status: 'LIVE', notes: 'resource:action enforcement' },
  { id: 'preferences', name: 'User preferences', status: 'PARTIAL', notes: 'Language/timezone confirmed in onboarding UI; API preference patch limited' },
  { id: 'notifications', name: 'Notifications', status: 'PARTIAL', notes: 'Training event notifications stored locally; prefer existing prefs' },
  { id: 'activity', name: 'Activity logs', status: 'LIVE', notes: 'Existing activity module' },
  { id: 'tasks', name: 'Task system', status: 'PARTIAL', notes: 'Domain tasks exist; training checklists local' },
  { id: 'automation', name: 'Automation / SLA engine', status: 'LIVE', notes: 'Reuse Automation Center; G13 links SLAs, does not duplicate engine' },
  { id: 'help', name: 'Help content', status: 'DEMO', notes: 'In-product catalog shipped for G13' },
  { id: 'tours', name: 'Product tours', status: 'DEMO', notes: 'Tour engine + stable data-tour selectors' },
  { id: 'feature-flags', name: 'Feature flags', status: 'NOT CONFIGURED', notes: 'No dedicated flag service wired for training' },
  { id: 'analytics', name: 'Adoption analytics', status: 'DEMO', notes: 'Dashboard KPIs use demo aggregates + local progress' },
  { id: 'support', name: 'Support system', status: 'PARTIAL', notes: 'In-product intake; ops routing demo' },
  { id: 'release-notes', name: 'Release notes', status: 'PARTIAL', notes: 'Content type supported in library' },
  { id: 'i18n', name: 'Localization', status: 'LIVE', notes: 'tr/en via next-intl + bilingual content' },
  { id: 'portal-perms', name: 'Portal permissions', status: 'LIVE', notes: 'Portal session isolation' },
];

export const ADOPTION_KPI_DEMO = {
  invitedUsers: 42,
  activatedUsers: 36,
  activeUsers: 28,
  onboardingStarted: 34,
  onboardingCompleted: 22,
  overdueTraining: 5,
  avgCompletionDays: 6.4,
  dau: 18,
  wau: 31,
  trainingCompletionRate: 0.68,
  workflowSuccessRate: 0.81,
  helpSearches: 146,
  unresolvedHelpSearches: 11,
  supportRequests: 9,
  checklistCompletion: 0.74,
  activationTrend: [12, 15, 18, 21, 24, 28, 31, 34, 36],
  trainingTrend: [0.2, 0.28, 0.35, 0.42, 0.5, 0.55, 0.61, 0.65, 0.68],
  activeTrend: [10, 12, 14, 16, 17, 19, 22, 25, 28],
  featureAdoption: [
    { name: 'Executive', access: 8, opened: 7, acted: 6, pct: 0.75 },
    { name: 'CRM', access: 14, opened: 13, acted: 11, pct: 0.79 },
    { name: 'Investors', access: 9, opened: 8, acted: 7, pct: 0.78 },
    { name: 'Projects', access: 11, opened: 10, acted: 8, pct: 0.73 },
    { name: 'Finance', access: 7, opened: 7, acted: 6, pct: 0.86 },
    { name: 'Marketing', access: 6, opened: 5, acted: 4, pct: 0.67 },
    { name: 'AI', access: 10, opened: 8, acted: 5, pct: 0.5 },
    { name: 'Documents', access: 20, opened: 16, acted: 12, pct: 0.6 },
    { name: 'Meetings', access: 18, opened: 12, acted: 9, pct: 0.5 },
    { name: 'Portal', access: 40, opened: 32, acted: 24, pct: 0.6 },
    { name: 'Reports', access: 15, opened: 10, acted: 7, pct: 0.47 },
    { name: 'Search', access: 36, opened: 30, acted: 22, pct: 0.61 },
    { name: 'Notifications', access: 36, opened: 28, acted: 18, pct: 0.5 },
    { name: 'Approvals', access: 12, opened: 11, acted: 9, pct: 0.75 },
  ],
  completionByRole: [
    { role: 'CEO', pct: 0.72 },
    { role: 'Sales', pct: 0.8 },
    { role: 'IR', pct: 0.65 },
    { role: 'Finance', pct: 0.7 },
    { role: 'Marketing', pct: 0.58 },
    { role: 'Admin', pct: 0.88 },
  ],
};
