import { L } from '../locale';
import type { OperationalChecklist } from '../types';

function item(
  id: string,
  role: OperationalChecklist['roleId'],
  en: string,
  tr: string,
  ws: string,
) {
  return {
    id,
    title: L(en, tr),
    description: L(`${en} — complete with evidence.`, `${tr} — kanıtla tamamlayın.`),
    ownerRole: role,
    relatedWorkspace: ws,
    completionCriteria: L('Marked done with optional note', 'Opsiyonel notla tamamlandı'),
    escalationRule: L('Escalate to manager after 1 missed cycle', '1 kaçırılan döngü sonrası yöneticiye yükselt'),
  };
}

export const CHECKLISTS: OperationalChecklist[] = [
  {
    id: 'daily-ceo',
    cadence: 'daily',
    roleId: 'ceo',
    title: L('CEO Daily Checklist', 'CEO Günlük Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('d-ceo-1', 'ceo', 'Review critical priorities', 'Kritik öncelikleri incele', 'executive'),
      item('d-ceo-2', 'ceo', 'Review cash position', 'Nakit durumunu incele', 'finance'),
      item('d-ceo-3', 'ceo', 'Review pending approvals', 'Bekleyen onayları incele', 'executive'),
      item('d-ceo-4', 'ceo', 'Review investor closings', 'Yatırımcı kapanışlarını incele', 'investors'),
      item('d-ceo-5', 'ceo', 'Review project risks', 'Proje risklerini incele', 'projects'),
      item('d-ceo-6', 'ceo', 'Review AI recommendations', 'YZ önerilerini incele', 'ai'),
    ],
  },
  {
    id: 'daily-cfo',
    cadence: 'daily',
    roleId: 'cfo',
    title: L('CFO Daily Checklist', 'CFO Günlük Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('d-cfo-1', 'cfo', 'Review bank balances', 'Banka bakiyelerini incele', 'finance'),
      item('d-cfo-2', 'cfo', 'Review incoming wires', 'Gelen havaleleri incele', 'finance'),
      item('d-cfo-3', 'cfo', 'Review outgoing payments', 'Giden ödemeleri incele', 'finance'),
      item('d-cfo-4', 'cfo', 'Review overdue receivables', 'Vadesi geçmiş alacakları incele', 'finance'),
      item('d-cfo-5', 'cfo', 'Review queue failures', 'Kuyruk hatalarını incele', 'automation'),
      item('d-cfo-6', 'cfo', 'Review reconciliation exceptions', 'Mutabakat istisnalarını incele', 'finance'),
    ],
  },
  {
    id: 'daily-sales',
    cadence: 'daily',
    roleId: 'sales_rep',
    title: L('Sales Daily Checklist', 'Satış Günlük Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('d-sal-1', 'sales_rep', 'Review assigned leads', 'Atanan leadleri incele', 'crm'),
      item('d-sal-2', 'sales_rep', 'Complete overdue follow-ups', 'Gecikmiş takipleri tamamla', 'crm'),
      item('d-sal-3', 'sales_rep', 'Update opportunity stages', 'Fırsat aşamalarını güncelle', 'crm'),
      item('d-sal-4', 'sales_rep', 'Schedule next actions', 'Sonraki aksiyonları planla', 'crm'),
      item('d-sal-5', 'sales_rep', 'Close completed tasks', 'Tamamlanan görevleri kapat', 'crm'),
      item('d-sal-6', 'sales_rep', 'Review stalled opportunities', 'Duran fırsatları incele', 'crm'),
    ],
  },
  {
    id: 'daily-ir',
    cadence: 'daily',
    roleId: 'investor_relations',
    title: L('IR Daily Checklist', 'Yİ Günlük Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('d-ir-1', 'investor_relations', 'Review investor follow-ups', 'Yatırımcı takiplerini incele', 'investors'),
      item('d-ir-2', 'investor_relations', 'Review missing documents', 'Eksik belgeleri incele', 'documents'),
      item('d-ir-3', 'investor_relations', 'Review payment status', 'Ödeme durumunu incele', 'finance'),
      item('d-ir-4', 'investor_relations', 'Prepare meetings', 'Toplantıları hazırla', 'investors'),
      item('d-ir-5', 'investor_relations', 'Update investor timeline', 'Yatırımcı zaman çizelgesini güncelle', 'investors'),
      item('d-ir-6', 'investor_relations', 'Review portal messages', 'Portal mesajlarını incele', 'portal'),
    ],
  },
  {
    id: 'daily-pm',
    cadence: 'daily',
    roleId: 'project_manager',
    title: L('PM Daily Checklist', 'PY Günlük Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('d-pm-1', 'project_manager', 'Review overdue tasks', 'Gecikmiş görevleri incele', 'projects'),
      item('d-pm-2', 'project_manager', 'Review critical issues', 'Kritik sorunları incele', 'projects'),
      item('d-pm-3', 'project_manager', 'Review upcoming inspections', 'Yaklaşan denetimleri incele', 'projects'),
      item('d-pm-4', 'project_manager', 'Review permit status', 'İzin durumunu incele', 'projects'),
      item('d-pm-5', 'project_manager', 'Update milestones', 'Kilometre taşlarını güncelle', 'projects'),
      item('d-pm-6', 'project_manager', 'Review contractor blockers', 'Yüklenici engellerini incele', 'projects'),
    ],
  },
  {
    id: 'daily-marketing',
    cadence: 'daily',
    roleId: 'marketing',
    title: L('Marketing Daily Checklist', 'Pazarlama Günlük Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('d-mkt-1', 'marketing', 'Review active campaigns', 'Aktif kampanyaları incele', 'marketing'),
      item('d-mkt-2', 'marketing', 'Review lead quality', 'Lead kalitesini incele', 'marketing'),
      item('d-mkt-3', 'marketing', 'Review spend anomalies', 'Harcama anomalilerini incele', 'marketing'),
      item('d-mkt-4', 'marketing', 'Review content schedule', 'İçerik takvimini incele', 'marketing'),
      item('d-mkt-5', 'marketing', 'Review website events', 'Web sitesi olaylarını incele', 'marketing'),
      item('d-mkt-6', 'marketing', 'Review campaign tasks', 'Kampanya görevlerini incele', 'marketing'),
    ],
  },
  {
    id: 'weekly-executive',
    cadence: 'weekly',
    roleId: 'ceo',
    title: L('Executive Weekly Checklist', 'Yönetici Haftalık Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('w-ex-1', 'ceo', 'Weekly business review', 'Haftalık iş incelemesi', 'executive'),
      item('w-ex-2', 'ceo', 'Cash forecast review', 'Nakit tahmin incelemesi', 'finance'),
      item('w-ex-3', 'ceo', 'Pipeline review', 'Pipeline incelemesi', 'crm'),
      item('w-ex-4', 'ceo', 'Project portfolio review', 'Proje portföy incelemesi', 'projects'),
      item('w-ex-5', 'ceo', 'Approval backlog review', 'Onay birikimi incelemesi', 'executive'),
      item('w-ex-6', 'ceo', 'Risk review', 'Risk incelemesi', 'projects'),
    ],
  },
  {
    id: 'weekly-sales',
    cadence: 'weekly',
    roleId: 'sales_manager',
    title: L('Sales Weekly Checklist', 'Satış Haftalık Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('w-sa-1', 'sales_manager', 'Pipeline hygiene', 'Pipeline hijyeni', 'crm'),
      item('w-sa-2', 'sales_manager', 'Inactive lead review', 'Pasif lead incelemesi', 'crm'),
      item('w-sa-3', 'sales_manager', 'Stage duration review', 'Aşama süresi incelemesi', 'crm'),
      item('w-sa-4', 'sales_manager', 'Opportunity forecast', 'Fırsat tahmini', 'crm'),
      item('w-sa-5', 'sales_manager', 'Lost-reason review', 'Kayıp nedeni incelemesi', 'crm'),
      item('w-sa-6', 'sales_manager', 'Meeting completion review', 'Toplantı tamamlanma incelemesi', 'crm'),
    ],
  },
  {
    id: 'weekly-finance',
    cadence: 'weekly',
    roleId: 'finance',
    title: L('Finance Weekly Checklist', 'Finans Haftalık Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('w-fi-1', 'finance', 'Bank reconciliation', 'Banka mutabakatı', 'finance'),
      item('w-fi-2', 'finance', 'Receivable aging', 'Alacak yaşlandırması', 'finance'),
      item('w-fi-3', 'finance', 'Payable schedule', 'Borç ödeme planı', 'finance'),
      item('w-fi-4', 'finance', 'Vendor payments', 'Tedarikçi ödemeleri', 'finance'),
      item('w-fi-5', 'finance', 'Project funding review', 'Proje fonlama incelemesi', 'finance'),
      item('w-fi-6', 'finance', 'Financial exception review', 'Finansal istisna incelemesi', 'finance'),
    ],
  },
  {
    id: 'weekly-projects',
    cadence: 'weekly',
    roleId: 'project_manager',
    title: L('Projects Weekly Checklist', 'Projeler Haftalık Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('w-pr-1', 'project_manager', 'Milestone review', 'Kilometre taşı incelemesi', 'projects'),
      item('w-pr-2', 'project_manager', 'Budget variance review', 'Bütçe sapması incelemesi', 'projects'),
      item('w-pr-3', 'project_manager', 'Permit review', 'İzin incelemesi', 'projects'),
      item('w-pr-4', 'project_manager', 'Inspection review', 'Denetim incelemesi', 'projects'),
      item('w-pr-5', 'project_manager', 'Contractor performance review', 'Yüklenici performans incelemesi', 'projects'),
      item('w-pr-6', 'project_manager', 'Risk register update', 'Risk kaydı güncelleme', 'projects'),
    ],
  },
  {
    id: 'weekly-marketing',
    cadence: 'weekly',
    roleId: 'marketing',
    title: L('Marketing Weekly Checklist', 'Pazarlama Haftalık Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('w-mk-1', 'marketing', 'Campaign review', 'Kampanya incelemesi', 'marketing'),
      item('w-mk-2', 'marketing', 'Attribution review', 'Atıf incelemesi', 'marketing'),
      item('w-mk-3', 'marketing', 'SEO review', 'SEO incelemesi', 'marketing'),
      item('w-mk-4', 'marketing', 'Content performance', 'İçerik performansı', 'marketing'),
      item('w-mk-5', 'marketing', 'Funnel conversion', 'Huni dönüşümü', 'marketing'),
      item('w-mk-6', 'marketing', 'Marketing calendar review', 'Pazarlama takvimi incelemesi', 'marketing'),
    ],
  },
  {
    id: 'monthly-ops',
    cadence: 'monthly',
    roleId: 'operations',
    title: L('Monthly Operational Checklist', 'Aylık Operasyonel Kontrol Listesi'),
    version: '1.0.0',
    status: 'published',
    items: [
      item('m-1', 'operations', 'Financial close', 'Finansal kapanış', 'finance'),
      item('m-2', 'operations', 'Monthly reporting', 'Aylık raporlama', 'executive'),
      item('m-3', 'operations', 'Investor reporting', 'Yatırımcı raporlaması', 'investors'),
      item('m-4', 'operations', 'Project status reporting', 'Proje durum raporlaması', 'projects'),
      item('m-5', 'operations', 'Marketing performance reporting', 'Pazarlama performans raporlaması', 'marketing'),
      item('m-6', 'operations', 'Permission review', 'İzin incelemesi', 'admin'),
      item('m-7', 'operations', 'Inactive user review', 'Pasif kullanıcı incelemesi', 'admin'),
      item('m-8', 'operations', 'Integration health review', 'Entegrasyon sağlık incelemesi', 'automation'),
      item('m-9', 'operations', 'AI cost review', 'YZ maliyet incelemesi', 'ai'),
      item('m-10', 'operations', 'Training completion review', 'Eğitim tamamlanma incelemesi', 'training'),
      item('m-11', 'operations', 'Document retention review', 'Belge saklama incelemesi', 'documents'),
      item('m-12', 'operations', 'System health review', 'Sistem sağlık incelemesi', 'admin'),
    ],
  },
];
