import { L } from '../locale';
import type { LearningPath } from '../types';

export const LEARNING_PATHS: LearningPath[] = [
  {
    id: 'path-ceo',
    roleId: 'ceo',
    title: L('CEO Learning Path', 'CEO Öğrenme Yolu'),
    description: L(
      'Executive dashboard, priorities, approvals, and decision logging.',
      'Yönetici paneli, öncelikler, onaylar ve karar kaydı.',
    ),
    teachTopics: [
      L('Executive Dashboard', 'Yönetici Paneli'),
      L("Today's Priorities", 'Günün Öncelikleri'),
      L('Financial Position', 'Finansal Durum'),
      L('Investor Pipeline', 'Yatırımcı Pipeline'),
      L('Project Risks', 'Proje Riskleri'),
      L('AI Recommendations', 'YZ Önerileri'),
      L('Approval Center', 'Onay Merkezi'),
      L('Reports & Search', 'Raporlar ve Arama'),
      L('Notifications', 'Bildirimler'),
      L('Decision logging', 'Karar kaydı'),
    ],
    practicalTasks: [
      L('Review a critical priority', 'Kritik bir önceliği incele'),
      L('Open financial drill-down', 'Finansal detaya in'),
      L('Approve or reject a request', 'Bir talebi onayla veya reddet'),
      L('Inspect an AI recommendation', 'YZ önerisini incele'),
      L('Review an investor pipeline item', 'Yatırımcı kalemini incele'),
      L('Open a project risk', 'Proje riskini aç'),
      L('Generate an executive report', 'Yönetici raporu oluştur'),
    ],
    modules: [
      { id: 'ceo-m1', title: L('Welcome & shell orientation', 'Karşılama ve kabuk yönlendirme'), mandatory: true, estimatedMinutes: 8, tourId: 'tour-shell-basics' },
      { id: 'ceo-m2', title: L('Executive daily rhythm', 'Yönetici günlük ritmi'), mandatory: true, estimatedMinutes: 12, checklistId: 'daily-ceo', tourId: 'tour-executive' },
      { id: 'ceo-m3', title: L('Approvals & AI', 'Onaylar ve YZ'), mandatory: true, estimatedMinutes: 15, tutorialId: 'tut-ai-recommendation', knowledgeCheckId: 'kc-ceo' },
      { id: 'ceo-m4', title: L('Reports optional deep-dive', 'Raporlar (opsiyonel)'), mandatory: false, estimatedMinutes: 10 },
    ],
    deadlineDays: 14,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-cfo',
    roleId: 'cfo',
    title: L('CFO Learning Path', 'CFO Öğrenme Yolu'),
    description: L('Treasury, wires, receivables, approvals, reconciliation.', 'Hazine, havale, alacak, onay ve mutabakat.'),
    teachTopics: [
      L('Finance Workspace', 'Finans Çalışma Alanı'),
      L('Treasury & Cash', 'Hazine ve Nakit'),
      L('Incoming / Outgoing Wires', 'Gelen / Giden Havaleler'),
      L('Receivables & Payables', 'Alacaklar ve Borçlar'),
      L('Forecasts', 'Tahminler'),
      L('Approval Center', 'Onay Merkezi'),
      L('Audit Log & Reconciliation', 'Denetim ve Mutabakat'),
    ],
    practicalTasks: [
      L('Review bank balance', 'Banka bakiyesini incele'),
      L('Reconcile a payment', 'Ödeme mutabakatı yap'),
      L('Inspect a funding gap', 'Fonlama açığını incele'),
      L('Approve an outgoing payment', 'Giden ödemeyi onayla'),
      L('Review 30-day cash forecast', '30 günlük nakit tahminini incele'),
      L('Investigate a financial anomaly', 'Finansal anomalı araştır'),
      L('Upload a bank statement', 'Banka ekstresi yükle'),
    ],
    modules: [
      { id: 'cfo-m1', title: L('Finance orientation', 'Finans oryantasyonu'), mandatory: true, estimatedMinutes: 10, tourId: 'tour-finance' },
      { id: 'cfo-m2', title: L('Daily treasury checklist', 'Günlük hazine listesi'), mandatory: true, estimatedMinutes: 12, checklistId: 'daily-cfo' },
      { id: 'cfo-m3', title: L('Wire reconciliation tutorial', 'Havale mutabakatı'), mandatory: true, estimatedMinutes: 20, tutorialId: 'tut-wire-reconcile', knowledgeCheckId: 'kc-finance' },
    ],
    deadlineDays: 14,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-sales-manager',
    roleId: 'sales_manager',
    title: L('Sales Manager Path', 'Satış Müdürü Yolu'),
    description: L('Pipeline hygiene, coaching, forecasts.', 'Pipeline hijyeni, koçluk, tahminler.'),
    teachTopics: [
      L('Leads & Opportunities', 'Leadler ve Fırsatlar'),
      L('Pipeline & Forecast', 'Pipeline ve Tahmin'),
      L('Team follow-ups', 'Ekip takipleri'),
    ],
    practicalTasks: [
      L('Review stalled opportunities', 'Duran fırsatları incele'),
      L('Coach a follow-up', 'Takip için koçluk yap'),
      L('Approve stage override', 'Aşama değişikliğini onayla'),
    ],
    modules: [
      { id: 'sm-m1', title: L('CRM tour', 'CRM turu'), mandatory: true, estimatedMinutes: 10, tourId: 'tour-crm' },
      { id: 'sm-m2', title: L('Weekly pipeline hygiene', 'Haftalık pipeline hijyeni'), mandatory: true, estimatedMinutes: 15, checklistId: 'weekly-sales' },
      { id: 'sm-m3', title: L('Lead to opportunity', 'Lead’den fırsata'), mandatory: true, estimatedMinutes: 18, tutorialId: 'tut-lead-opportunity', knowledgeCheckId: 'kc-sales' },
    ],
    deadlineDays: 10,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-sales-rep',
    roleId: 'sales_rep',
    title: L('Sales Representative Path', 'Satış Temsilcisi Yolu'),
    description: L('Leads, contacts, opportunities, follow-ups.', 'Lead, kişi, fırsat ve takipler.'),
    teachTopics: [
      L('Leads', 'Leadler'),
      L('Contacts & Companies', 'Kişiler ve Şirketler'),
      L('Opportunities & Pipeline', 'Fırsatlar ve Pipeline'),
      L('Tasks, Meetings, Notes', 'Görevler, Toplantılar, Notlar'),
      L('AI lead recommendations', 'YZ lead önerileri'),
    ],
    practicalTasks: [
      L('Create a lead', 'Lead oluştur'),
      L('Update contact details', 'Kişi bilgilerini güncelle'),
      L('Move an opportunity', 'Fırsat aşamasını değiştir'),
      L('Schedule a meeting', 'Toplantı planla'),
      L('Create a task', 'Görev oluştur'),
      L('Add a note', 'Not ekle'),
      L('Complete a follow-up', 'Takibi tamamla'),
      L('Review lead score', 'Lead skorunu incele'),
      L('Convert a lead', 'Lead dönüştür'),
    ],
    modules: [
      { id: 'sr-m1', title: L('CRM basics', 'CRM temelleri'), mandatory: true, estimatedMinutes: 12, tourId: 'tour-crm' },
      { id: 'sr-m2', title: L('Daily sales checklist', 'Günlük satış listesi'), mandatory: true, estimatedMinutes: 10, checklistId: 'daily-sales' },
      { id: 'sr-m3', title: L('Lead conversion simulation', 'Lead dönüşüm simülasyonu'), mandatory: true, estimatedMinutes: 20, tutorialId: 'tut-lead-opportunity', knowledgeCheckId: 'kc-sales' },
    ],
    deadlineDays: 10,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-ir',
    roleId: 'investor_relations',
    title: L('Investor Relations Path', 'Yatırımcı İlişkileri Yolu'),
    description: L('Investors, reservations, portal access, documents.', 'Yatırımcılar, rezervasyon, portal, belgeler.'),
    teachTopics: [
      L('Investor Workspace', 'Yatırımcı Alanı'),
      L('Preferences & KYC', 'Tercihler ve KYC'),
      L('Reservations & Contracts', 'Rezervasyon ve Sözleşmeler'),
      L('Payments & Closings', 'Ödemeler ve Kapanışlar'),
      L('Portal Access', 'Portal Erişimi'),
    ],
    practicalTasks: [
      L('Create or update investor', 'Yatırımcı oluştur/güncelle'),
      L('Add investment preference', 'Yatırım tercihi ekle'),
      L('Create reservation', 'Rezervasyon oluştur'),
      L('Invite investor to portal', 'Portala davet et'),
      L('Prepare meeting brief', 'Toplantı özeti hazırla'),
    ],
    modules: [
      { id: 'ir-m1', title: L('Investor workspace tour', 'Yatırımcı alanı turu'), mandatory: true, estimatedMinutes: 12, tourId: 'tour-investors' },
      { id: 'ir-m2', title: L('Daily IR checklist', 'Günlük Yİ listesi'), mandatory: true, estimatedMinutes: 10, checklistId: 'daily-ir' },
      { id: 'ir-m3', title: L('Reservation & portal invite', 'Rezervasyon ve portal'), mandatory: true, estimatedMinutes: 22, tutorialId: 'tut-investor-reservation', knowledgeCheckId: 'kc-ir' },
    ],
    deadlineDays: 12,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-pm',
    roleId: 'project_manager',
    title: L('Project Manager Path', 'Proje Yöneticisi Yolu'),
    description: L('Projects, milestones, issues, budget variance.', 'Projeler, kilometre taşları, sorunlar, bütçe.'),
    teachTopics: [
      L('Projects & Construction Board', 'Projeler ve Şantiye Panosu'),
      L('Milestones & Tasks', 'Kilometre taşları ve Görevler'),
      L('Budget & Change Orders', 'Bütçe ve Değişiklik Emirleri'),
      L('Permits & Inspections', 'İzinler ve Denetimler'),
    ],
    practicalTasks: [
      L('Update project status', 'Proje durumunu güncelle'),
      L('Create construction task', 'Şantiye görevi oluştur'),
      L('Report issue', 'Sorun bildir'),
      L('Review budget variance', 'Bütçe sapmasını incele'),
    ],
    modules: [
      { id: 'pm-m1', title: L('Projects tour', 'Projeler turu'), mandatory: true, estimatedMinutes: 12, tourId: 'tour-projects' },
      { id: 'pm-m2', title: L('Daily PM checklist', 'Günlük PY listesi'), mandatory: true, estimatedMinutes: 10, checklistId: 'daily-pm' },
      { id: 'pm-m3', title: L('Budget change approval', 'Bütçe değişikliği onayı'), mandatory: true, estimatedMinutes: 18, tutorialId: 'tut-budget-change' },
    ],
    deadlineDays: 12,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-construction',
    roleId: 'construction_ops',
    title: L('Construction Operations Path', 'İnşaat Operasyonları Yolu'),
    description: L('Field tasks, inspections, contractors, permits.', 'Saha görevleri, denetimler, yükleniciler, izinler.'),
    teachTopics: [
      L('Construction Board', 'Şantiye Panosu'),
      L('Contractors', 'Yükleniciler'),
      L('Inspections & Issues', 'Denetimler ve Sorunlar'),
    ],
    practicalTasks: [
      L('Assign contractor', 'Yüklenici ata'),
      L('Schedule inspection', 'Denetim planla'),
      L('Record inspection result', 'Denetim sonucunu kaydet'),
      L('Upload permit', 'İzin yükle'),
    ],
    modules: [
      { id: 'co-m1', title: L('Construction tour', 'Şantiye turu'), mandatory: true, estimatedMinutes: 10, tourId: 'tour-projects' },
      { id: 'co-m2', title: L('Permit to inspection', 'İzinden denetime'), mandatory: true, estimatedMinutes: 16, tutorialId: 'tut-permit-inspection' },
    ],
    deadlineDays: 10,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-finance',
    roleId: 'finance',
    title: L('Finance Path', 'Finans Yolu'),
    description: L('Day-to-day finance operations and controls.', 'Günlük finans operasyonları ve kontroller.'),
    teachTopics: [
      L('Cash & Wires', 'Nakit ve Havaleler'),
      L('Receivables / Payables', 'Alacak / Borç'),
      L('Reconciliation', 'Mutabakat'),
    ],
    practicalTasks: [
      L('Reconcile incoming wire', 'Gelen havaleyi mutabık kıl'),
      L('Prepare payable schedule', 'Ödeme planı hazırla'),
    ],
    modules: [
      { id: 'fin-m1', title: L('Finance tour', 'Finans turu'), mandatory: true, estimatedMinutes: 10, tourId: 'tour-finance' },
      { id: 'fin-m2', title: L('Outgoing payment approval', 'Giden ödeme onayı'), mandatory: true, estimatedMinutes: 15, tutorialId: 'tut-outgoing-payment', knowledgeCheckId: 'kc-finance' },
    ],
    deadlineDays: 12,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-marketing',
    roleId: 'marketing',
    title: L('Marketing Path', 'Pazarlama Yolu'),
    description: L('Campaigns, attribution, content, funnel.', 'Kampanyalar, atıf, içerik, huni.'),
    teachTopics: [
      L('Campaigns & Attribution', 'Kampanyalar ve Atıf'),
      L('Content Studio', 'İçerik Stüdyosu'),
      L('Funnel & ROI', 'Huni ve ROI'),
    ],
    practicalTasks: [
      L('Create campaign', 'Kampanya oluştur'),
      L('Review attribution', 'Atıfı incele'),
      L('Investigate poor lead quality', 'Düşük lead kalitesini araştır'),
    ],
    modules: [
      { id: 'mkt-m1', title: L('Marketing tour', 'Pazarlama turu'), mandatory: true, estimatedMinutes: 12, tourId: 'tour-marketing' },
      { id: 'mkt-m2', title: L('Daily marketing checklist', 'Günlük pazarlama listesi'), mandatory: true, estimatedMinutes: 10, checklistId: 'daily-marketing' },
      { id: 'mkt-m3', title: L('Campaign to attribution', 'Kampanyadan atıfa'), mandatory: true, estimatedMinutes: 18, tutorialId: 'tut-campaign-attribution', knowledgeCheckId: 'kc-marketing' },
    ],
    deadlineDays: 10,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-operations',
    roleId: 'operations',
    title: L('Operations Path', 'Operasyonlar Yolu'),
    description: L('Cross-functional playbooks, SLAs, escalations.', 'Çapraz fonksiyon playbook, SLA, yükseltmeler.'),
    teachTopics: [
      L('Operations playbooks', 'Operasyon playbookları'),
      L('SLA & escalation', 'SLA ve yükseltme'),
      L('Support routing', 'Destek yönlendirme'),
    ],
    practicalTasks: [
      L('Open a playbook', 'Playbook aç'),
      L('Escalate a support case', 'Destek vakasını yükselt'),
    ],
    modules: [
      { id: 'ops-m1', title: L('Ops orientation', 'Operasyon oryantasyonu'), mandatory: true, estimatedMinutes: 10, tourId: 'tour-shell-basics' },
      { id: 'ops-m2', title: L('Incident reporting', 'Olay bildirimi'), mandatory: true, estimatedMinutes: 12, tutorialId: 'tut-incident' },
    ],
    deadlineDays: 14,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-admin',
    roleId: 'admin',
    title: L('Admin Learning Path', 'Yönetici Öğrenme Yolu'),
    description: L('Users, roles, security, training builder, health.', 'Kullanıcılar, roller, güvenlik, eğitim oluşturucu, sağlık.'),
    teachTopics: [
      L('Users & Roles', 'Kullanıcılar ve Roller'),
      L('Permissions & Access', 'İzinler ve Erişim'),
      L('Integrations & AI settings', 'Entegrasyonlar ve YZ'),
      L('Training Builder', 'Eğitim Oluşturucu'),
      L('Health & Audit', 'Sağlık ve Denetim'),
    ],
    practicalTasks: [
      L('Create user', 'Kullanıcı oluştur'),
      L('Assign role', 'Rol ata'),
      L('Review permission matrix', 'İzin matrisini incele'),
      L('Create training path', 'Eğitim yolu oluştur'),
      L('Publish guidance', 'Rehberliği yayınla'),
      L('Review system health', 'Sistem sağlığını incele'),
    ],
    modules: [
      { id: 'adm-m1', title: L('Admin shell tour', 'Yönetici kabuk turu'), mandatory: true, estimatedMinutes: 12, tourId: 'tour-admin' },
      { id: 'adm-m2', title: L('User creation tutorial', 'Kullanıcı oluşturma'), mandatory: true, estimatedMinutes: 15, tutorialId: 'tut-user-create', knowledgeCheckId: 'kc-admin' },
      { id: 'adm-m3', title: L('Training builder', 'Eğitim oluşturucu'), mandatory: true, estimatedMinutes: 20 },
    ],
    deadlineDays: 14,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-ea',
    roleId: 'executive_assistant',
    title: L('Executive Assistant Path', 'Yönetici Asistanı Yolu'),
    description: L('Priorities, meetings, follow-ups, briefings.', 'Öncelikler, toplantılar, takipler, brifingler.'),
    teachTopics: [
      L('Priorities & calendar', 'Öncelikler ve takvim'),
      L('Meeting prep', 'Toplantı hazırlığı'),
      L('Notifications', 'Bildirimler'),
    ],
    practicalTasks: [
      L('Prepare meeting brief', 'Toplantı özeti hazırla'),
      L('Track follow-ups', 'Takipleri izle'),
    ],
    modules: [
      { id: 'ea-m1', title: L('Shell basics', 'Kabuk temelleri'), mandatory: true, estimatedMinutes: 8, tourId: 'tour-shell-basics' },
      { id: 'ea-m2', title: L('Meeting prep tutorial', 'Toplantı hazırlığı'), mandatory: true, estimatedMinutes: 12, tutorialId: 'tut-meeting-prep' },
    ],
    deadlineDays: 10,
    version: '1.0.0',
    status: 'published',
  },
  {
    id: 'path-portal',
    roleId: 'portal_investor',
    title: L('Portal Investor Path', 'Portal Yatırımcı Yolu'),
    description: L('Portfolio, payments, documents, messages — client language.', 'Portföy, ödemeler, belgeler, mesajlar — müşteri dili.'),
    teachTopics: [
      L('Login & security', 'Giriş ve güvenlik'),
      L('Portfolio & projects', 'Portföy ve projeler'),
      L('Payments & documents', 'Ödemeler ve belgeler'),
      L('Messages & notifications', 'Mesajlar ve bildirimler'),
    ],
    practicalTasks: [
      L('View portfolio', 'Portföyü görüntüle'),
      L('Download a document', 'Belge indir'),
      L('Check payment status', 'Ödeme durumunu kontrol et'),
    ],
    modules: [
      { id: 'por-m1', title: L('Portal orientation', 'Portal oryantasyonu'), mandatory: true, estimatedMinutes: 8, tourId: 'tour-portal' },
    ],
    deadlineDays: 7,
    version: '1.0.0',
    status: 'published',
  },
];

export function getPathForRole(roleId: string): LearningPath | undefined {
  return LEARNING_PATHS.find((p) => p.roleId === roleId);
}
