import { L } from '../locale';
import type { ProductTour } from '../types';

export const PRODUCT_TOURS: ProductTour[] = [
  {
    id: 'tour-shell-basics',
    title: L('Shell & navigation basics', 'Kabuk ve gezinme temelleri'),
    description: L('Learn the OS shell: menu, search, and your workspaces.', 'OS kabuğunu öğrenin: menü, arama ve çalışma alanları.'),
    type: 'informational',
    roles: ['ceo', 'cfo', 'sales_manager', 'sales_rep', 'investor_relations', 'project_manager', 'construction_ops', 'finance', 'marketing', 'operations', 'admin', 'executive_assistant'],
    route: '/dashboard/onboarding',
    estimatedMinutes: 5,
    skipAllowed: true,
    version: '1.0.0',
    status: 'published',
    steps: [
      {
        id: 'shell-1',
        title: L('Main menu', 'Ana menü'),
        description: L('Use the sidebar to open your primary workspaces.', 'Birincil çalışma alanlarını açmak için kenar çubuğunu kullanın.'),
        action: L('Locate the main menu', 'Ana menüyü bulun'),
        expectedResult: L('You can identify Home and workspaces', 'Ana Sayfa ve çalışma alanlarını ayırt edebilirsiniz'),
        selector: '[data-tour="os-main-menu"]',
        completionCondition: 'viewed',
        placement: 'right',
        helpLink: '/dashboard/help?q=navigation',
      },
      {
        id: 'shell-2',
        title: L('Onboarding hub', 'Oryantasyon merkezi'),
        description: L('Your role path, checklists, and first tasks live here.', 'Rol yolu, listeler ve ilk görevler burada.'),
        action: L('Review the onboarding panel', 'Oryantasyon panelini inceleyin'),
        expectedResult: L('You see your assigned role path', 'Atanan rol yolunu görürsünüz'),
        selector: '[data-tour="onboarding-welcome"]',
        completionCondition: 'viewed',
        placement: 'bottom',
      },
      {
        id: 'shell-3',
        title: L('Help & training', 'Yardım ve eğitim'),
        description: L('Searchable help and training library are always available.', 'Aranabilir yardım ve eğitim kütüphanesi her zaman erişilebilir.'),
        action: L('Note the Help entry', 'Yardım girişini not edin'),
        expectedResult: L('You know where to search for answers', 'Cevap arayacağınız yeri biliyorsunuz'),
        selector: '[data-tour="nav-help"]',
        completionCondition: 'viewed',
        placement: 'right',
        helpLink: '/dashboard/help',
      },
      {
        id: 'shell-4',
        title: L('Progress', 'İlerleme'),
        description: L('Progress is saved — you can pause and resume.', 'İlerleme kaydedilir — duraklatıp devam edebilirsiniz.'),
        action: L('Confirm progress indicator', 'İlerleme göstergesini doğrulayın'),
        expectedResult: L('You understand resume behavior', 'Devam etme davranışını anlıyorsunuz'),
        selector: '[data-tour="onboarding-progress"]',
        completionCondition: 'viewed',
        placement: 'left',
      },
    ],
  },
  {
    id: 'tour-executive',
    title: L('Executive dashboard tour', 'Yönetici paneli turu'),
    description: L('Priorities, financial pulse, and approvals.', 'Öncelikler, finansal nabız ve onaylar.'),
    type: 'guided_workflow',
    roles: ['ceo', 'executive_assistant', 'admin'],
    route: '/dashboard/executive',
    estimatedMinutes: 8,
    skipAllowed: true,
    version: '1.0.0',
    status: 'published',
    steps: [
      {
        id: 'exec-1',
        title: L('Executive workspace', 'Yönetici alanı'),
        description: L('Start each day with critical priorities.', 'Her güne kritik önceliklerle başlayın.'),
        action: L('Open executive', 'Yöneticiyi açın'),
        expectedResult: L('Dashboard loads', 'Panel yüklenir'),
        selector: '[data-tour="nav-executive"]',
        completionCondition: 'viewed',
        placement: 'right',
      },
      {
        id: 'exec-2',
        title: L('Onboarding link-back', 'Oryantasyona dönüş'),
        description: L('Return to onboarding when you need guided steps.', 'Rehberli adımlar için oryantasyona dönün.'),
        action: L('Find onboarding', 'Oryantasyonu bulun'),
        expectedResult: L('Path is clear', 'Yol net'),
        selector: '[data-tour="nav-onboarding"]',
        completionCondition: 'viewed',
        placement: 'right',
      },
    ],
  },
  {
    id: 'tour-crm',
    title: L('CRM tour', 'CRM turu'),
    description: L('Leads, pipeline, and follow-ups.', 'Leadler, pipeline ve takipler.'),
    type: 'guided_click',
    roles: ['sales_manager', 'sales_rep', 'admin'],
    route: '/workspaces/crm',
    estimatedMinutes: 8,
    skipAllowed: true,
    version: '1.0.0',
    status: 'published',
    steps: [
      {
        id: 'crm-1',
        title: L('CRM entry', 'CRM girişi'),
        description: L('CRM workspace holds leads and opportunities.', 'CRM alanı lead ve fırsatları barındırır.'),
        action: L('Locate CRM', 'CRM’yi bulun'),
        expectedResult: L('CRM link visible', 'CRM bağlantısı görünür'),
        selector: '[data-tour="nav-help"]',
        completionCondition: 'viewed',
        placement: 'right',
        warning: L('Only act on records you are assigned.', 'Yalnızca size atanan kayıtlarda işlem yapın.'),
      },
      {
        id: 'crm-2',
        title: L('Training library', 'Eğitim kütüphanesi'),
        description: L('Workflow tutorials reinforce CRM steps.', 'İş akışı eğitimleri CRM adımlarını pekiştirir.'),
        action: L('Open training', 'Eğitimi açın'),
        expectedResult: L('Training hub available', 'Eğitim merkezi erişilebilir'),
        selector: '[data-tour="nav-training"]',
        completionCondition: 'viewed',
        placement: 'right',
      },
    ],
  },
  {
    id: 'tour-investors',
    title: L('Investor workspace tour', 'Yatırımcı alanı turu'),
    description: L('Profiles, reservations, portal access.', 'Profiller, rezervasyonlar, portal erişimi.'),
    type: 'guided_workflow',
    roles: ['investor_relations', 'admin'],
    route: '/dashboard/investors',
    estimatedMinutes: 8,
    skipAllowed: true,
    version: '1.0.0',
    status: 'published',
    steps: [
      {
        id: 'inv-1',
        title: L('Investors module', 'Yatırımcılar modülü'),
        description: L('Manage capital partners and preferences.', 'Sermaye ortaklarını ve tercihleri yönetin.'),
        action: L('Find investors nav', 'Yatırımcılar menüsünü bulun'),
        expectedResult: L('Module visible if permitted', 'İzin varsa modül görünür'),
        selector: '[data-tour="nav-onboarding"]',
        completionCondition: 'viewed',
        placement: 'right',
      },
    ],
  },
  {
    id: 'tour-projects',
    title: L('Projects tour', 'Projeler turu'),
    description: L('Milestones, issues, budget.', 'Kilometre taşları, sorunlar, bütçe.'),
    type: 'informational',
    roles: ['project_manager', 'construction_ops', 'admin'],
    route: '/dashboard/projects',
    estimatedMinutes: 7,
    skipAllowed: true,
    version: '1.0.0',
    status: 'published',
    steps: [
      {
        id: 'prj-1',
        title: L('Projects entry', 'Projeler girişi'),
        description: L('Track delivery and construction status.', 'Teslimat ve şantiye durumunu izleyin.'),
        action: L('Open training for project tutorials', 'Proje eğitimleri için eğitimi açın'),
        expectedResult: L('Tutorials listed', 'Eğitimler listelenir'),
        selector: '[data-tour="nav-training"]',
        completionCondition: 'viewed',
        placement: 'right',
      },
    ],
  },
  {
    id: 'tour-finance',
    title: L('Finance tour', 'Finans turu'),
    description: L('Cash, wires, approvals.', 'Nakit, havaleler, onaylar.'),
    type: 'mandatory_compliance',
    roles: ['cfo', 'finance', 'admin'],
    route: '/dashboard/finance',
    estimatedMinutes: 8,
    skipAllowed: false,
    version: '1.0.0',
    status: 'published',
    steps: [
      {
        id: 'fin-1',
        title: L('Finance controls', 'Finans kontrolleri'),
        description: L('Approvals and reconciliation protect cash.', 'Onaylar ve mutabakat nakdi korur.'),
        action: L('Review help for reconciliation', 'Mutabakat yardımını inceleyin'),
        expectedResult: L('Help article reachable', 'Yardım makalesine erişilir'),
        selector: '[data-tour="nav-help"]',
        completionCondition: 'viewed',
        placement: 'right',
        warning: L('Never post live payments in training mode.', 'Eğitim modunda canlı ödeme kaydı yapmayın.'),
      },
    ],
  },
  {
    id: 'tour-marketing',
    title: L('Marketing tour', 'Pazarlama turu'),
    description: L('Campaigns, attribution, content.', 'Kampanyalar, atıf, içerik.'),
    type: 'new_feature',
    roles: ['marketing', 'admin'],
    route: '/workspaces/marketing',
    estimatedMinutes: 7,
    skipAllowed: true,
    version: '1.0.0',
    status: 'published',
    steps: [
      {
        id: 'mkt-1',
        title: L('Marketing guidance', 'Pazarlama rehberliği'),
        description: L('Attribution and ROI explanations live in help.', 'Atıf ve ROI açıklamaları yardımda.'),
        action: L('Open help', 'Yardımı açın'),
        expectedResult: L('Marketing articles listed', 'Pazarlama makaleleri listelenir'),
        selector: '[data-tour="nav-help"]',
        completionCondition: 'viewed',
        placement: 'right',
      },
    ],
  },
  {
    id: 'tour-admin',
    title: L('Admin tour', 'Yönetici turu'),
    description: L('Users, roles, adoption, training builder.', 'Kullanıcılar, roller, benimsenme, eğitim oluşturucu.'),
    type: 'guided_workflow',
    roles: ['admin'],
    route: '/dashboard/admin',
    estimatedMinutes: 10,
    skipAllowed: true,
    version: '1.0.0',
    status: 'published',
    adminOnly: true,
    steps: [
      {
        id: 'adm-1',
        title: L('Adoption dashboard', 'Benimsenme paneli'),
        description: L('Measure activation and training completion.', 'Aktivasyon ve eğitim tamamlanmasını ölçün.'),
        action: L('Open adoption', 'Benimsenmeyi açın'),
        expectedResult: L('KPIs visible', 'KPI’lar görünür'),
        selector: '[data-tour="nav-admin-adoption"]',
        completionCondition: 'viewed',
        placement: 'right',
      },
      {
        id: 'adm-2',
        title: L('Training builder', 'Eğitim oluşturucu'),
        description: L('Draft, preview, and publish tours safely.', 'Turları güvenle taslaklayın, önizleyin, yayınlayın.'),
        action: L('Open builder', 'Oluşturucuyu açın'),
        expectedResult: L('Builder loads', 'Oluşturucu yüklenir'),
        selector: '[data-tour="nav-training-builder"]',
        completionCondition: 'viewed',
        placement: 'right',
        warning: L('Broken selectors block publish.', 'Bozuk seçiciler yayını engeller.'),
      },
    ],
  },
  {
    id: 'tour-portal',
    title: L('Portal orientation', 'Portal oryantasyonu'),
    description: L('Portfolio, payments, documents — client language.', 'Portföy, ödemeler, belgeler — müşteri dili.'),
    type: 'informational',
    roles: ['portal_investor'],
    route: '/portal/help',
    estimatedMinutes: 6,
    skipAllowed: true,
    version: '1.0.0',
    status: 'published',
    steps: [
      {
        id: 'por-1',
        title: L('Portal help', 'Portal yardımı'),
        description: L('Find answers without CRM jargon.', 'CRM jargonu olmadan cevap bulun.'),
        action: L('Open portal help topics', 'Portal yardım konularını açın'),
        expectedResult: L('Topics listed', 'Konular listelenir'),
        selector: '[data-tour="portal-help-root"]',
        completionCondition: 'viewed',
        placement: 'bottom',
      },
    ],
  },
];

export function getTour(id: string): ProductTour | undefined {
  return PRODUCT_TOURS.find((t) => t.id === id);
}
