import { L } from '../locale';
import type { WorkflowTutorial } from '../types';

function tut(
  id: string,
  en: string,
  tr: string,
  role: WorkflowTutorial['responsibleRole'],
  stepsEn: string[],
  stepsTr: string[],
  helpIds: string[],
): WorkflowTutorial {
  return {
    id,
    title: L(en, tr),
    purpose: L(`End-to-end guidance for ${en}.`, `${tr} için uçtan uca rehber.`),
    responsibleRole: role,
    prerequisites: [L('Relevant workspace access', 'İlgili çalışma alanı erişimi')],
    steps: stepsEn.map((s, i) => L(s, stepsTr[i] ?? s)),
    expectedResult: L('Workflow completed with audit trail', 'İş akışı denetim iziyle tamamlandı'),
    commonMistakes: [
      L('Skipping required approvals', 'Zorunlu onayları atlamak'),
      L('Using production actions in training mode', 'Eğitim modunda üretim aksiyonları kullanmak'),
    ],
    approvalRequirements: L('Follow role-based approval matrix', 'Role dayalı onay matrisini izleyin'),
    relatedHelpIds: helpIds,
    version: '1.0.0',
    status: 'published',
  };
}

export const WORKFLOW_TUTORIALS: WorkflowTutorial[] = [
  tut('tut-lead-opportunity', 'Lead to Opportunity', 'Lead’den Fırsata', 'sales_rep',
    ['Open lead', 'Qualify', 'Create opportunity', 'Set stage', 'Assign owner'],
    ['Leadi aç', 'Nitele', 'Fırsat oluştur', 'Aşama belirle', 'Sahip ata'],
    ['help-duplicate-leads']),
  tut('tut-opportunity-investor', 'Opportunity to Investor', 'Fırsattan Yatırımcıya', 'investor_relations',
    ['Confirm interest', 'Create investor profile', 'Link opportunity', 'Capture preferences'],
    ['İlgiyi doğrula', 'Yatırımcı profili oluştur', 'Fırsatı bağla', 'Tercihleri kaydet'],
    ['help-investor-invite']),
  tut('tut-investor-reservation', 'Investor to Reservation', 'Yatırımcıdan Rezervasyona', 'investor_relations',
    ['Select unit', 'Create reservation', 'Set expiry', 'Notify IR (training only)'],
    ['Birim seç', 'Rezervasyon oluştur', 'Süre belirle', 'Yİ bilgilendir (yalnızca eğitim)'],
    ['help-reservation']),
  tut('tut-reservation-contract', 'Reservation to Contract', 'Rezervasyondan Sözleşmeye', 'investor_relations',
    ['Collect documents', 'Draft contract', 'Legal review', 'Prepare for signature'],
    ['Belgeleri topla', 'Sözleşme taslağı', 'Hukuk incelemesi', 'İmzaya hazırla'],
    ['help-contract']),
  tut('tut-contract-payment', 'Contract to Payment', 'Sözleşmeden Ödemeye', 'finance',
    ['Record schedule', 'Confirm account', 'Await wire', 'Match payment'],
    ['Planı kaydet', 'Hesabı doğrula', 'Havale bekle', 'Ödemeyi eşleştir'],
    ['help-payment-approval']),
  tut('tut-payment-closing', 'Payment to Closing', 'Ödemeden Kapanışa', 'investor_relations',
    ['Verify funds', 'Clear contingencies', 'Schedule closing', 'Update status'],
    ['Fonları doğrula', 'Koşulları temizle', 'Kapanış planla', 'Durumu güncelle'],
    ['help-closing']),
  tut('tut-closing-portfolio', 'Closing to Portfolio', 'Kapanıştan Portföye', 'investor_relations',
    ['Activate portfolio item', 'Enable portal access', 'Share documents', 'Confirm investor view'],
    ['Portföy kalemini etkinleştir', 'Portal erişimini aç', 'Belgeleri paylaş', 'Yatırımcı görünümünü doğrula'],
    ['help-portal-portfolio']),
  tut('tut-project-lifecycle', 'Project Creation to Completion', 'Proje Oluşturmadan Tamamlamaya', 'project_manager',
    ['Create project', 'Set milestones', 'Assign team', 'Track delivery', 'Close project'],
    ['Proje oluştur', 'Kilometre taşları', 'Ekip ata', 'Teslimatı izle', 'Projeyi kapat'],
    ['help-project-budget']),
  tut('tut-permit-inspection', 'Permit to Inspection', 'İzinden Denetime', 'construction_ops',
    ['Upload permit', 'Schedule inspection', 'Record result', 'Close findings'],
    ['İzin yükle', 'Denetim planla', 'Sonucu kaydet', 'Bulguları kapat'],
    ['help-permit']),
  tut('tut-budget-change', 'Budget Change Approval', 'Bütçe Değişikliği Onayı', 'project_manager',
    ['Draft change', 'Attach evidence', 'Submit approval', 'Apply approved change'],
    ['Değişiklik taslağı', 'Kanıt ekle', 'Onaya gönder', 'Onaylı değişikliği uygula'],
    ['help-project-budget']),
  tut('tut-wire-reconcile', 'Incoming Wire Reconciliation', 'Gelen Havale Mutabakatı', 'finance',
    ['Locate unmatched wire', 'Match to obligation', 'Post (training blocked)', 'Confirm balance'],
    ['Eşleşmeyen havaleyi bul', 'Yükümlülüğe eşleştir', 'Kaydet (eğitimde engelli)', 'Bakiyeyi doğrula'],
    ['help-reconciliation']),
  tut('tut-outgoing-payment', 'Outgoing Payment Approval', 'Giden Ödeme Onayı', 'finance',
    ['Create payment request', 'Validate account', 'Route approval', 'Release when approved'],
    ['Ödeme talebi oluştur', 'Hesabı doğrula', 'Onaya yönlendir', 'Onaylanınca serbest bırak'],
    ['help-payment-approval']),
  tut('tut-campaign-attribution', 'Campaign to Lead Attribution', 'Kampanyadan Lead Atıfına', 'marketing',
    ['Create campaign', 'Assign channel', 'Capture leads', 'Review attribution'],
    ['Kampanya oluştur', 'Kanal ata', 'Leadleri yakala', 'Atıfı incele'],
    ['help-attribution']),
  tut('tut-document-review', 'Document Upload and Review', 'Belge Yükleme ve İnceleme', 'operations',
    ['Upload document', 'Classify', 'Request review', 'Publish to permitted viewers'],
    ['Belge yükle', 'Sınıflandır', 'İnceleme iste', 'İzinli görüntüleyicilere yayınla'],
    ['help-documents']),
  tut('tut-portal-invite', 'Investor Portal Invitation', 'Yatırımcı Portal Daveti', 'investor_relations',
    ['Verify investor', 'Enable portal', 'Send invite (training blocked)', 'Confirm first login'],
    ['Yatırımcıyı doğrula', 'Portalı etkinleştir', 'Davet gönder (eğitimde engelli)', 'İlk girişi doğrula'],
    ['help-investor-invite']),
  tut('tut-meeting-prep', 'Meeting Preparation and Follow-Up', 'Toplantı Hazırlığı ve Takip', 'executive_assistant',
    ['Create meeting', 'Attach brief', 'Capture notes', 'Create follow-ups'],
    ['Toplantı oluştur', 'Özet ekle', 'Notları kaydet', 'Takipler oluştur'],
    ['help-meetings']),
  tut('tut-ai-recommendation', 'AI Recommendation Review', 'YZ Öneri İncelemesi', 'ceo',
    ['Open AI workspace', 'Inspect recommendation', 'Accept or dismiss', 'Log decision'],
    ['YZ alanını aç', 'Öneriyi incele', 'Kabul veya reddet', 'Kararı kaydet'],
    ['help-ai']),
  tut('tut-user-create', 'User Creation and Permission Assignment', 'Kullanıcı Oluşturma ve İzin Atama', 'admin',
    ['Create user', 'Assign role', 'Confirm workspace access', 'Send invite'],
    ['Kullanıcı oluştur', 'Rol ata', 'Çalışma alanı erişimini doğrula', 'Davet gönder'],
    ['help-admin-users']),
  tut('tut-incident', 'Incident Reporting', 'Olay Bildirimi', 'operations',
    ['Classify severity', 'Capture evidence', 'Notify owners', 'Track resolution'],
    ['Ciddiyeti sınıflandır', 'Kanıt topla', 'Sahipleri bilgilendir', 'Çözümü izle'],
    ['help-support']),
  tut('tut-support-escalation', 'Support Escalation', 'Destek Yükseltme', 'operations',
    ['Open support request', 'Set severity', 'Route category', 'Escalate if SLA breached'],
    ['Destek talebi aç', 'Ciddiyet belirle', 'Kategoriye yönlendir', 'SLA aşımında yükselt'],
    ['help-support']),
];
