import { investorProfile } from './mock-data';
import type {
  Attachment,
  Conversation,
  Message,
  MessageAuthor,
  TimelineEvent,
} from './messaging-types';

const INVESTOR_AUTHOR: MessageAuthor = {
  id: 'inv-001',
  name: investorProfile.name,
  role: 'Investor',
  avatarInitials: investorProfile.avatarInitials,
  isInvestor: true,
  emailMasked: 'e***@whitmorecapital.com',
};

const IR_TEAM = {
  sarah: {
    id: 'ir-001',
    name: 'Sarah Chen',
    role: 'Relationship Manager',
    avatarInitials: 'SC',
    isInvestor: false,
    emailMasked: 's***@investhome.com',
  },
  marcus: {
    id: 'ir-002',
    name: 'Marcus Webb',
    role: 'Investor Relations',
    avatarInitials: 'MW',
    isInvestor: false,
    emailMasked: 'm***@investhome.com',
  },
  elena: {
    id: 'ir-003',
    name: 'Elena Vasquez',
    role: 'Portfolio Manager',
    avatarInitials: 'EV',
    isInvestor: false,
    emailMasked: 'e***@investhome.com',
  },
  james: {
    id: 'ir-004',
    name: 'James Okonkwo',
    role: 'Legal & Compliance',
    avatarInitials: 'JO',
    isInvestor: false,
    emailMasked: 'j***@investhome.com',
  },
  system: {
    id: 'sys-001',
    name: 'Investhome OS',
    role: 'System',
    avatarInitials: 'IO',
    isInvestor: false,
    emailMasked: 'system@investhome.com',
  },
};

function attach(
  id: string,
  fileName: string,
  fileType: Attachment['fileType'],
  fileSizeBytes: number,
): Attachment {
  return { id, fileName, fileType, fileSizeBytes, isMock: true };
}

function msg(
  partial: Omit<Message, 'isInternal'> & { isInternal?: boolean },
): Message {
  return { isInternal: false, ...partial };
}

function internalNote(
  partial: Omit<Message, 'isInternal' | 'author'> & { author?: MessageAuthor },
): Message {
  return {
    ...partial,
    author: partial.author ?? IR_TEAM.marcus,
    isInternal: true,
  };
}

function timeline(
  id: string,
  type: TimelineEvent['type'],
  title: string,
  description: string,
  timestamp: string,
  referenceId?: string,
): TimelineEvent {
  return { id, type, title, description, timestamp, referenceId };
}

function conv(
  partial: Omit<
    Conversation,
    'messages' | 'timelineEvents'
  > & {
    messages: Message[];
    timelineEvents?: TimelineEvent[];
  },
): Conversation {
  const visibleMessages = partial.messages.filter((m) => !m.isInternal);
  const lastMsg = visibleMessages[visibleMessages.length - 1];
  return {
    ...partial,
    messages: partial.messages,
    timelineEvents: partial.timelineEvents ?? [],
    lastMessagePreview: lastMsg?.body.slice(0, 120) ?? partial.lastMessagePreview,
    lastMessageAt: lastMsg?.sentAt ?? partial.lastMessageAt,
    unreadCount: visibleMessages.filter((m) => !m.isRead && !m.author.isInvestor).length,
    hasAttachments: visibleMessages.some((m) => m.attachments.length > 0),
  };
}

const conversations: Conversation[] = [
  conv({
    id: 'conv-001',
    subject: 'Q3 Portfolio Review — Allocation Discussion',
    investmentId: null,
    investmentName: 'Portfolio',
    type: 'direct',
    status: 'active',
    category: 'inbox',
    messageType: 'investor_relations',
    priority: 'high',
    irMember: IR_TEAM.sarah,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-14T16:30:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: true,
    relatedTaskIds: ['task-004'],
    relatedDocumentIds: [],
    relatedSignatureIds: [],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-001-1',
        conversationId: 'conv-001',
        author: IR_TEAM.sarah,
        body: 'Good afternoon Eleanor. I wanted to confirm our Q3 portfolio review scheduled for July 18 at 2:00 PM ET. We will cover allocation across your active positions and upcoming distribution schedule.',
        messageType: 'investor_relations',
        sentAt: '2025-07-10T14:00:00Z',
        isRead: true,
        attachments: [],
        references: [],
        isPinned: false,
      }),
      msg({
        id: 'msg-001-2',
        conversationId: 'conv-001',
        author: INVESTOR_AUTHOR,
        body: 'Thank you Sarah. That time works well. Please include an update on The Temple construction timeline.',
        messageType: 'investor_relations',
        sentAt: '2025-07-11T09:15:00Z',
        isRead: true,
        attachments: [],
        references: [{ type: 'investment', id: 'pi-001', label: 'The Temple' }],
        isPinned: false,
      }),
      msg({
        id: 'msg-001-3',
        conversationId: 'conv-001',
        author: IR_TEAM.sarah,
        body: 'Absolutely — I have added The Temple progress report to the agenda. Looking forward to our conversation.',
        messageType: 'investor_relations',
        sentAt: '2025-07-14T16:30:00Z',
        isRead: false,
        attachments: [attach('att-001', 'Q3-Review-Agenda.pdf', 'pdf', 245_760)],
        references: [{ type: 'task', id: 'task-004', label: 'Confirm Q3 portfolio review' }],
        isPinned: true,
      }),
      internalNote({
        id: 'msg-001-int',
        conversationId: 'conv-001',
        body: 'RM note: Eleanor prefers morning calls but confirmed afternoon slot.',
        messageType: 'investor_relations',
        sentAt: '2025-07-11T09:20:00Z',
        isRead: true,
        attachments: [],
        references: [],
        isPinned: false,
      }),
    ],
    timelineEvents: [
      timeline('tl-001-1', 'message', 'Review scheduled', 'Q3 portfolio review confirmed for July 18', '2025-07-10T14:00:00Z'),
      timeline('tl-001-2', 'task', 'Task linked', 'Confirm Q3 portfolio review appointment', '2025-07-14T16:30:00Z', 'task-004'),
    ],
  }),

  conv({
    id: 'conv-002',
    subject: 'The Temple — Construction Milestone Update',
    investmentId: 'pi-001',
    investmentName: 'The Temple',
    type: 'project_thread',
    status: 'active',
    category: 'project_updates',
    messageType: 'construction_update',
    priority: 'normal',
    irMember: IR_TEAM.elena,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-12T11:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: [],
    relatedDocumentIds: ['doc-003'],
    relatedSignatureIds: [],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-002-1',
        conversationId: 'conv-002',
        author: IR_TEAM.elena,
        body: 'Structural steel installation is complete at The Temple. The project remains on schedule at 62% completion with facade work beginning next week.',
        messageType: 'construction_update',
        sentAt: '2025-07-08T10:00:00Z',
        isRead: true,
        attachments: [attach('att-002', 'Temple-Construction-Photos-July.zip', 'png', 4_194_304)],
        references: [{ type: 'investment', id: 'pi-001', label: 'The Temple' }],
        isPinned: false,
      }),
      msg({
        id: 'msg-002-2',
        conversationId: 'conv-002',
        author: IR_TEAM.system,
        body: 'Project milestone recorded: Structural completion — The Temple (62% overall progress).',
        messageType: 'system_notification',
        sentAt: '2025-07-08T10:05:00Z',
        isRead: true,
        attachments: [],
        references: [{ type: 'document', id: 'doc-003', label: 'Construction Progress Report' }],
        isPinned: false,
      }),
      msg({
        id: 'msg-002-3',
        conversationId: 'conv-002',
        author: INVESTOR_AUTHOR,
        body: 'Excellent progress. When will the next investor site visit be scheduled?',
        messageType: 'project_update',
        sentAt: '2025-07-12T11:00:00Z',
        isRead: true,
        attachments: [],
        references: [],
        isPinned: false,
      }),
    ],
    timelineEvents: [
      timeline('tl-002-1', 'construction', 'Structural complete', 'Steel installation finished — 62% project completion', '2025-07-08T10:00:00Z', 'pi-001'),
      timeline('tl-002-2', 'document', 'Report available', 'Construction progress report uploaded', '2025-07-08T10:05:00Z', 'doc-003'),
    ],
  }),

  conv({
    id: 'conv-003',
    subject: 'Uniloft — Q2 Distribution Notice',
    investmentId: 'pi-002',
    investmentName: 'Uniloft',
    type: 'project_thread',
    status: 'active',
    category: 'financial',
    messageType: 'distribution_notice',
    priority: 'high',
    irMember: IR_TEAM.marcus,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-09T08:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: true,
    relatedTaskIds: [],
    relatedDocumentIds: ['doc-005'],
    relatedSignatureIds: [],
    relatedDistributionIds: ['dist-002-04'],
    messages: [
      msg({
        id: 'msg-003-1',
        conversationId: 'conv-003',
        author: IR_TEAM.marcus,
        body: 'Your Q2 preferred return distribution of $17,000 from Uniloft has been scheduled for deposit on June 30. Please review the attached distribution statement.',
        messageType: 'distribution_notice',
        sentAt: '2025-06-28T09:00:00Z',
        isRead: true,
        attachments: [attach('att-003', 'Uniloft-Q2-Distribution-Statement.pdf', 'pdf', 512_000)],
        references: [
          { type: 'investment', id: 'pi-002', label: 'Uniloft' },
          { type: 'distribution', id: 'dist-002-04', label: 'Q2 Preferred Return' },
        ],
        isPinned: false,
      }),
      msg({
        id: 'msg-003-2',
        conversationId: 'conv-003',
        author: IR_TEAM.system,
        body: 'Distribution completed: $17,000 deposited to account ending in ••••4821.',
        messageType: 'system_notification',
        sentAt: '2025-07-09T08:00:00Z',
        isRead: false,
        attachments: [],
        references: [{ type: 'distribution', id: 'dist-002-04', label: 'Q2 Distribution' }],
        isPinned: false,
      }),
    ],
    timelineEvents: [
      timeline('tl-003-1', 'distribution', 'Distribution scheduled', 'Q2 preferred return of $17,000', '2025-06-28T09:00:00Z', 'dist-002-04'),
      timeline('tl-003-2', 'distribution', 'Payment completed', 'Funds deposited to investor account', '2025-07-09T08:00:00Z', 'dist-002-04'),
    ],
  }),

  conv({
    id: 'conv-004',
    subject: 'Subscription Agreement — Signature Required',
    investmentId: 'pi-001',
    investmentName: 'The Temple',
    type: 'project_thread',
    status: 'active',
    category: 'signatures',
    messageType: 'signature_request',
    priority: 'urgent',
    irMember: IR_TEAM.james,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-10T14:30:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: ['task-001'],
    relatedDocumentIds: ['doc-001'],
    relatedSignatureIds: ['sig-001'],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-004-1',
        conversationId: 'conv-004',
        author: IR_TEAM.james,
        body: 'Your subscription agreement for The Temple Class A units requires your electronic signature. Please review and sign by July 20.',
        messageType: 'signature_request',
        sentAt: '2025-06-28T10:00:00Z',
        isRead: true,
        attachments: [],
        references: [
          { type: 'signature', id: 'sig-001', label: 'Subscription Agreement' },
          { type: 'document', id: 'doc-001', label: 'Temple Subscription Agreement' },
        ],
        isPinned: true,
      }),
      msg({
        id: 'msg-004-2',
        conversationId: 'conv-004',
        author: IR_TEAM.james,
        body: 'Reminder: Signature deadline is approaching in 10 days. Contact us if you need assistance.',
        messageType: 'signature_request',
        sentAt: '2025-07-10T14:30:00Z',
        isRead: false,
        attachments: [],
        references: [{ type: 'task', id: 'task-001', label: 'Sign subscription agreement' }],
        isPinned: false,
      }),
    ],
    timelineEvents: [
      timeline('tl-004-1', 'signature', 'Signature requested', 'Subscription agreement sent for e-signature', '2025-06-28T10:00:00Z', 'sig-001'),
    ],
  }),

  conv({
    id: 'conv-005',
    subject: '309 H Street — Lease-Up Progress',
    investmentId: 'pi-003',
    investmentName: '309 H Street',
    type: 'project_thread',
    status: 'active',
    category: 'project_updates',
    messageType: 'project_update',
    priority: 'normal',
    irMember: IR_TEAM.elena,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-07T15:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: [],
    relatedDocumentIds: ['doc-007'],
    relatedSignatureIds: [],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-005-1',
        conversationId: 'conv-005',
        author: IR_TEAM.elena,
        body: '309 H Street lease-up reached 88% occupancy. Three new commercial tenants signed LOIs this month.',
        messageType: 'project_update',
        sentAt: '2025-07-07T15:00:00Z',
        isRead: false,
        attachments: [attach('att-005', 'H-Street-Lease-Summary.xlsx', 'xlsx', 890_000)],
        references: [{ type: 'investment', id: 'pi-003', label: '309 H Street' }],
        isPinned: false,
      }),
    ],
    timelineEvents: [
      timeline('tl-005-1', 'project_update', 'Lease-up milestone', '88% occupancy achieved', '2025-07-07T15:00:00Z', 'pi-003'),
    ],
  }),

  conv({
    id: 'conv-006',
    subject: 'The Campus — Annual Investor Report',
    investmentId: 'pi-004',
    investmentName: 'The Campus',
    type: 'project_thread',
    status: 'active',
    category: 'financial',
    messageType: 'financial_update',
    priority: 'normal',
    irMember: IR_TEAM.marcus,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-05T12:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: [],
    relatedDocumentIds: ['doc-009'],
    relatedSignatureIds: [],
    relatedDistributionIds: ['dist-004-03'],
    messages: [
      msg({
        id: 'msg-006-1',
        conversationId: 'conv-006',
        author: IR_TEAM.marcus,
        body: 'The Campus 2024 annual investor report is now available. NOI increased 8.2% year-over-year with occupancy at 96%.',
        messageType: 'financial_update',
        sentAt: '2025-07-05T12:00:00Z',
        isRead: true,
        attachments: [attach('att-006', 'Campus-Annual-Report-2024.pdf', 'pdf', 3_145_728)],
        references: [{ type: 'document', id: 'doc-009', label: 'Annual Investor Report' }],
        isPinned: false,
      }),
    ],
    timelineEvents: [],
  }),

  conv({
    id: 'conv-007',
    subject: 'Accreditation Renewal — Documentation Request',
    investmentId: null,
    investmentName: 'Account',
    type: 'support',
    status: 'active',
    category: 'documents',
    messageType: 'document_request',
    priority: 'high',
    irMember: IR_TEAM.james,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-08T09:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: ['task-002'],
    relatedDocumentIds: ['doc-002'],
    relatedSignatureIds: ['sig-002'],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-007-1',
        conversationId: 'conv-007',
        author: IR_TEAM.james,
        body: 'Your accredited investor status renewal is due August 1. Please upload updated financial documentation via the secure portal.',
        messageType: 'document_request',
        sentAt: '2025-06-15T10:00:00Z',
        isRead: true,
        attachments: [],
        references: [{ type: 'task', id: 'task-002', label: 'Upload accreditation docs' }],
        isPinned: false,
      }),
      msg({
        id: 'msg-007-2',
        conversationId: 'conv-007',
        author: INVESTOR_AUTHOR,
        body: 'I will gather the CPA letter and brokerage statements this week.',
        messageType: 'general_support',
        sentAt: '2025-07-08T09:00:00Z',
        isRead: true,
        attachments: [],
        references: [],
        isPinned: false,
      }),
    ],
    timelineEvents: [
      timeline('tl-007-1', 'task', 'Task created', 'Accreditation renewal documentation due', '2025-06-15T10:00:00Z', 'task-002'),
    ],
  }),

  conv({
    id: 'conv-008',
    subject: 'Nelson Avenue — Q2 Distribution & Tax Withholding',
    investmentId: 'pi-005',
    investmentName: 'Nelson Avenue',
    type: 'project_thread',
    status: 'active',
    category: 'financial',
    messageType: 'tax_notice',
    priority: 'normal',
    irMember: IR_TEAM.marcus,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-03T10:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: [],
    relatedDocumentIds: ['doc-011'],
    relatedSignatureIds: [],
    relatedDistributionIds: ['dist-005-03'],
    messages: [
      msg({
        id: 'msg-008-1',
        conversationId: 'conv-008',
        author: IR_TEAM.marcus,
        body: 'Q2 distribution of $8,000 from Nelson Avenue processed with standard tax withholding. K-1 preview attached for your records.',
        messageType: 'tax_notice',
        sentAt: '2025-07-03T10:00:00Z',
        isRead: true,
        attachments: [attach('att-008', 'Nelson-K1-Preview-2025.pdf', 'pdf', 678_912)],
        references: [{ type: 'distribution', id: 'dist-005-03', label: 'Q2 Distribution' }],
        isPinned: false,
      }),
    ],
    timelineEvents: [],
  }),

  conv({
    id: 'conv-009',
    subject: 'H Place Residences — Pre-Construction Update',
    investmentId: 'pi-006',
    investmentName: 'H Place Residences',
    type: 'project_thread',
    status: 'active',
    category: 'project_updates',
    messageType: 'construction_update',
    priority: 'normal',
    irMember: IR_TEAM.elena,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-11T08:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: [],
    relatedDocumentIds: [],
    relatedSignatureIds: [],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-009-1',
        conversationId: 'conv-009',
        author: IR_TEAM.elena,
        body: 'H Place Residences has received final zoning approval. Site preparation begins August 1 with 18% overall progress.',
        messageType: 'construction_update',
        sentAt: '2025-07-11T08:00:00Z',
        isRead: false,
        attachments: [],
        references: [{ type: 'investment', id: 'pi-006', label: 'H Place Residences' }],
        isPinned: false,
      }),
    ],
    timelineEvents: [
      timeline('tl-009-1', 'construction', 'Zoning approved', 'Final zoning clearance received', '2025-07-11T08:00:00Z', 'pi-006'),
    ],
  }),

  conv({
    id: 'conv-010',
    subject: 'Georgetown Row — Construction Progress',
    investmentId: 'pi-009',
    investmentName: 'Georgetown Row',
    type: 'project_thread',
    status: 'active',
    category: 'project_updates',
    messageType: 'construction_update',
    priority: 'low',
    irMember: IR_TEAM.elena,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-06T14:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: [],
    relatedDocumentIds: ['doc-014'],
    relatedSignatureIds: [],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-010-1',
        conversationId: 'conv-010',
        author: IR_TEAM.elena,
        body: 'Georgetown Row exterior masonry is 74% complete. Interior framing on floors 3–5 underway.',
        messageType: 'construction_update',
        sentAt: '2025-07-06T14:00:00Z',
        isRead: true,
        attachments: [attach('att-010', 'Georgetown-Progress-July.jpg', 'jpeg', 1_048_576)],
        references: [{ type: 'investment', id: 'pi-009', label: 'Georgetown Row' }],
        isPinned: false,
      }),
    ],
    timelineEvents: [],
  }),

  conv({
    id: 'conv-011',
    subject: 'Capitol Heights — Fund Launch Announcement',
    investmentId: 'pi-008',
    investmentName: 'Capitol Heights',
    type: 'project_thread',
    status: 'active',
    category: 'announcements',
    messageType: 'announcement',
    priority: 'normal',
    irMember: IR_TEAM.sarah,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-01T09:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: ['task-005'],
    relatedDocumentIds: ['doc-015'],
    relatedSignatureIds: ['sig-003'],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-011-1',
        conversationId: 'conv-011',
        author: IR_TEAM.sarah,
        body: 'Welcome to Capitol Heights Opportunity Zone Fund. Your allocation of $500,000 has been confirmed. Subscription documents are ready for review.',
        messageType: 'announcement',
        sentAt: '2025-07-01T09:00:00Z',
        isRead: false,
        attachments: [],
        references: [
          { type: 'investment', id: 'pi-008', label: 'Capitol Heights' },
          { type: 'signature', id: 'sig-003', label: 'Capitol Heights Subscription' },
        ],
        isPinned: false,
      }),
    ],
    timelineEvents: [
      timeline('tl-011-1', 'project_update', 'Fund launch', 'Capitol Heights allocation confirmed', '2025-07-01T09:00:00Z', 'pi-008'),
    ],
  }),

  conv({
    id: 'conv-012',
    subject: 'Tax Document — K-1 Availability Notice',
    investmentId: 'pi-002',
    investmentName: 'Uniloft',
    type: 'project_thread',
    status: 'active',
    category: 'documents',
    messageType: 'tax_notice',
    priority: 'normal',
    irMember: IR_TEAM.james,
    lastMessagePreview: '',
    lastMessageAt: '2025-06-28T09:15:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: ['task-006'],
    relatedDocumentIds: ['doc-006'],
    relatedSignatureIds: [],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-012-1',
        conversationId: 'conv-012',
        author: IR_TEAM.james,
        body: 'Your 2024 K-1 for Uniloft Residential Partners LP is available for download in the Documents section.',
        messageType: 'tax_notice',
        sentAt: '2025-06-28T09:15:00Z',
        isRead: false,
        attachments: [],
        references: [{ type: 'document', id: 'doc-006', label: '2024 K-1 — Uniloft' }],
        isPinned: false,
      }),
    ],
    timelineEvents: [
      timeline('tl-012-1', 'document', 'K-1 available', '2024 tax document ready for download', '2025-06-28T09:15:00Z', 'doc-006'),
    ],
  }),

  conv({
    id: 'conv-013',
    subject: 'General Support — Portal Access Question',
    investmentId: null,
    investmentName: 'Account',
    type: 'support',
    status: 'active',
    category: 'support',
    messageType: 'general_support',
    priority: 'low',
    irMember: IR_TEAM.marcus,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-02T11:30:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: [],
    relatedDocumentIds: [],
    relatedSignatureIds: [],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-013-1',
        conversationId: 'conv-013',
        author: INVESTOR_AUTHOR,
        body: 'Can I add a secondary authorized viewer to my portal account for my CFO?',
        messageType: 'general_support',
        sentAt: '2025-07-01T16:00:00Z',
        isRead: true,
        attachments: [],
        references: [],
        isPinned: false,
      }),
      msg({
        id: 'msg-013-2',
        conversationId: 'conv-013',
        author: IR_TEAM.marcus,
        body: 'Yes — we support read-only delegate access. I have sent the authorization form to your email on file (e***@whitmorecapital.com).',
        messageType: 'general_support',
        sentAt: '2025-07-02T11:30:00Z',
        isRead: true,
        attachments: [attach('att-013', 'Delegate-Authorization-Form.pdf', 'pdf', 156_672)],
        references: [],
        isPinned: false,
      }),
    ],
    timelineEvents: [],
  }),

  conv({
    id: 'conv-014',
    subject: 'Riverside Flip Fund — Exit Summary',
    investmentId: 'pi-007',
    investmentName: 'Riverside Flip Fund III',
    type: 'project_thread',
    status: 'closed',
    category: 'financial',
    messageType: 'financial_update',
    priority: 'normal',
    irMember: IR_TEAM.marcus,
    lastMessagePreview: '',
    lastMessageAt: '2024-11-20T16:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: [],
    relatedDocumentIds: ['doc-012'],
    relatedSignatureIds: [],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-014-1',
        conversationId: 'conv-014',
        author: IR_TEAM.marcus,
        body: 'Riverside Flip Fund III has successfully exited with a 42% ROI. Final distribution of $497,000 has been processed.',
        messageType: 'financial_update',
        sentAt: '2024-11-20T16:00:00Z',
        isRead: true,
        attachments: [attach('att-014', 'Riverside-Exit-Summary.pdf', 'pdf', 892_160)],
        references: [{ type: 'investment', id: 'pi-007', label: 'Riverside Flip Fund III' }],
        isPinned: false,
      }),
    ],
    timelineEvents: [
      timeline('tl-014-1', 'distribution', 'Final distribution', 'Exit proceeds of $497,000 distributed', '2024-11-20T16:00:00Z', 'pi-007'),
    ],
  }),

  conv({
    id: 'conv-015',
    subject: 'Legal Notice — Updated Operating Agreement',
    investmentId: 'pi-004',
    investmentName: 'The Campus',
    type: 'project_thread',
    status: 'active',
    category: 'documents',
    messageType: 'legal_notice',
    priority: 'high',
    irMember: IR_TEAM.james,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-13T10:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: ['task-007'],
    relatedDocumentIds: ['doc-010'],
    relatedSignatureIds: ['sig-004'],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-015-1',
        conversationId: 'conv-015',
        author: IR_TEAM.james,
        body: 'An amended operating agreement for The Campus Mixed-Use Fund requires your review and signature by July 25.',
        messageType: 'legal_notice',
        sentAt: '2025-07-13T10:00:00Z',
        isRead: false,
        attachments: [],
        references: [
          { type: 'document', id: 'doc-010', label: 'Amended Operating Agreement' },
          { type: 'signature', id: 'sig-004', label: 'Operating Agreement Amendment' },
        ],
        isPinned: false,
      }),
    ],
    timelineEvents: [],
  }),

  conv({
    id: 'conv-016',
    subject: 'Lakeside Fund — Q2 Investor Update Review',
    investmentId: 'pi-003',
    investmentName: '309 H Street',
    type: 'project_thread',
    status: 'active',
    category: 'inbox',
    messageType: 'project_update',
    priority: 'normal',
    irMember: IR_TEAM.sarah,
    lastMessagePreview: '',
    lastMessageAt: '2025-07-15T09:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: ['task-003'],
    relatedDocumentIds: ['doc-008'],
    relatedSignatureIds: [],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-016-1',
        conversationId: 'conv-016',
        author: IR_TEAM.sarah,
        body: 'Please review the Q2 investor update for 309 H Street. Key highlights include lease-up progress and revised exit timeline.',
        messageType: 'project_update',
        sentAt: '2025-07-15T09:00:00Z',
        isRead: false,
        attachments: [attach('att-016', 'Q2-Investor-Update-H-Street.pdf', 'pdf', 1_234_567)],
        references: [{ type: 'task', id: 'task-003', label: 'Review Q2 investor update' }],
        isPinned: false,
      }),
    ],
    timelineEvents: [],
  }),

  conv({
    id: 'conv-017',
    subject: 'Platform Maintenance — Scheduled Downtime',
    investmentId: null,
    investmentName: 'Platform',
    type: 'announcement',
    status: 'archived',
    category: 'archived',
    messageType: 'system_notification',
    priority: 'low',
    irMember: IR_TEAM.system,
    lastMessagePreview: '',
    lastMessageAt: '2025-06-20T08:00:00Z',
    unreadCount: 0,
    hasAttachments: false,
    isStarred: false,
    relatedTaskIds: [],
    relatedDocumentIds: [],
    relatedSignatureIds: [],
    relatedDistributionIds: [],
    messages: [
      msg({
        id: 'msg-017-1',
        conversationId: 'conv-017',
        author: IR_TEAM.system,
        body: 'Investor portal maintenance scheduled June 22, 2025 from 2:00–4:00 AM ET. All services restored successfully.',
        messageType: 'system_notification',
        sentAt: '2025-06-20T08:00:00Z',
        isRead: true,
        attachments: [],
        references: [],
        isPinned: false,
      }),
    ],
    timelineEvents: [],
  }),
];

export function getAllConversations(): Conversation[] {
  return conversations.map((c) => ({ ...c, messages: [...c.messages] }));
}

export function getConversationById(id: string): Conversation | undefined {
  const found = conversations.find((c) => c.id === id);
  if (!found) return undefined;
  return { ...found, messages: [...found.messages], timelineEvents: [...found.timelineEvents] };
}

export function getVisibleMessages(conversation: Conversation): Message[] {
  return conversation.messages.filter((m) => !m.isInternal);
}

export const IR_TEAM_MEMBERS = IR_TEAM;
