import { getAllInvestments } from './investments';
import type {
  DocumentActivity,
  DocumentVersion,
  InvestorDocument,
} from './document-types';

function version(
  id: string,
  versionNumber: number,
  uploadedAt: string,
  fileSizeBytes: number,
  isCurrent: boolean,
): DocumentVersion {
  return {
    id,
    versionNumber,
    uploadedAt,
    uploadedBy: 'Investhome Operations',
    fileSizeBytes,
    changeNotes: versionNumber > 1 ? 'Updated per investor request' : null,
    isCurrent,
  };
}

function activity(
  id: string,
  timestamp: string,
  action: DocumentActivity['action'],
  description: string,
): DocumentActivity {
  return {
    id,
    timestamp,
    actor: action === 'uploaded' ? 'Investhome Operations' : 'Eleanor Whitmore',
    action,
    description,
  };
}

function doc(
  partial: Omit<
    InvestorDocument,
    'investmentName' | 'entityName' | 'versions' | 'activity'
  > & {
    versions?: DocumentVersion[];
    activity?: DocumentActivity[];
  },
): InvestorDocument {
  const inv = getAllInvestments().find((i) => i.id === partial.investmentId);
  const uploadedAt = partial.uploadedAt;
  return {
    ...partial,
    investmentName: inv?.projectName ?? 'Unknown Investment',
    entityName: inv?.entityName ?? 'Unknown Entity',
    versions: partial.versions ?? [
      version(`${partial.id}-v1`, 1, uploadedAt, partial.fileSizeBytes, true),
    ],
    activity: partial.activity ?? [
      activity(`${partial.id}-a1`, uploadedAt, 'uploaded', 'Document uploaded to investor portal'),
    ],
  };
}

const documents: InvestorDocument[] = [
  doc({
    id: 'doc-001',
    title: 'Subscription Agreement — Class A Units',
    description: 'Primary subscription agreement for The Temple development investment.',
    investmentId: 'pi-001',
    category: 'subscription',
    documentType: 'subscription_agreement',
    status: 'pending_signature',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Temple-Subscription-Agreement.pdf',
    fileSizeBytes: 2_458_880,
    pageCount: 42,
    uploadedAt: '2025-06-28T10:00:00Z',
    updatedAt: '2025-07-10T14:30:00Z',
    expiresAt: '2025-08-15',
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-001',
    distributionStatementId: null,
    distributionId: null,
    tags: ['required', 'signature_needed'],
    relatedDocumentIds: ['doc-002', 'doc-003'],
  }),
  doc({
    id: 'doc-002',
    title: 'Operating Agreement — Temple Holdings LLC',
    description: 'Amended and restated operating agreement.',
    investmentId: 'pi-001',
    category: 'legal',
    documentType: 'operating_agreement',
    status: 'viewed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Temple-Operating-Agreement.pdf',
    fileSizeBytes: 1_892_160,
    pageCount: 68,
    uploadedAt: '2025-06-15T09:00:00Z',
    updatedAt: '2025-07-05T11:00:00Z',
    expiresAt: null,
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['required'],
    relatedDocumentIds: ['doc-001'],
  }),
  doc({
    id: 'doc-003',
    title: 'Side Letter — Co-Investment Rights',
    description: 'Side letter granting co-investment rights on future Temple offerings.',
    investmentId: 'pi-001',
    category: 'legal',
    documentType: 'side_letter',
    status: 'signed',
    accessLevel: 'restricted',
    fileType: 'pdf',
    fileName: 'Temple-Side-Letter.pdf',
    fileSizeBytes: 524_288,
    pageCount: 8,
    uploadedAt: '2023-04-10T08:00:00Z',
    updatedAt: '2023-04-12T16:00:00Z',
    expiresAt: null,
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-010',
    distributionStatementId: null,
    distributionId: null,
    tags: [],
    relatedDocumentIds: ['doc-001'],
  }),
  doc({
    id: 'doc-004',
    title: 'Form W-9 — Tax Identification',
    description: 'IRS Form W-9 for tax reporting purposes.',
    investmentId: 'pi-001',
    category: 'tax',
    documentType: 'w9',
    status: 'new',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'W9-Whitmore-Capital.pdf',
    fileSizeBytes: 156_672,
    pageCount: 2,
    uploadedAt: '2025-07-01T12:00:00Z',
    updatedAt: '2025-07-01T12:00:00Z',
    expiresAt: '2025-12-31',
    taxYear: 2025,
    isRead: false,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-002',
    distributionStatementId: null,
    distributionId: null,
    tags: ['required', 'tax_season', 'signature_needed'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-005',
    title: 'Schedule K-1 — Tax Year 2024',
    description: 'Partnership Schedule K-1 for The Temple investment.',
    investmentId: 'pi-001',
    category: 'tax',
    documentType: 'k1',
    status: 'viewed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Temple-K1-2024.pdf',
    fileSizeBytes: 389_120,
    pageCount: 6,
    uploadedAt: '2025-03-15T10:00:00Z',
    updatedAt: '2025-03-20T09:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['tax_season', 'annual'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-006',
    title: 'Q2 2025 Investor Update',
    description: 'Quarterly construction progress and financial update.',
    investmentId: 'pi-001',
    category: 'report',
    documentType: 'investor_update',
    status: 'new',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: 'Temple-Q2-2025-Update.pdf',
    fileSizeBytes: 4_194_304,
    pageCount: 24,
    uploadedAt: '2025-07-10T08:00:00Z',
    updatedAt: '2025-07-10T08:00:00Z',
    expiresAt: null,
    taxYear: 2025,
    isRead: false,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['quarterly'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-007',
    title: 'Subscription Agreement — Uniloft LP',
    description: 'Limited partnership subscription agreement.',
    investmentId: 'pi-002',
    category: 'subscription',
    documentType: 'subscription_agreement',
    status: 'signed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Uniloft-Subscription.pdf',
    fileSizeBytes: 2_097_152,
    pageCount: 38,
    uploadedAt: '2021-08-15T10:00:00Z',
    updatedAt: '2021-08-20T14:00:00Z',
    expiresAt: null,
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-011',
    distributionStatementId: null,
    distributionId: null,
    tags: [],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-008',
    title: 'Schedule K-1 — Tax Year 2024',
    description: 'Partnership Schedule K-1 for Uniloft Residential Partners LP.',
    investmentId: 'pi-002',
    category: 'tax',
    documentType: 'k1',
    status: 'viewed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Uniloft-K1-2024.pdf',
    fileSizeBytes: 412_672,
    pageCount: 7,
    uploadedAt: '2025-03-10T09:00:00Z',
    updatedAt: '2025-03-18T11:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['tax_season', 'annual'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-009',
    title: 'Q2 2025 Distribution Statement',
    description: 'Distribution statement for Q2 2025 preferred return payment.',
    investmentId: 'pi-002',
    category: 'financial',
    documentType: 'distribution_statement',
    status: 'viewed',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: 'Uniloft-DIST-2025Q2-Statement.pdf',
    fileSizeBytes: 245_760,
    pageCount: 3,
    uploadedAt: '2025-06-30T16:00:00Z',
    updatedAt: '2025-07-02T10:00:00Z',
    expiresAt: null,
    taxYear: 2025,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: 'stmt-uniloft-q2-2025',
    distributionId: 'dist-002-q2-2025',
    tags: ['quarterly'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-010',
    title: 'Annual Report 2024',
    description: 'Comprehensive annual performance report.',
    investmentId: 'pi-002',
    category: 'report',
    documentType: 'annual_report',
    status: 'viewed',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: 'Uniloft-Annual-Report-2024.pdf',
    fileSizeBytes: 6_291_456,
    pageCount: 52,
    uploadedAt: '2025-02-28T10:00:00Z',
    updatedAt: '2025-03-05T09:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['annual'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-011',
    title: 'Property Insurance Certificate',
    description: 'Current property insurance coverage certificate.',
    investmentId: 'pi-002',
    category: 'insurance',
    documentType: 'insurance_certificate',
    status: 'viewed',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: 'Uniloft-Insurance-Cert-2025.pdf',
    fileSizeBytes: 189_440,
    pageCount: 4,
    uploadedAt: '2025-01-15T08:00:00Z',
    updatedAt: '2025-01-15T08:00:00Z',
    expiresAt: '2026-01-15',
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['annual'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-012',
    title: 'Subscription Agreement — 309 H Street',
    description: 'Equity subscription for H Street Development Co.',
    investmentId: 'pi-003',
    category: 'subscription',
    documentType: 'subscription_agreement',
    status: 'signed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: '309H-Subscription.pdf',
    fileSizeBytes: 1_835_008,
    pageCount: 36,
    uploadedAt: '2022-11-01T10:00:00Z',
    updatedAt: '2022-11-05T15:00:00Z',
    expiresAt: null,
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-012',
    distributionStatementId: null,
    distributionId: null,
    tags: [],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-013',
    title: 'Schedule K-1 — Tax Year 2024',
    description: 'Partnership Schedule K-1 for 309 H Street.',
    investmentId: 'pi-003',
    category: 'tax',
    documentType: 'k1',
    status: 'new',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: '309H-K1-2024.pdf',
    fileSizeBytes: 378_880,
    pageCount: 6,
    uploadedAt: '2025-03-20T10:00:00Z',
    updatedAt: '2025-03-20T10:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: false,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['tax_season', 'annual'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-014',
    title: 'Q1 2025 Distribution Statement',
    description: 'Distribution statement for Q1 2025 profit share.',
    investmentId: 'pi-003',
    category: 'financial',
    documentType: 'distribution_statement',
    status: 'viewed',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: '309H-DIST-2025Q1-Statement.pdf',
    fileSizeBytes: 212_992,
    pageCount: 2,
    uploadedAt: '2025-03-31T14:00:00Z',
    updatedAt: '2025-04-01T09:00:00Z',
    expiresAt: null,
    taxYear: 2025,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: 'stmt-309h-q1-2025',
    distributionId: 'dist-003-q1-2025',
    tags: ['quarterly'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-015',
    title: 'Accredited Investor Verification Letter',
    description: 'Third-party verification of accredited investor status.',
    investmentId: 'pi-003',
    category: 'compliance',
    documentType: 'accreditation_letter',
    status: 'expired',
    accessLevel: 'restricted',
    fileType: 'pdf',
    fileName: 'Accreditation-Letter-2023.pdf',
    fileSizeBytes: 98_304,
    pageCount: 2,
    uploadedAt: '2023-10-01T10:00:00Z',
    updatedAt: '2023-10-01T10:00:00Z',
    expiresAt: '2025-06-30',
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['required'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-016',
    title: 'Subscription Agreement — Campus Mixed-Use Fund I',
    description: 'Fund subscription agreement for The Campus investment.',
    investmentId: 'pi-004',
    category: 'subscription',
    documentType: 'subscription_agreement',
    status: 'signed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Campus-Subscription.pdf',
    fileSizeBytes: 2_621_440,
    pageCount: 44,
    uploadedAt: '2020-06-10T10:00:00Z',
    updatedAt: '2020-06-15T16:00:00Z',
    expiresAt: null,
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-013',
    distributionStatementId: null,
    distributionId: null,
    tags: [],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-017',
    title: 'Schedule K-1 — Tax Year 2024',
    description: 'Partnership Schedule K-1 for Campus Mixed-Use Fund I.',
    investmentId: 'pi-004',
    category: 'tax',
    documentType: 'k1',
    status: 'viewed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Campus-K1-2024.pdf',
    fileSizeBytes: 445_440,
    pageCount: 8,
    uploadedAt: '2025-03-05T09:00:00Z',
    updatedAt: '2025-03-12T11:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['tax_season', 'annual'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-018',
    title: 'Form 1099-DIV — Tax Year 2024',
    description: '1099 dividend income reporting form.',
    investmentId: 'pi-004',
    category: 'tax',
    documentType: '1099',
    status: 'viewed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Campus-1099-2024.pdf',
    fileSizeBytes: 112_640,
    pageCount: 2,
    uploadedAt: '2025-01-31T10:00:00Z',
    updatedAt: '2025-02-05T09:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['tax_season', 'annual'],
    relatedDocumentIds: ['doc-017'],
  }),
  doc({
    id: 'doc-019',
    title: 'Q2 2025 Distribution Statement',
    description: 'Semi-annual distribution statement.',
    investmentId: 'pi-004',
    category: 'financial',
    documentType: 'distribution_statement',
    status: 'viewed',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: 'Campus-DIST-2025H1-Statement.pdf',
    fileSizeBytes: 278_528,
    pageCount: 4,
    uploadedAt: '2025-06-15T14:00:00Z',
    updatedAt: '2025-06-16T10:00:00Z',
    expiresAt: null,
    taxYear: 2025,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: 'stmt-campus-h1-2025',
    distributionId: 'dist-004-h1-2025',
    tags: ['quarterly'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-020',
    title: 'Property Appraisal — 2024',
    description: 'Independent third-party property appraisal.',
    investmentId: 'pi-004',
    category: 'financial',
    documentType: 'appraisal',
    status: 'viewed',
    accessLevel: 'restricted',
    fileType: 'pdf',
    fileName: 'Campus-Appraisal-2024.pdf',
    fileSizeBytes: 3_670_016,
    pageCount: 28,
    uploadedAt: '2024-12-15T10:00:00Z',
    updatedAt: '2024-12-15T10:00:00Z',
    expiresAt: '2025-12-15',
    taxYear: 2024,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['annual'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-021',
    title: 'Subscription Agreement — Nelson Avenue',
    description: 'Equity subscription for Nelson Avenue Equity LLC.',
    investmentId: 'pi-005',
    category: 'subscription',
    documentType: 'subscription_agreement',
    status: 'signed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Nelson-Subscription.pdf',
    fileSizeBytes: 1_572_864,
    pageCount: 32,
    uploadedAt: '2019-03-18T10:00:00Z',
    updatedAt: '2019-03-22T14:00:00Z',
    expiresAt: null,
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-014',
    distributionStatementId: null,
    distributionId: null,
    tags: [],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-022',
    title: 'Schedule K-1 — Tax Year 2024',
    description: 'Partnership Schedule K-1 for Nelson Avenue.',
    investmentId: 'pi-005',
    category: 'tax',
    documentType: 'k1',
    status: 'viewed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Nelson-K1-2024.pdf',
    fileSizeBytes: 356_352,
    pageCount: 6,
    uploadedAt: '2025-03-08T09:00:00Z',
    updatedAt: '2025-03-15T10:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['tax_season', 'annual'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-023',
    title: 'Capital Call Notice — Tranche 2',
    description: 'Notice of capital call for H Place Residences pre-construction.',
    investmentId: 'pi-006',
    category: 'financial',
    documentType: 'capital_call_notice',
    status: 'pending_signature',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: 'HPlace-Capital-Call-2.pdf',
    fileSizeBytes: 167_936,
    pageCount: 3,
    uploadedAt: '2025-07-05T10:00:00Z',
    updatedAt: '2025-07-08T14:00:00Z',
    expiresAt: '2025-07-25',
    taxYear: 2025,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-003',
    distributionStatementId: null,
    distributionId: null,
    tags: ['required', 'signature_needed'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-024',
    title: 'Subscription Agreement — H Place Condominium Fund',
    description: 'Fund subscription agreement for H Place Residences.',
    investmentId: 'pi-006',
    category: 'subscription',
    documentType: 'subscription_agreement',
    status: 'signed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'HPlace-Subscription.pdf',
    fileSizeBytes: 2_228_224,
    pageCount: 40,
    uploadedAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-02-28T16:00:00Z',
    expiresAt: null,
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-015',
    distributionStatementId: null,
    distributionId: null,
    tags: [],
    relatedDocumentIds: ['doc-023'],
  }),
  doc({
    id: 'doc-025',
    title: 'Construction Progress Report — June 2025',
    description: 'Monthly construction progress with photos and budget update.',
    investmentId: 'pi-006',
    category: 'report',
    documentType: 'investor_update',
    status: 'new',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: 'HPlace-Progress-June-2025.pdf',
    fileSizeBytes: 5_242_880,
    pageCount: 18,
    uploadedAt: '2025-07-01T08:00:00Z',
    updatedAt: '2025-07-01T08:00:00Z',
    expiresAt: null,
    taxYear: 2025,
    isRead: false,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['quarterly'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-026',
    title: 'Final Distribution Statement — Exit',
    description: 'Final distribution statement upon fund exit.',
    investmentId: 'pi-007',
    category: 'financial',
    documentType: 'distribution_statement',
    status: 'viewed',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: 'Riverside-Exit-Statement.pdf',
    fileSizeBytes: 334_848,
    pageCount: 5,
    uploadedAt: '2024-11-20T16:00:00Z',
    updatedAt: '2024-11-22T10:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: 'stmt-riverside-exit',
    distributionId: 'dist-007-exit',
    tags: [],
    relatedDocumentIds: ['doc-027'],
  }),
  doc({
    id: 'doc-027',
    title: 'Schedule K-1 — Tax Year 2024 (Final)',
    description: 'Final Schedule K-1 upon fund exit.',
    investmentId: 'pi-007',
    category: 'tax',
    documentType: 'k1',
    status: 'viewed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Riverside-K1-2024-Final.pdf',
    fileSizeBytes: 401_408,
    pageCount: 7,
    uploadedAt: '2025-02-15T10:00:00Z',
    updatedAt: '2025-02-20T09:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['tax_season', 'annual'],
    relatedDocumentIds: ['doc-026'],
  }),
  doc({
    id: 'doc-028',
    title: 'Exit Summary Report',
    description: 'Comprehensive exit summary with returns analysis.',
    investmentId: 'pi-007',
    category: 'report',
    documentType: 'annual_report',
    status: 'viewed',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: 'Riverside-Exit-Summary.pdf',
    fileSizeBytes: 2_883_584,
    pageCount: 22,
    uploadedAt: '2024-11-25T10:00:00Z',
    updatedAt: '2024-11-25T10:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: true,
    isArchived: true,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['annual'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-029',
    title: 'Subscription Agreement — Capitol Heights OZ Fund',
    description: 'Opportunity zone fund subscription agreement (pending investment).',
    investmentId: 'pi-008',
    category: 'subscription',
    documentType: 'subscription_agreement',
    status: 'pending_signature',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'CapitolHeights-Subscription.pdf',
    fileSizeBytes: 2_359_296,
    pageCount: 46,
    uploadedAt: '2025-07-08T10:00:00Z',
    updatedAt: '2025-07-12T14:00:00Z',
    expiresAt: '2025-08-30',
    taxYear: null,
    isRead: false,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-004',
    distributionStatementId: null,
    distributionId: null,
    tags: ['required', 'signature_needed'],
    relatedDocumentIds: ['doc-030'],
  }),
  doc({
    id: 'doc-030',
    title: 'Investor Questionnaire & Suitability Form',
    description: 'Pre-investment suitability and accreditation questionnaire.',
    investmentId: 'pi-008',
    category: 'compliance',
    documentType: 'consent_form',
    status: 'new',
    accessLevel: 'restricted',
    fileType: 'pdf',
    fileName: 'CapitolHeights-Questionnaire.pdf',
    fileSizeBytes: 445_440,
    pageCount: 12,
    uploadedAt: '2025-07-08T10:00:00Z',
    updatedAt: '2025-07-08T10:00:00Z',
    expiresAt: '2025-08-30',
    taxYear: null,
    isRead: false,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-005',
    distributionStatementId: null,
    distributionId: null,
    tags: ['required', 'signature_needed'],
    relatedDocumentIds: ['doc-029'],
  }),
  doc({
    id: 'doc-031',
    title: 'NDA — Capitol Heights Offering',
    description: 'Non-disclosure agreement for offering materials.',
    investmentId: 'pi-008',
    category: 'legal',
    documentType: 'nda',
    status: 'signed',
    accessLevel: 'restricted',
    fileType: 'pdf',
    fileName: 'CapitolHeights-NDA.pdf',
    fileSizeBytes: 143_360,
    pageCount: 4,
    uploadedAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-06-03T14:00:00Z',
    expiresAt: '2026-06-01',
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-016',
    distributionStatementId: null,
    distributionId: null,
    tags: [],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-032',
    title: 'Subscription Agreement — Georgetown Row',
    description: 'Equity subscription for Georgetown Heritage REIT.',
    investmentId: 'pi-009',
    category: 'subscription',
    documentType: 'subscription_agreement',
    status: 'signed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Georgetown-Subscription.pdf',
    fileSizeBytes: 1_966_080,
    pageCount: 34,
    uploadedAt: '2023-07-12T10:00:00Z',
    updatedAt: '2023-07-18T16:00:00Z',
    expiresAt: null,
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-017',
    distributionStatementId: null,
    distributionId: null,
    tags: [],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-033',
    title: 'Schedule K-1 — Tax Year 2024',
    description: 'Partnership Schedule K-1 for Georgetown Row.',
    investmentId: 'pi-009',
    category: 'tax',
    documentType: 'k1',
    status: 'viewed',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Georgetown-K1-2024.pdf',
    fileSizeBytes: 367_616,
    pageCount: 6,
    uploadedAt: '2025-03-18T09:00:00Z',
    updatedAt: '2025-03-25T10:00:00Z',
    expiresAt: null,
    taxYear: 2024,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['tax_season', 'annual'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-034',
    title: 'Wire Instructions Acknowledgment',
    description: 'Acknowledgment of wire transfer instructions (masked account details).',
    investmentId: 'pi-009',
    category: 'financial',
    documentType: 'wire_instructions',
    status: 'pending_signature',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Georgetown-Wire-Ack.pdf',
    fileSizeBytes: 89_088,
    pageCount: 1,
    uploadedAt: '2025-07-12T10:00:00Z',
    updatedAt: '2025-07-14T09:00:00Z',
    expiresAt: '2025-07-31',
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-006',
    distributionStatementId: null,
    distributionId: null,
    tags: ['required', 'signature_needed'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-035',
    title: 'Q1 2025 Investor Update',
    description: 'Quarterly construction and leasing update.',
    investmentId: 'pi-009',
    category: 'report',
    documentType: 'investor_update',
    status: 'viewed',
    accessLevel: 'standard',
    fileType: 'pdf',
    fileName: 'Georgetown-Q1-2025-Update.pdf',
    fileSizeBytes: 3_407_872,
    pageCount: 16,
    uploadedAt: '2025-04-15T08:00:00Z',
    updatedAt: '2025-04-20T10:00:00Z',
    expiresAt: null,
    taxYear: 2025,
    isRead: true,
    isArchived: false,
    requiresSignature: false,
    signatureRequestId: null,
    distributionStatementId: null,
    distributionId: null,
    tags: ['quarterly'],
    relatedDocumentIds: [],
  }),
  doc({
    id: 'doc-036',
    title: 'Amendment No. 2 — Operating Agreement',
    description: 'Second amendment to Georgetown Heritage REIT operating agreement.',
    investmentId: 'pi-009',
    category: 'legal',
    documentType: 'amendment',
    status: 'pending_signature',
    accessLevel: 'confidential',
    fileType: 'pdf',
    fileName: 'Georgetown-Amendment-2.pdf',
    fileSizeBytes: 234_496,
    pageCount: 6,
    uploadedAt: '2025-06-20T10:00:00Z',
    updatedAt: '2025-07-01T14:00:00Z',
    expiresAt: '2025-08-15',
    taxYear: null,
    isRead: true,
    isArchived: false,
    requiresSignature: true,
    signatureRequestId: 'sig-007',
    distributionStatementId: null,
    distributionId: null,
    tags: ['signature_needed'],
    relatedDocumentIds: ['doc-032'],
  }),
];

export function getAllDocuments(): InvestorDocument[] {
  return [...documents].sort(
    (a, b) => new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime(),
  );
}

export function getDocumentById(id: string): InvestorDocument | undefined {
  return documents.find((d) => d.id === id);
}

export function getDocumentsByInvestmentId(investmentId: string): InvestorDocument[] {
  return documents.filter((d) => d.investmentId === investmentId);
}

export const DOCUMENT_CATEGORY_LABELS: Record<
  import('./document-types').DocumentCategory,
  string
> = {
  subscription: 'Subscription',
  tax: 'Tax',
  financial: 'Financial',
  legal: 'Legal',
  report: 'Reports',
  insurance: 'Insurance',
  compliance: 'Compliance',
  correspondence: 'Correspondence',
  signature: 'Signature',
};

export const DOCUMENT_TYPE_LABELS: Record<
  import('./document-types').DocumentType,
  string
> = {
  subscription_agreement: 'Subscription Agreement',
  operating_agreement: 'Operating Agreement',
  side_letter: 'Side Letter',
  w9: 'Form W-9',
  k1: 'Schedule K-1',
  '1099': 'Form 1099',
  accreditation_letter: 'Accreditation Letter',
  investor_update: 'Investor Update',
  quarterly_report: 'Quarterly Report',
  annual_report: 'Annual Report',
  capital_call_notice: 'Capital Call Notice',
  distribution_statement: 'Distribution Statement',
  insurance_certificate: 'Insurance Certificate',
  title_report: 'Title Report',
  appraisal: 'Appraisal',
  amendment: 'Amendment',
  consent_form: 'Consent Form',
  nda: 'NDA',
  wire_instructions: 'Wire Instructions',
  other: 'Other',
};

export const DOCUMENT_STATUS_LABELS: Record<
  import('./document-types').DocumentStatus,
  string
> = {
  new: 'New',
  viewed: 'Viewed',
  signed: 'Signed',
  pending_signature: 'Pending Signature',
  archived: 'Archived',
  expired: 'Expired',
};
