import type { InvestorNotificationItem } from './messaging-types';

export const investorNotificationCenter: InvestorNotificationItem[] = [
  {
    id: 'inc-001',
    title: 'Unread message from Sarah Chen',
    message: 'Q3 portfolio review agenda attached — please confirm attendance.',
    category: 'message',
    timestamp: '2025-07-14T16:30:00Z',
    isRead: false,
    isDismissed: false,
    priority: 'high',
    actionLabel: 'Open conversation',
    actionHref: '/investor/messages/conv-001',
    relatedId: 'conv-001',
  },
  {
    id: 'inc-002',
    title: 'Signature required',
    message: 'The Temple subscription agreement awaits your e-signature by July 20.',
    category: 'signature',
    timestamp: '2025-07-10T14:30:00Z',
    isRead: false,
    isDismissed: false,
    priority: 'urgent',
    actionLabel: 'Review & sign',
    actionHref: '/investor/documents',
    relatedId: 'sig-001',
  },
  {
    id: 'inc-003',
    title: 'Upcoming distribution',
    message: 'Uniloft Q3 distribution of $17,000 scheduled for September 30.',
    category: 'distribution',
    timestamp: '2025-07-10T08:00:00Z',
    isRead: false,
    isDismissed: false,
    priority: 'normal',
    actionLabel: 'View distribution',
    actionHref: '/investor/distributions',
    relatedId: 'dist-002-05',
  },
  {
    id: 'inc-004',
    title: 'Task due today',
    message: 'Review Q2 investor update for 309 H Street is due today.',
    category: 'task',
    timestamp: '2025-07-15T08:00:00Z',
    isRead: false,
    isDismissed: false,
    priority: 'high',
    actionLabel: 'View task',
    actionHref: '/investor/tasks/task-003',
    relatedId: 'task-003',
  },
  {
    id: 'inc-005',
    title: 'K-1 document available',
    message: '2024 K-1 for Uniloft is ready for download.',
    category: 'tax',
    timestamp: '2025-06-28T09:15:00Z',
    isRead: true,
    isDismissed: false,
    priority: 'normal',
    actionLabel: 'Download',
    actionHref: '/investor/documents',
    relatedId: 'doc-006',
  },
  {
    id: 'inc-006',
    title: 'Construction milestone',
    message: 'The Temple structural steel installation complete — 62% progress.',
    category: 'investment',
    timestamp: '2025-07-08T10:00:00Z',
    isRead: true,
    isDismissed: false,
    priority: 'normal',
    actionLabel: 'View update',
    actionHref: '/investor/messages/conv-002',
    relatedId: 'pi-001',
  },
  {
    id: 'inc-007',
    title: 'Accreditation renewal reminder',
    message: 'Upload updated accreditation documentation by August 1.',
    category: 'compliance',
    timestamp: '2025-07-08T09:00:00Z',
    isRead: false,
    isDismissed: false,
    priority: 'high',
    actionLabel: 'View task',
    actionHref: '/investor/tasks/task-002',
    relatedId: 'task-002',
  },
  {
    id: 'inc-008',
    title: 'Legal notice — operating agreement',
    message: 'Amended operating agreement for The Campus requires signature by July 25.',
    category: 'document',
    timestamp: '2025-07-13T10:00:00Z',
    isRead: false,
    isDismissed: false,
    priority: 'high',
    actionLabel: 'Review document',
    actionHref: '/investor/messages/conv-015',
    relatedId: 'conv-015',
  },
  {
    id: 'inc-009',
    title: 'New announcement',
    message: 'Q3 2025 Investor Portal Enhancements now live.',
    category: 'system',
    timestamp: '2025-07-10T09:00:00Z',
    isRead: true,
    isDismissed: false,
    priority: 'low',
    actionLabel: 'Read announcement',
    actionHref: '/investor/messages',
    relatedId: 'ann-001',
  },
  {
    id: 'inc-010',
    title: 'Capitol Heights allocation confirmed',
    message: 'Your $500,000 allocation to Capitol Heights has been confirmed.',
    category: 'investment',
    timestamp: '2025-07-01T09:00:00Z',
    isRead: true,
    isDismissed: true,
    priority: 'normal',
    actionLabel: 'View investment',
    actionHref: '/investor/investments/pi-008',
    relatedId: 'pi-008',
  },
];

export function getAllInvestorNotifications(): InvestorNotificationItem[] {
  return [...investorNotificationCenter];
}

export function getInvestorNotificationById(id: string): InvestorNotificationItem | undefined {
  return investorNotificationCenter.find((n) => n.id === id);
}
