export const PERSON_CARD_COPY = {
  tr: {
    title: 'Kişi Kartı',
    back: 'Kişilere dön',
    tabs: {
      overview: 'Genel',
      purchases: 'Satın Almalar',
      history: 'İletişim',
      documents: 'Belgeler',
      tasks: 'Görevler',
    },
    loadError: 'Kişi yüklenemedi',
    accessDenied: 'Erişim yok',
    saved: 'Kaydedildi',
    save: 'Kaydet',
    saving: 'Kaydediliyor…',
    saveFailed: 'Kaydedilemedi',
    cancel: 'İptal',
    edit: 'Düzenle',
    editPerson: 'Kişiyi Düzenle',
    email: 'E-posta',
    whatsapp: 'WhatsApp',
    message: 'Mesaj',
    meeting: 'Toplantı',
    more: 'Diğer',
    assignOwner: 'Sorumlu Ata',
    createTask: 'Görev Oluştur',
    moveToJunk: "Junk'a taşı",
    junkStatus: 'Durum: Junk',
    junkReason: 'Junk Sebebi',
    agent: 'Acenta',
    active: 'Aktif',
    passive: 'Pasif',
    junk: 'Junk',
    addComment: 'Yorum Ekle',
    comment: 'Yorum',
    type: 'Tür',
    datetime: 'Tarih / saat',
    createFollowUp: 'Takip görevi oluştur',
    followUpDate: 'Takip tarihi',
    yes: 'Evet',
    no: 'Hayır',
    saveComment: 'Yorumu kaydet',
    task: 'Görev',
    description: 'Açıklama',
    assignee: 'Sorumlu',
    date: 'Tarih',
    status: 'Durum',
    saveTask: 'Görevi kaydet',
    currentOwner: 'Mevcut sorumlu',
    newOwner: 'Yeni sorumlu',
    selectUser: 'Kullanıcı seç',
    saveAssignment: 'Atamayı kaydet',
    select: 'Seçin',
    general: 'Genel Bilgiler',
    purchases: 'Satın Almalar',
    tasksHeading: 'Görevler',
    tasksPlan: 'Görevler / Takip Planı',
    documents: 'Belgeler',
    viewAll: 'Tümünü Gör',
    noPurchases: 'Satın alma kaydı yok.',
    noTasks: 'Bu kişi için görev kaydı yok.',
    noDocuments: 'Bu kişiye bağlı belge yok.',
    noDocumentView: 'Belge görüntüleme yetkisi yok.',
    linkDocument: 'Mevcut belge ID ile bağla',
    linkDocumentAction: 'Belgeyi bağla',
    historyHeading: 'Yorumlar / İletişim Akışı',
    totalPurchases: 'Toplam Satın Alma',
    inProjects: 'aktif projede',
    communication: 'İletişim',
    lastContact: 'Son İletişim',
    lastUpdate: 'Son güncelleme',
    tags: 'Etiketler',
    addTag: 'Etiket ekle',
    removeTag: 'kaldır',
    source: 'Geliş Kaynağı',
    referrer: 'Yönlendiren / Acenta',
    createdAt: 'Oluşturulma Tarihi',
    updatedAt: 'Son güncelleme',
    displayName: 'Ad Soyad',
    firstName: 'Ad',
    lastName: 'Soyad',
    phone: 'Telefon',
    extraPhones: 'Ek telefonlar',
    extraPhone: 'Ek telefon',
    secondEmail: 'İkinci E-posta',
    extraEmails: 'Ek e-postalar',
    address: 'Adres',
    city: 'Şehir',
    region: 'Bölge',
    country: 'Ülke',
    language: 'Dil',
    budgetMin: 'Alıcı bütçesi (min)',
    budgetMax: 'Alıcı bütçesi (max)',
    buyerBudget: 'Alıcı bütçesi',
    company: 'Şirket',
    position: 'Pozisyon',
    notes: 'Notlar',
    roles: 'Tür / roller',
    role: 'Rol',
    owner: 'Sorumlu',
    ownerUser: 'Sorumlu kullanıcı',
    nextFollowUp: 'Sonraki takip',
    junkReasonField: 'Junk sebebi',
    junkReasonFree: 'Junk sebebi (serbest)',
    selectOrType: 'Seçin veya yazın',
    nameRequired: 'Ad soyad gerekli',
    invalidEmail: 'E-posta geçersiz',
    invalidPhone: 'Telefon numarası geçersiz.',
    invalidEmailMsg: 'E-posta adresi geçersiz.',
    complete: 'Tamamla',
    postpone: 'Ertele',
    hemenKira: 'Hemen Kira',
    agreementStatus: 'Durum',
    agreementDate: 'Anlaşma tarihi',
    investmentAmount: 'Yatırım Tutarı',
    unitNumber: 'Daire No',
    salePrice: 'Satış / anlaşma fiyatı',
    payment: 'Ödeme',
    deposit: 'Kapora',
    justNow: 'Az önce',
    minutesAgo: 'dk önce',
    minutesLater: 'dk sonra',
    hoursAgo: 'saat önce',
    hoursLater: 'saat sonra',
    daysAgo: 'gün önce',
    daysLater: 'gün sonra',
    purchased: 'Satın Alındı',
    cancelled: 'İptal',
    lost: 'Kaybedildi',
    unitChange: 'Daire değişikliği',
    loading: 'Yükleniyor…',
    taskPlaceholder: '24 Eyl 14:00 müşteriyi ara',
    people: 'Kişiler',
    person: 'Kişi',
    backToPerson: 'Kişiye dön',
    purchaseDetail: 'Satın Alma Detayı',
    amount: 'Tutar',
    unit: 'Daire',
    purchaseDate: 'Satın Alma Tarihi',
    purchasePrice: 'Satın Alma Fiyatı',
    editAmount: 'Tutarı düzenle',
    saveAmount: 'Tutarı kaydet',
    amountRequired: 'Tutar gerekli',
    owners: 'Sahipler',
    basics: 'Temel Bilgiler',
    noteKind: 'Yorum',
    callKind: 'Arama',
    followKind: 'Genel takip',
    proposalKind: 'Teklif takibi',
    notStarted: 'Başlamadı',
    inProgress: 'Devam ediyor',
    waiting: 'Beklemede',
    completed: 'Tamamlandı',
    sources: {
      instagram: 'Instagram Lead',
      facebook: 'Facebook Lead',
      whatsapp: 'WhatsApp',
      agency: 'Acenta',
      website: 'Web Sitesi',
      manual: 'Manuel',
    },
    roleLabels: {
      investor: 'Yatırımcı',
      prospect: 'Aday',
      buyer: 'Alıcı',
      broker: 'Acenta',
      realtor: 'Emlakçı',
      partner: 'Partner',
      vendor: 'Tedarikçi',
      contractor: 'Yüklenici',
      attorney: 'Avukat',
      lender: 'Finans',
      property_manager: 'Yönetici',
      architect: 'Mimar',
      consultant: 'Danışman',
      media_contact: 'Medya',
      government_contact: 'Kamu',
      internal_team: 'İç ekip',
    },
  },
  en: {
    title: 'Person Card',
    back: 'Back to people',
    tabs: {
      overview: 'Overview',
      purchases: 'Purchases',
      history: 'Communication',
      documents: 'Documents',
      tasks: 'Tasks',
    },
    loadError: 'Unable to load person',
    accessDenied: 'Access denied',
    saved: 'Saved',
    save: 'Save',
    saving: 'Saving…',
    saveFailed: 'Could not save',
    cancel: 'Cancel',
    edit: 'Edit',
    editPerson: 'Edit person',
    email: 'Email',
    whatsapp: 'WhatsApp',
    message: 'Message',
    meeting: 'Meeting',
    more: 'More',
    assignOwner: 'Assign owner',
    createTask: 'Create task',
    moveToJunk: 'Move to Junk',
    junkStatus: 'Status: Junk',
    junkReason: 'Junk reason',
    agent: 'Agency',
    active: 'Active',
    passive: 'Inactive',
    junk: 'Junk',
    addComment: 'Add comment',
    comment: 'Comment',
    type: 'Type',
    datetime: 'Date / time',
    createFollowUp: 'Create follow-up task',
    followUpDate: 'Follow-up date',
    yes: 'Yes',
    no: 'No',
    saveComment: 'Save comment',
    task: 'Task',
    description: 'Description',
    assignee: 'Assignee',
    date: 'Date',
    status: 'Status',
    saveTask: 'Save task',
    currentOwner: 'Current owner',
    newOwner: 'New owner',
    selectUser: 'Select user',
    saveAssignment: 'Save assignment',
    select: 'Select',
    general: 'Profile',
    purchases: 'Purchases',
    tasksHeading: 'Tasks',
    tasksPlan: 'Tasks / follow-up plan',
    documents: 'Documents',
    viewAll: 'View all',
    noPurchases: 'No purchases.',
    noTasks: 'No tasks for this person.',
    noDocuments: 'No documents linked to this person.',
    noDocumentView: 'You do not have permission to view documents.',
    linkDocument: 'Link existing document ID',
    linkDocumentAction: 'Link document',
    historyHeading: 'Comments / communication',
    totalPurchases: 'Total purchases',
    inProjects: 'active projects',
    communication: 'Communication',
    lastContact: 'Last contact',
    lastUpdate: 'Last updated',
    tags: 'Tags',
    addTag: 'Add tag',
    removeTag: 'remove',
    source: 'Lead source',
    referrer: 'Referrer / agency',
    createdAt: 'Created',
    updatedAt: 'Last updated',
    displayName: 'Full name',
    firstName: 'First name',
    lastName: 'Last name',
    phone: 'Phone',
    extraPhones: 'Additional phones',
    extraPhone: 'Additional phone',
    secondEmail: 'Second email',
    extraEmails: 'Additional emails',
    address: 'Address',
    city: 'City',
    region: 'Region',
    country: 'Country',
    language: 'Language',
    budgetMin: 'Buyer budget (min)',
    budgetMax: 'Buyer budget (max)',
    buyerBudget: 'Buyer budget',
    company: 'Company',
    position: 'Position',
    notes: 'Notes',
    roles: 'Type / roles',
    role: 'Role',
    owner: 'Owner',
    ownerUser: 'Responsible user',
    nextFollowUp: 'Next follow-up',
    junkReasonField: 'Junk reason',
    junkReasonFree: 'Junk reason (custom)',
    selectOrType: 'Select or type',
    nameRequired: 'Full name is required',
    invalidEmail: 'Invalid email',
    invalidPhone: 'Invalid phone number.',
    invalidEmailMsg: 'Invalid email address.',
    complete: 'Complete',
    postpone: 'Snooze',
    hemenKira: 'Immediate rent',
    agreementStatus: 'Status',
    agreementDate: 'Agreement date',
    investmentAmount: 'Investment amount',
    unitNumber: 'Unit no.',
    salePrice: 'Sale / agreement price',
    payment: 'Payment',
    deposit: 'Deposit',
    justNow: 'Just now',
    minutesAgo: 'min ago',
    minutesLater: 'min later',
    hoursAgo: 'hours ago',
    hoursLater: 'hours later',
    daysAgo: 'days ago',
    daysLater: 'days later',
    purchased: 'Purchased',
    cancelled: 'Cancelled',
    lost: 'Lost',
    unitChange: 'Unit change',
    loading: 'Loading…',
    taskPlaceholder: 'Call the client 24 Sep 14:00',
    people: 'People',
    person: 'Person',
    backToPerson: 'Back to person',
    purchaseDetail: 'Purchase detail',
    amount: 'Amount',
    unit: 'Unit',
    purchaseDate: 'Purchase date',
    purchasePrice: 'Purchase price',
    editAmount: 'Edit amount',
    saveAmount: 'Save amount',
    amountRequired: 'Amount is required',
    owners: 'Owners',
    basics: 'Overview',
    noteKind: 'Comment',
    callKind: 'Call',
    followKind: 'General follow-up',
    proposalKind: 'Proposal follow-up',
    notStarted: 'Not started',
    inProgress: 'In progress',
    waiting: 'Waiting',
    completed: 'Completed',
    sources: {
      instagram: 'Instagram Lead',
      facebook: 'Facebook Lead',
      whatsapp: 'WhatsApp',
      agency: 'Agency',
      website: 'Website',
      manual: 'Manual',
    },
    roleLabels: {
      investor: 'Investor',
      prospect: 'Prospect',
      buyer: 'Buyer',
      broker: 'Agency',
      realtor: 'Realtor',
      partner: 'Partner',
      vendor: 'Vendor',
      contractor: 'Contractor',
      attorney: 'Attorney',
      lender: 'Lender',
      property_manager: 'Manager',
      architect: 'Architect',
      consultant: 'Consultant',
      media_contact: 'Media',
      government_contact: 'Government',
      internal_team: 'Internal team',
    },
  },
} as const;

export type PersonCardCopy = (typeof PERSON_CARD_COPY)['en'];

export function personCardCopy(locale: string): PersonCardCopy {
  return locale === 'tr' ? PERSON_CARD_COPY.tr : PERSON_CARD_COPY.en;
}
