import type { PeopleWorkspacePreview } from './people-model';

/** Typed local fixtures for People UX review — no live API calls. */
export function makePeoplePreview(): PeopleWorkspacePreview {
  return {
    totalPeople: 582,
    totalPages: 30,
    kpis: [
      {
        key: 'total',
        value: 582,
        hintKey: 'totalHint',
        delta: '+32',
        deltaTone: 'up',
      },
      {
        key: 'active',
        value: 368,
        hintKey: 'activeHint',
        delta: '+21',
        deltaTone: 'up',
      },
      {
        key: 'decisionMakers',
        value: 146,
        hintKey: 'decisionMakersHint',
        delta: '+8',
        deltaTone: 'up',
      },
      {
        key: 'newThisMonth',
        value: 74,
        hintKey: 'newThisMonthHint',
        delta: '+28',
        deltaTone: 'up',
      },
      {
        key: 'meetingPending',
        value: 23,
        hintKey: 'meetingPendingHint',
        delta: '+5',
        deltaTone: 'up',
      },
    ],
    people: [
      {
        id: 'p-james',
        name: 'James Temple',
        titleKey: 'managingPartner',
        initials: 'JT',
        avatarTone: 'navy',
        company: 'The Temple Group',
        companyInitials: 'TG',
        companyTone: 'navy',
        role: 'decisionMaker',
        department: 'executive',
        country: 'us',
        hasEmail: true,
        hasPhone: true,
        hasLinkedIn: true,
        hasWhatsApp: false,
        lastActivityKey: 'meeting',
        lastActivityDate: '22.07.2026',
        relationScore: 94,
        relation: 'veryStrong',
        aiNoteKey: 'james',
        owner: 'Emin Bilgin',
        tags: ['strategic', 'capital'],
      },
      {
        id: 'p-sara',
        name: 'Sara Al-Hassan',
        titleKey: 'ceo',
        initials: 'SA',
        avatarTone: 'cyan',
        company: 'Marina Heights LLC',
        companyInitials: 'MH',
        companyTone: 'cyan',
        role: 'ceo',
        department: 'executive',
        country: 'ae',
        hasEmail: true,
        hasPhone: true,
        hasLinkedIn: true,
        hasWhatsApp: true,
        lastActivityKey: 'call',
        lastActivityDate: '21.07.2026',
        relationScore: 82,
        relation: 'strong',
        aiNoteKey: 'sara',
        owner: 'Ayşe Demir',
        tags: ['pipeline', 'coastal'],
      },
      {
        id: 'p-elena',
        name: 'Elena Brooks',
        titleKey: 'designDirector',
        initials: 'EB',
        avatarTone: 'violet',
        company: 'Bay Area Architects',
        companyInitials: 'BA',
        companyTone: 'violet',
        role: 'architect',
        department: 'design',
        country: 'us',
        hasEmail: true,
        hasPhone: false,
        hasLinkedIn: true,
        hasWhatsApp: false,
        lastActivityKey: 'email',
        lastActivityDate: '19.07.2026',
        relationScore: 68,
        relation: 'medium',
        aiNoteKey: 'elena',
        owner: 'Mehmet Kaya',
        tags: ['design'],
      },
      {
        id: 'p-oliver',
        name: 'Oliver Grant',
        titleKey: 'partner',
        initials: 'OG',
        avatarTone: 'amber',
        company: 'Liberty Law Partners',
        companyInitials: 'LL',
        companyTone: 'amber',
        role: 'lawyer',
        department: 'legal',
        country: 'uk',
        hasEmail: true,
        hasPhone: true,
        hasLinkedIn: false,
        hasWhatsApp: false,
        lastActivityKey: 'note',
        lastActivityDate: '15.07.2026',
        relationScore: 45,
        relation: 'attention',
        aiNoteKey: 'oliver',
        owner: 'Can Özkan',
        tags: ['legal', 'closing'],
      },
      {
        id: 'p-mia',
        name: 'Mia Chen',
        titleKey: 'opsLead',
        initials: 'MC',
        avatarTone: 'rose',
        company: 'Sunset Title Company',
        companyInitials: 'ST',
        companyTone: 'rose',
        role: 'operations',
        department: 'operations',
        country: 'us',
        hasEmail: true,
        hasPhone: false,
        hasLinkedIn: false,
        hasWhatsApp: true,
        lastActivityKey: 'task',
        lastActivityDate: '08.07.2026',
        relationScore: 32,
        relation: 'weak',
        aiNoteKey: 'mia',
        owner: 'Zeynep Arslan',
        tags: ['ops'],
      },
      {
        id: 'p-emre',
        name: 'Emre Yılmaz',
        titleKey: 'investmentLead',
        initials: 'EY',
        avatarTone: 'green',
        company: 'Bosphorus Capital',
        companyInitials: 'BC',
        companyTone: 'green',
        role: 'investor',
        department: 'investment',
        country: 'tr',
        hasEmail: true,
        hasPhone: true,
        hasLinkedIn: true,
        hasWhatsApp: true,
        lastActivityKey: 'meeting',
        lastActivityDate: '23.07.2026',
        relationScore: 88,
        relation: 'strong',
        aiNoteKey: 'emre',
        owner: 'Emin Bilgin',
        tags: ['capital', 'local'],
      },
      {
        id: 'p-wei',
        name: 'Wei Lin',
        titleKey: 'broker',
        initials: 'WL',
        avatarTone: 'cyan',
        company: 'Harbor Brokerage',
        companyInitials: 'HB',
        companyTone: 'cyan',
        role: 'broker',
        department: 'brokerage',
        country: 'sg',
        hasEmail: true,
        hasPhone: true,
        hasLinkedIn: true,
        hasWhatsApp: true,
        lastActivityKey: 'call',
        lastActivityDate: '20.07.2026',
        relationScore: 74,
        relation: 'medium',
        aiNoteKey: 'wei',
        owner: 'Ayşe Demir',
        tags: ['broker'],
      },
      {
        id: 'p-lukas',
        name: 'Lukas Weber',
        titleKey: 'relationshipMgr',
        initials: 'LW',
        avatarTone: 'navy',
        company: 'Nordic Trust Bank',
        companyInitials: 'NT',
        companyTone: 'navy',
        role: 'finance',
        department: 'finance',
        country: 'de',
        hasEmail: true,
        hasPhone: true,
        hasLinkedIn: true,
        hasWhatsApp: false,
        lastActivityKey: 'email',
        lastActivityDate: '18.07.2026',
        relationScore: 79,
        relation: 'strong',
        aiNoteKey: 'lukas',
        owner: 'Mehmet Kaya',
        tags: ['finance'],
      },
    ],
    recentPeople: [
      {
        id: 'recent-1',
        name: 'Emre Yılmaz',
        company: 'Bosphorus Capital',
        initials: 'EY',
        avatarTone: 'green',
        addedAtKey: 'hoursAgo2',
      },
      {
        id: 'recent-2',
        name: 'Wei Lin',
        company: 'Harbor Brokerage',
        initials: 'WL',
        avatarTone: 'cyan',
        addedAtKey: 'yesterday',
      },
      {
        id: 'recent-3',
        name: 'Lukas Weber',
        company: 'Nordic Trust Bank',
        initials: 'LW',
        avatarTone: 'navy',
        addedAtKey: 'daysAgo3',
      },
    ],
    upcomingMeetings: [
      {
        id: 'meet-1',
        name: 'Sara Al-Hassan',
        company: 'Marina Heights LLC',
        whenKey: 'jul241000',
      },
      {
        id: 'meet-2',
        name: 'James Temple',
        company: 'The Temple Group',
        whenKey: 'jul251430',
      },
      {
        id: 'meet-3',
        name: 'Emre Yılmaz',
        company: 'Bosphorus Capital',
        whenKey: 'jul261100',
      },
    ],
    sourceDistribution: [
      { key: 'referral', pct: 32 },
      { key: 'event', pct: 25 },
      { key: 'website', pct: 18 },
      { key: 'email', pct: 15 },
      { key: 'ads', pct: 6 },
      { key: 'other', pct: 4 },
    ],
    activePeople: [
      {
        id: 'ap-1',
        name: 'James Temple',
        initials: 'JT',
        avatarTone: 'navy',
        activityCount: 12,
        lastContactKey: 'daysAgo1',
      },
      {
        id: 'ap-2',
        name: 'Sara Al-Hassan',
        initials: 'SA',
        avatarTone: 'cyan',
        activityCount: 10,
        lastContactKey: 'daysAgo2',
      },
      {
        id: 'ap-3',
        name: 'Emre Yılmaz',
        initials: 'EY',
        avatarTone: 'green',
        activityCount: 9,
        lastContactKey: 'hoursAgo6',
      },
    ],
    owners: ['Emin Bilgin', 'Ayşe Demir', 'Mehmet Kaya', 'Can Özkan', 'Zeynep Arslan'],
    tags: ['strategic', 'capital', 'pipeline', 'coastal', 'design', 'legal', 'closing', 'ops', 'local', 'broker', 'finance'],
    companies: [
      'The Temple Group',
      'Marina Heights LLC',
      'Bay Area Architects',
      'Liberty Law Partners',
      'Sunset Title Company',
      'Bosphorus Capital',
      'Harbor Brokerage',
      'Nordic Trust Bank',
    ],
    countries: ['us', 'ae', 'uk', 'tr', 'de', 'sg'],
  };
}
