import type { AdminWorkspacePreview } from './admin-model';

/** Typed local fixtures for Admin UX review — no live API calls. */
export function makeAdminPreview(): AdminWorkspacePreview {
  return {
    totalUsers: 142,
    totalPages: 15,
    kpis: [
      {
        key: 'activeUsers',
        value: 142,
        hintKey: 'activeUsersHint',
        delta: '+12%',
        deltaTone: 'up',
      },
      {
        key: 'onlineUsers',
        value: 18,
        hintKey: 'onlineUsersHint',
      },
      {
        key: 'uptime',
        value: '99.98%',
        hintKey: 'uptimeHint',
      },
      {
        key: 'openAlerts',
        value: 3,
        hintKey: 'openAlertsHint',
      },
      {
        key: 'apiRequests',
        value: '24.850',
        hintKey: 'apiRequestsHint',
        delta: '+8%',
        deltaTone: 'up',
      },
    ],
    users: [
      {
        id: 'u-emin',
        name: 'Emin Bilgin',
        email: 'emin@investhome.com',
        initials: 'EB',
        avatarTone: 'navy',
        role: 'systemAdmin',
        workspace: 'platform',
        lastLoginLabel: '25.07.2026 18:42',
        lastLoginOnline: true,
        status: 'active',
        mfaEnabled: true,
        aiUsed: 12450,
        aiLimit: 50000,
        aiUsedLabel: '12.450',
        aiLimitLabel: '50.000',
      },
      {
        id: 'u-ayse',
        name: 'Ayşe Demir',
        email: 'ayse.demir@investhome.com',
        initials: 'AD',
        avatarTone: 'cyan',
        role: 'admin',
        workspace: 'crm',
        lastLoginLabel: '25.07.2026 17:10',
        lastLoginOnline: true,
        status: 'active',
        mfaEnabled: true,
        aiUsed: 8200,
        aiLimit: 30000,
        aiUsedLabel: '8.200',
        aiLimitLabel: '30.000',
      },
      {
        id: 'u-can',
        name: 'Can Yılmaz',
        email: 'can.yilmaz@investhome.com',
        initials: 'CY',
        avatarTone: 'amber',
        role: 'salesManager',
        workspace: 'sales',
        lastLoginLabel: '25.07.2026 15:22',
        status: 'active',
        mfaEnabled: true,
        aiUsed: 15600,
        aiLimit: 25000,
        aiUsedLabel: '15.600',
        aiLimitLabel: '25.000',
      },
      {
        id: 'u-selin',
        name: 'Selin Kara',
        email: 'selin.kara@investhome.com',
        initials: 'SK',
        avatarTone: 'green',
        role: 'salesRep',
        workspace: 'sales',
        lastLoginLabel: '25.07.2026 14:05',
        status: 'active',
        mfaEnabled: false,
        aiUsed: 4100,
        aiLimit: 15000,
        aiUsedLabel: '4.100',
        aiLimitLabel: '15.000',
      },
      {
        id: 'u-mert',
        name: 'Mert Özkan',
        email: 'mert.ozkan@investhome.com',
        initials: 'MÖ',
        avatarTone: 'violet',
        role: 'analyst',
        workspace: 'finance',
        lastLoginLabel: '24.07.2026 11:48',
        status: 'active',
        mfaEnabled: true,
        aiUsed: 9800,
        aiLimit: 20000,
        aiUsedLabel: '9.800',
        aiLimitLabel: '20.000',
      },
      {
        id: 'u-deniz',
        name: 'Deniz Aksoy',
        email: 'deniz.aksoy@investhome.com',
        initials: 'DA',
        avatarTone: 'rose',
        role: 'support',
        workspace: 'operations',
        lastLoginLabel: '23.07.2026 09:30',
        status: 'inactive',
        mfaEnabled: false,
        aiUsed: 1200,
        aiLimit: 10000,
        aiUsedLabel: '1.200',
        aiLimitLabel: '10.000',
      },
      {
        id: 'u-elif',
        name: 'Elif Şahin',
        email: 'elif.sahin@investhome.com',
        initials: 'EŞ',
        avatarTone: 'cyan',
        role: 'marketing',
        workspace: 'marketing',
        lastLoginLabel: '22.07.2026 16:18',
        status: 'suspended',
        mfaEnabled: true,
        aiUsed: 6400,
        aiLimit: 18000,
        aiUsedLabel: '6.400',
        aiLimitLabel: '18.000',
      },
      {
        id: 'u-burak',
        name: 'Burak Çetin',
        email: 'burak.cetin@investhome.com',
        initials: 'BC',
        avatarTone: 'navy',
        role: 'admin',
        workspace: 'platform',
        lastLoginLabel: '25.07.2026 12:01',
        lastLoginOnline: true,
        status: 'active',
        mfaEnabled: true,
        aiUsed: 22100,
        aiLimit: 40000,
        aiUsedLabel: '22.100',
        aiLimitLabel: '40.000',
      },
      {
        id: 'u-zeynep',
        name: 'Zeynep Arslan',
        email: 'zeynep.arslan@investhome.com',
        initials: 'ZA',
        avatarTone: 'green',
        role: 'salesRep',
        workspace: 'crm',
        lastLoginLabel: '21.07.2026 08:55',
        status: 'active',
        mfaEnabled: false,
        aiUsed: 2750,
        aiLimit: 15000,
        aiUsedLabel: '2.750',
        aiLimitLabel: '15.000',
      },
      {
        id: 'u-onur',
        name: 'Onur Kılıç',
        email: 'onur.kilic@investhome.com',
        initials: 'OK',
        avatarTone: 'amber',
        role: 'analyst',
        workspace: 'operations',
        lastLoginLabel: '20.07.2026 19:12',
        status: 'active',
        mfaEnabled: true,
        aiUsed: 11200,
        aiLimit: 20000,
        aiUsedLabel: '11.200',
        aiLimitLabel: '20.000',
      },
    ],
    roles: [
      { id: 'r-sys', role: 'systemAdmin', users: 2, descriptionKey: 'systemAdmin' },
      { id: 'r-adm', role: 'admin', users: 8, descriptionKey: 'admin' },
      { id: 'r-sm', role: 'salesManager', users: 12, descriptionKey: 'salesManager' },
      { id: 'r-sr', role: 'salesRep', users: 64, descriptionKey: 'salesRep' },
      { id: 'r-an', role: 'analyst', users: 18, descriptionKey: 'analyst' },
      { id: 'r-su', role: 'support', users: 22, descriptionKey: 'support' },
      { id: 'r-mk', role: 'marketing', users: 16, descriptionKey: 'marketing' },
    ],
    permissions: [
      {
        id: 'p1',
        workspace: 'crm',
        role: 'salesManager',
        accessKey: 'full',
      },
      {
        id: 'p2',
        workspace: 'sales',
        role: 'salesRep',
        accessKey: 'edit',
      },
      {
        id: 'p3',
        workspace: 'finance',
        role: 'analyst',
        accessKey: 'view',
      },
      {
        id: 'p4',
        workspace: 'platform',
        role: 'systemAdmin',
        accessKey: 'full',
      },
      {
        id: 'p5',
        workspace: 'marketing',
        role: 'marketing',
        accessKey: 'edit',
      },
      {
        id: 'p6',
        workspace: 'operations',
        role: 'support',
        accessKey: 'view',
      },
    ],
    auditRows: [
      {
        id: 'a1',
        eventKey: 'userCreated',
        actor: 'Emin Bilgin',
        timeLabel: '25.07.2026 18:12',
      },
      {
        id: 'a2',
        eventKey: 'roleUpdated',
        actor: 'Ayşe Demir',
        timeLabel: '25.07.2026 17:40',
      },
      {
        id: 'a3',
        eventKey: 'permissionChanged',
        actor: 'Burak Çetin',
        timeLabel: '25.07.2026 16:05',
      },
      {
        id: 'a4',
        eventKey: 'mfaEnabled',
        actor: 'Can Yılmaz',
        timeLabel: '25.07.2026 14:28',
      },
      {
        id: 'a5',
        eventKey: 'userSuspended',
        actor: 'Emin Bilgin',
        timeLabel: '24.07.2026 21:10',
      },
      {
        id: 'a6',
        eventKey: 'systemScan',
        actor: 'System',
        timeLabel: '24.07.2026 03:00',
      },
    ],
    services: [
      { id: 's-api', service: 'api', statusKey: 'running', detail: 'v2.14.3' },
      { id: 's-web', service: 'web', statusKey: 'running', detail: 'edge-12' },
      { id: 's-db', service: 'database', statusKey: 'running', detail: 'primary' },
      { id: 's-q', service: 'queue', statusKey: 'running', detail: 'redis-a' },
      { id: 's-st', service: 'storage', statusKey: 'running', detail: 's3-eu' },
    ],
    health: [
      { key: 'api', statusKey: 'running' },
      { key: 'web', statusKey: 'running' },
      { key: 'database', statusKey: 'running' },
      { key: 'queue', statusKey: 'running' },
      { key: 'storage', statusKey: 'running' },
    ],
    recentAudit: [
      {
        id: 'ra1',
        eventKey: 'userCreated',
        actor: 'Emin Bilgin',
        timeLabel: '2 dk önce',
      },
      {
        id: 'ra2',
        eventKey: 'roleUpdated',
        actor: 'Ayşe Demir',
        timeLabel: '18 dk önce',
      },
      {
        id: 'ra3',
        eventKey: 'permissionChanged',
        actor: 'Burak Çetin',
        timeLabel: '1 sa önce',
      },
      {
        id: 'ra4',
        eventKey: 'mfaEnabled',
        actor: 'Can Yılmaz',
        timeLabel: '3 sa önce',
      },
      {
        id: 'ra5',
        eventKey: 'systemScan',
        actor: 'System',
        timeLabel: '6 sa önce',
      },
    ],
    workers: [
      { id: 'w1', name: 'Worker 1', statusKey: 'running', heartbeat: '12 sn' },
      { id: 'w2', name: 'Worker 2', statusKey: 'running', heartbeat: '18 sn' },
      { id: 'w3', name: 'Worker 3', statusKey: 'running', heartbeat: '9 sn' },
      { id: 'w4', name: 'Worker 4', statusKey: 'idle', heartbeat: '41 sn' },
    ],
    queues: [
      { key: 'mail', pending: 12 },
      { key: 'notification', pending: 3 },
      { key: 'import', pending: 0 },
      { key: 'ai', pending: 8 },
    ],
    apiPerformance: {
      points: [42, 48, 45, 52, 58, 55, 62, 70, 66, 74, 80, 76, 84, 90, 86, 92],
      requestsLabel: '24.850',
      avgResponse: '142ms',
      errorRate: '0.02%',
    },
    workspaces: ['crm', 'sales', 'finance', 'marketing', 'operations', 'platform'],
  };
}
